# Tugas Praktikum 3 PD NUMERIK

Kembali ke [Persamaan Diferensial Numerik](../pdnum2023.qmd)

## Petunjuk Pengumpulan Tugas

1. Tugas ini dikerjakan secara individu.

2. Terdapat satu (1) soal yang harus dijawab.

3. File yang harus diunggah terdiri dari:

    a. beberapa function file sesuai kebutuhan. Penamaan untuk function file dibebaskan, selama masih relevan dengan isi fungsinya (dilarang menamakan function file "adamsorde5.m" jika isinya adalah metode Runge-Kutta).

    b. satu (1) script file untuk jawaban. Penamaannya adalah "soal.m" untuk soal yang diberikan.

    c. satu (1) file PDF untuk penjelasan keseluruhan soal. Penjelasan diketik dalam Word atau sejenisnya dengan format penamaan "Penjelasan.pdf".

4. Semua file disatukan dalam satu file .zip dengan format penamaan:

[Nama]\_[NPM]\_[Kelas SIAK]_Tugas 1_Prak PDNum.zip

Contoh: "Cristiano-Ronaldo_2101234567_C_Tugas 1_Prak PDNum.zip"

5. Batas pengumpulan tugas ini adalah 16 April  2023, pukul 23.59 WIB.

Tugas dikumpulkan melalui gform sesuai dengan kelas masing-masing:

Link: [ristek.link/Tugas3PrakPDNum](ristek.link/Tugas3PrakPDNum)


6. Dilarang melakukan **plagiarisme**. Jika terdapat mahasisya yang terindikasi melakukan plagiarisme, **maka mahasiswa tersebut memperoleh nilai 0** untuk tugas ini.

7. Apabila ada yang ingin ditanyakan anda dapat bertanya pada kolom komentar atau, silakan mengontak salah satu kontak berikut:
    * LINE: Carles_Octavianus (carles)


## SOAL

### Sfixfoal 1

Ubahlah 2 metode persamaan differential numerik (dapat berupa metode single-step ataupun multi-step) favorit (selain runge-kutta tentunya) menjadi metode yang dapat menyelesaikan sistem persamaan differensial.

gunakan  kedua metode tersebut unutk menyelesaikan persamaan differensial berikut:

$y^{\prime \prime}-2 y^{\prime}+y=t e^t-t, \quad 0 \leq t \leq 1, \quad y(0)=y^{\prime}(0)=0$, dengan $h=0.1$ dengan solusi analitiknya: $y(t)=\frac{1}{6} t^3 e^t-t e^t+2 e^t-t-2$

dan Buatlah grafik perbandingan dari metode tersebut. 












