---
title: "Praktikum PDNum (Persamaan Diferensial Numerik) 2024 Genap (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

# Timeline

- [Modul 1: Pengenalan GNU Octave](./modul1.ipynb), 21-22 Februari 2024 (*offline* di Lab Komputer D.311 untuk sesi 1 dan sesi 2, dan di Lab Statistika D.406 untuk sesi 3)

- [Modul 2: Plotting Fungsi, Metode Euler, Metode Taylor](./modul2.ipynb), 28-29 Februari 2024 (*offline* di Lab Komputer D.311 untuk sesi 1 dan sesi 2, dan di Lab Statistika D.406 untuk sesi 3)

- [Modul 3: Metode Runge-Kutta dan variasinya](./modul3.ipynb), 6-7 Maret 2024 (*offline* di Lab Komputer D.311 untuk sesi 1 dan sesi 2)

- [Modul 4: Metode Multistep](./modul4.ipynb), 13-14 Maret 2024

- [Modul 5: Sistem PDB orde 1 dan PDB orde tinggi](./modul5.ipynb), 17-18 April 2024 (Sesi 1 *online*, Sesi 2 *offline*)

- [Modul 6: Metode *Shooting* dan *Linear Finite Difference* untuk Masalah Nilai Batas PDB](./modul6.ipynb), 24-25 April 2024

- [Modul 7: *Nonlinear Finite Difference*, PDP Eliptik & Hiperbolik](./modul7.ipynb), Kamis, 2 Mei 2024, *online* melalui Zoom

- [Modul 8: PDP Parabolik](./modul8.ipynb), Rabu, 8 Mei 2024, *hybrid*: *offline* di D.311 dan *online* melalui Zoom

- [Modul 9: PDP orde 1, persamaan transport/adveksi](./modul9.ipynb), 15-16 Mei 2024, *offline* di D.311

**Tugas Akhir**

- [Tugas 1: Masalah Nilai Awal PDB Numerik](./tugas1.qmd)

    Diberikan: Senin, 10 Juni 2024

    *Deadline*: Jumat, 14 Juni 2024, 23.59 WIB

- [Tugas 2: Masalah Nilai Batas PDB Numerik](./tugas2.qmd)

    Diberikan: Senin, 10 Juni 2024

    *Deadline*: Jumat, 14 Juni 2024, 23.59 WIB

- [Tugas 3: PDP Numerik](./tugas3.qmd)

    Diberikan: Senin, 10 Juni 2024

    *Deadline*: Jumat, 14 Juni 2024, 23.59 WIB

# Rekaman praktikum

Untuk pertemuan-pertemuan praktikum PDNum (Persamaan Diferensial Numerik) yang dilaksanakan secara *online* melalui Zoom, semua rekaman disimpan di *link* berikut.

<https://bit.ly/RekamanPrakPDNum2024Genap>
