---
title: "Tugas 2 Praktikum Persamaan Diferensial Numerik 2024 Genap: Masalah Nilai Batas PDB Numerik"
---

**Semester Genap Tahun Ajaran 2023/2024**

Kembali ke [Persamaan Diferensial Numerik](./pdnum2024genap.qmd)

## Petunjuk Umum

1. Tugas ini dikerjakan secara individu.

2. Terdapat dua (2) soal yang harus dijawab.

3. *File-file* yang harus diunggah terdiri dari:

    a. Beberapa *function file* sesuai kebutuhan. Penamaan untuk *function file* dibebaskan (tentunya nama fungsinya harus menyesuaikan), selama masih relevan dengan isi fungsinya (misalnya, dilarang menamakan *function file* `adamsorde5.m` jika isinya adalah metode Runge-Kutta).

    b. Sejumlah *script file* sesuai ketentuan soal.

    c. Satu *file* .pdf (format penamaan: "penjelasan.pdf") yang berisi penjelasan terkait jawaban kalian, sesuai permintaan soal. Pembuatannya bebas apakah menggunakan Word, LaTeX, atau yang lainnya. Jangan lupa tuliskan nama lengkap, NPM, kelas, dan judul "Tugas 2 Persamaan Diferensial Numerik 2024 Genap".

4. Semua *file* disatukan dalam satu *file* .zip dengan format penamaan:

    `[Nama Lengkap]_[NPM]_[Kelas SIAK]_Tugas 2_Prak PDNum.zip`

    Contoh: `Sung Jinwoo_2201234567_C_Tugas 2_Prak PDNum.zip`

5. Batas pengumpulan tugas ini adalah Jumat, 14 Juni 2024, pukul 23.59 WIB. Tugas dikumpulkan sesuai dengan kelas SIAK (link akan selalu sama untuk semua tugas praktikum PDNum):

    Kelas A: <https://forms.gle/sdSZAfFZJkNu9rK68>

    Kelas B: <https://forms.gle/wdvZJ4c1UvifV5gEA>

    Keterlambatan akan dikenakan pengurangan nilai.

6. Dilarang dengan keras melakukan plagiarisme, baik mencontek ataupun dicontek. Jika terdapat mahasiswa yang terindikasi melakukan plagiarisme, maka mahasiswa tersebut memperoleh nilai 0 untuk tugas ini. Namun, Anda sangat dianjurkan memanfaatkan apapun yang ada di [modul praktikum](./pdnum2024genap.qmd).

7. Apabila ada pertanyaan, harap hubungi CP:
    
    Bisma (LINE: bisma_joyosumarto)
    
    Karina (LINE: karinac12)

## Soal

Tugas ini terdiri dari soal 1a-1d dan 2a-2e.

1. Diberikan masalah nilai batas (MNB) linier / *Linear Boundary Value Problem* (BVP)

    $$y'' = -4x^{(-1)}y' - 2x^{(-2)}y + 2x^{(-2)}\ln{(x)}, \quad 1 \le x \le 2,$$

    $$y(1) = -\frac{1}{2}, \quad y(2) = \ln{2}$$

    dan diketahui solusi eksaknya adalah

    $$y(x) = \ln{(x)} + \frac{5}{x} - \frac{4}{x^2} - \frac{3}{2}$$

    Dengan $h = 0.1$,

    a. Di *file* penjelasan, cocokkan PDB di atas dengan bentuk umum masalah nilai batas linier

        $$y'' = p(x)y' + q(x)y + r(x), \quad a \le x \le b,$$

        $$y(a) = \alpha, \quad y(b) = \beta$$

        yaitu tentukan fungsi $p(x)$, fungsi $q(x)$, fungsi $r(x)$, nilai $a$, nilai $b$, nilai $\alpha$, dan nilai $\beta$.

    b. Buatlah *script file* `soal_1b.m` berisi penggunaan metode *linear shooting* untuk mengaproksimasi solusi dari MNB tersebut. Bandingkan dengan solusi analitik (cukup $y(t)$ saja), sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan, serta perhitungan nilai $N$.

        Hint: untuk metode *shooting* (linier maupun nonlinier),

        $$h = \frac{b-a}{N}$$

    c. Buatlah *script file* `soal_1c.m` berisi penggunaan metode *linear finite difference* untuk mengaproksimasi solusi dari MNB tersebut. Bandingkan dengan solusi analitik, sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan, serta perhitungan nilai $N$.

        Hint: untuk metode *finite difference* untuk masalah nilai batas (linier maupun nonlinier),

        $$h = \frac{b-a}{N+1}$$

    d. Di *file* penjelasan, berikan argumen Anda: di antara kedua metode tersebut, apakah ada metode yang jelas lebih baik untuk masalah ini, ataukah sama-sama cukup baik?

2. Diberikan masalah nilai batas nonlinier

    $$y'' = \frac{1}{2} \left(1 - \left(y'\right)^2 - y \sin{x}\right), \quad 0 \le x \le \pi$$

    $$y(0) = 2, \quad y(\pi) = 2$$

    dan diketahui solusi eksaknya adalah

    $$y(x) = 2 + \sin{x}$$

    Dengan toleransi $10^{-4}$ dan $h = \frac{\pi}{20}$,

    a. Di *file* penjelasan, cocokkan PDB di atas dengan bentuk umum masalah nilai batas

        $$y'' = f(x, y, y'), \quad a \le x \le b,$$

        $$y(a) = \alpha, \quad y(b) = \beta$$

        yaitu tentukan fungsi $f(x, y, y')$, nilai $a$, nilai $b$, nilai $\alpha$, dan nilai $\beta$.

    b. Di *file* penjelasan, uraikan perhitungan $f_y(x,y,y')$ (yaitu $\frac{\partial f}{\partial y}(x,y,y')$) dan $f_{y'}(x,y,y')$ (yaitu $\frac{\partial f}{\partial y'}(x,y,y')$) secara analitik (turunan parsial).

    c. Buatlah *script file* `soal_2c.m` berisi penggunaan metode *nonlinear shooting* untuk mengaproksimasi solusi dari MNB tersebut. Bandingkan dengan solusi analitik (cukup $y(t)$ saja), sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan, serta perhitungan nilai $N$.

    d. Buatlah *script file* `soal_2d.m` berisi penggunaan metode *nonlinear finite difference* untuk mengaproksimasi solusi dari MNB tersebut. Bandingkan dengan solusi analitik, sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan, serta perhitungan nilai $N$.

    e. Di *file* penjelasan, berikan argumen Anda: di antara kedua metode tersebut, apakah ada metode yang jelas lebih baik untuk masalah ini, ataukah sama-sama cukup baik?
