---
title: "Tugas 1 Praktikum Persamaan Diferensial Numerik 2024 Genap: Masalah Nilai Awal PDB Numerik"
---

**Semester Genap Tahun Ajaran 2023/2024**

Kembali ke [Persamaan Diferensial Numerik](./pdnum2024genap.qmd)

## Petunjuk Umum

1. Tugas ini dikerjakan secara individu.

2. Terdapat dua (2) soal yang harus dijawab.

3. *File-file* yang harus diunggah terdiri dari:

    a. Beberapa *function file* sesuai kebutuhan. Penamaan untuk *function file* dibebaskan (tentunya nama fungsinya harus menyesuaikan), selama masih relevan dengan isi fungsinya (misalnya, dilarang menamakan *function file* `adamsorde5.m` jika isinya adalah metode Runge-Kutta).

    b. Sejumlah *script file* sesuai ketentuan soal.

    c. Satu *file* .pdf (format penamaan: "penjelasan.pdf") yang berisi penjelasan terkait jawaban kalian, sesuai permintaan soal. Pembuatannya bebas apakah menggunakan Word, LaTeX, atau yang lainnya. Jangan lupa tuliskan nama lengkap, NPM, kelas, dan judul "Tugas 1 Persamaan Diferensial Numerik 2024 Genap".

4. Semua *file* disatukan dalam satu *file* .zip dengan format penamaan:

    `[Nama Lengkap]_[NPM]_[Kelas SIAK]_Tugas 1_Prak PDNum.zip`

    Contoh: `Satoru Gojo_2201234567_C_Tugas 1_Prak PDNum.zip`

5. Batas pengumpulan tugas ini adalah Jumat, 14 Juni 2024, pukul 23.59 WIB. Tugas dikumpulkan sesuai dengan kelas SIAK (link akan selalu sama untuk semua tugas praktikum PDNum):

    Kelas A: <https://forms.gle/sdSZAfFZJkNu9rK68>

    Kelas B: <https://forms.gle/wdvZJ4c1UvifV5gEA>

    Keterlambatan akan dikenakan pengurangan nilai.

6. Dilarang dengan keras melakukan plagiarisme, baik mencontek ataupun dicontek. Jika terdapat mahasiswa yang terindikasi melakukan plagiarisme, maka mahasiswa tersebut memperoleh nilai 0 untuk tugas ini. Namun, Anda sangat dianjurkan memanfaatkan apapun yang ada di [modul praktikum](./pdnum2024genap.qmd).

7. Apabila ada pertanyaan, harap hubungi CP:
    
    Bisma (LINE: bisma_joyosumarto)
    
    Karina (LINE: karinac12)

## Soal

Tugas ini terdiri dari soal 1a-1d dan 2a-2e.

1. Diberikan suatu masalah nilai awal (MNA) / *initial value problem* (IVP):

    $$
    \begin{aligned}
    & y^{\prime}=\frac{y^{2}}{1+t}, \quad 1 \leq t \leq 2 \\
    & y(1)=-(\ln 2)^{-1}
    \end{aligned}
    $$

    Diketahui solusi eksak dari MNA tersebut adalah:

    $$
    y(t)=-\frac{1}{\ln (t+1)}
    $$

    Dengan $h=0.05$,

    a. Di *file* penjelasan, cocokkan MNA di atas dengan bentuk umum MNA PDB orde 1

        $$y' = f(t,y), \quad a \le t \le b$$
        $$y(a) = \alpha$$

        yaitu tentukan fungsi $f(t,y)$, nilai $a$, nilai $b$, dan nilai $\alpha$. Hitung juga nilai $N$.

    b. Buatlah *script file* `soal_1b.m` berisi penggunaan satu metode ***one-step*** pilihan Anda untuk mengaproksimasi solusi dari MNA tersebut. (Tentunya, perolehlah terlebih dahulu *function file* yang sesuai dari modul praktikum.) Bandingkan dengan solusi analitik, sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan.

    c. Buatlah *script file* `soal_1c.m` berisi penggunaan satu metode ***multistep*** pilihan Anda untuk mengaproksimasi solusi dari MNA tersebut. Bandingkan dengan solusi analitik, sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan.

    d. Di *file* penjelasan, berikan argumen Anda: di antara kedua metode tersebut, apakah ada metode yang jelas lebih baik untuk masalah ini, ataukah sama-sama cukup baik?

2. Diberikan MNA PDB orde 2

    $$y^{\prime \prime}-2 y^{\prime}+y=t e^t-t, \quad 0 \leq t \leq 1, \quad y(0)=y^{\prime}(0)=0$$
    
    dan diketahui solusi analitiknya:

    $$y(t)=\frac{1}{6} t^3 e^t-t e^t+2 e^t-t-2$$

    Dengan $h=0.05$,

    a. Di *file* penjelasan, tentukan rumus $y'(t)$ dari solusi analitik yang diberikan.

    b. Di *file* penjelasan, berikan uraian mengubah MNA PDB orde 2 tersebut menjadi sistem MNA PDB orde 1. Hitung juga nilai $N$.

    c. Buatlah *script file* `soal_2c.m` berisi penggunaan satu metode ***one-step*** pilihan Anda untuk mengaproksimasi solusi dari sistem tersebut. Bandingkan dengan solusi analitik (baik $y(t)$ maupun $y'(t)$), sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan.

    d. Buatlah *script file* `soal_2d.m` berisi penggunaan satu metode ***multistep*** pilihan Anda untuk mengaproksimasi solusi dari sistem tersebut. Bandingkan dengan solusi analitik (baik $y(t)$ maupun $y'(t)$), sertakan perhitungan *error*. Lampirkan tabel dan gambar grafiknya di *file* penjelasan.

    e. Di *file* penjelasan, berikan argumen Anda: di antara kedua metode tersebut, apakah ada metode yang jelas lebih baik untuk masalah ini, ataukah sama-sama cukup baik?
