---
title: "Tugas 3 Praktikum Persamaan Diferensial Numerik 2024 Genap: PDP Numerik"
filters:
  - parse-latex
---

**Semester Genap Tahun Ajaran 2023/2024**

Kembali ke [Persamaan Diferensial Numerik](./pdnum2024genap.qmd)

## Petunjuk Umum

1. Tugas ini dikerjakan secara individu.

2. Terdapat tiga (3) soal yang harus dijawab.

3. *File-file* yang harus diunggah terdiri dari:

    a. Beberapa *function file* sesuai kebutuhan. Penamaan untuk *function file* dibebaskan (tentunya nama fungsinya harus menyesuaikan), selama masih relevan dengan isi fungsinya (misalnya, dilarang menamakan *function file* `adamsorde5.m` jika isinya adalah metode Runge-Kutta).

    b. Sejumlah *script file* sesuai ketentuan soal.

    c. Satu *file* .pdf (format penamaan: "penjelasan.pdf") yang berisi penjelasan terkait jawaban kalian, sesuai permintaan soal. Pembuatannya bebas apakah menggunakan Word, LaTeX, atau yang lainnya. Jangan lupa tuliskan nama lengkap, NPM, kelas, dan judul "Tugas 3 Persamaan Diferensial Numerik 2024 Genap".

4. Semua *file* disatukan dalam satu *file* .zip dengan format penamaan:

    `[Nama Lengkap]_[NPM]_[Kelas SIAK]_Tugas 3_Prak PDNum.zip`

    Contoh: `Kibutsuji Muzan_2201234567_C_Tugas 3_Prak PDNum.zip`

5. Batas pengumpulan tugas ini adalah Jumat, 14 Juni 2024, pukul 23.59 WIB. Tugas dikumpulkan sesuai dengan kelas SIAK (link akan selalu sama untuk semua tugas praktikum PDNum):

    Kelas A: <https://forms.gle/sdSZAfFZJkNu9rK68>

    Kelas B: <https://forms.gle/wdvZJ4c1UvifV5gEA>

    Keterlambatan akan dikenakan pengurangan nilai.

6. Dilarang dengan keras melakukan plagiarisme, baik mencontek ataupun dicontek. Jika terdapat mahasiswa yang terindikasi melakukan plagiarisme, maka mahasiswa tersebut memperoleh nilai 0 untuk tugas ini. Namun, Anda sangat dianjurkan memanfaatkan apapun yang ada di [modul praktikum](./pdnum2024genap.qmd).

7. Apabila ada pertanyaan, harap hubungi CP:
    
    Bisma (LINE: bisma_joyosumarto)
    
    Karina (LINE: karinac12)

## Soal

Tugas ini terdiri dari soal 1a-1d, 2a-2f, dan 3a-3e.

1. Diberikan masalah persamaan *transport* (adveksi):

    $$u_t + 2u_x = 0, \quad 0 < x < 2, \quad 0 < t < 3$$

    $$u(x,0) = e^{-x^2}, \quad 0 \le x \le 2$$

    $$u(0,t) = e^{-4t^2}, \quad 0 < t < 3$$

    $$u(2,t) = e^{-4\left(1-t\right)^2}, \quad 0 < t < 3$$

    yang memiliki solusi eksak $u(x,t) = e^{-\left(x-2t\right)^2}$.

    Dengan $\Delta x = \Delta t = 0.1$,

    a. Di *file* penjelasan, cocokkan PDP di atas dengan bentuk umum persamaan *transport*

        $$u_t + du_x = 0, \quad \text{xb} < x < \text{xu}, \quad \text{tb} < t < \text{tu}$$

        $$u(x,\text{tb}) = f(x), \quad \text{xb} \le x \le \text{xu}$$

        $$u(\text{xb},t) = \text{lb}(t), \quad \text{tb} < t < \text{tu}$$

        $$u(\text{xu},t) = \text{rb}(t), \quad \text{tb} < t < \text{tu}$$

        yaitu tentukan nilai $d$, nilai $\text{xb}$, nilai $\text{xu}$, nilai $\text{tb}$, nilai $\text{tu}$, fungsi $f(x)$, fungsi $\text{lb}(t)$, dan fungsi $\text{rb}(t)$.

    b. Buatlah *script file* `soal_1b.m` berisi penggunaan metode Courant-Isaacson-Rees untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya (termasuk grafik solusi analitik) di *file* penjelasan (putar dulu grafiknya agar lebih terlihat). Seberapa mirip hasilnya dengan solusi analitik?

    c. Buatlah *script file* `soal_1c.m` berisi penggunaan metode Richardson untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya di *file* penjelasan (putar dulu grafiknya agar lebih terlihat). Apakah solusi numeriknya stabil?

    d. Buatlah *script file* `soal_1d.m` berisi penggunaan metode Lax untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya di *file* penjelasan (putar dulu grafiknya agar lebih terlihat). Seberapa mirip hasilnya dengan solusi analitik?

2. Diberikan masalah nilai awal-batas

    $$\begin{aligned}
        u_t &= 3u_{xx}, \quad 0 \le x \le \pi, \quad 0 < t < T, \\
        u(0,t) &= u(\pi, t) = 0, \quad 0 < t \le T, \\
        u(x,0) &= 3\sin{(2x)} - 6\sin{(5x)}, \quad 0 \le x \le \pi
    \end{aligned}$$

    dan ~~setelah menggunakan metode pemisahan variabel di UAS PDP tahun ini~~ diketahui solusi eksaknya adalah

    $$u(x,t) = 3e^{-12t} \sin{(2x)} - 6e^{-75t} \sin{(5x)}$$

    Dengan $T=2$,

    a. Di *file* penjelasan, uraikan pemeriksaan diskriminan dari PDP tersebut untuk memastikan bahwa PDP di atas tergolong parabolik.

    b. Di *file* penjelasan, cocokkan PDP parabolik di atas dengan bentuk umum persamaan panas

        $$\frac{\partial u}{\partial t} (x,t) = \alpha^2 \frac{\partial^2 u}{\partial x^2}(x,t), \quad \text{xb} < x < \text{xu}, \quad \text{tb} < t < \text{tu},$$

        $$u(x,0) = f(x), \quad \text{xb} \le x \le \text{xu}$$

        $$u(0,t) = \text{lb}(t) = 0, \quad \text{tb} < t \le \text{tu}$$

        $$u(l,t) = \text{rb}(t) = 0, \quad \text{tb} < t \le \text{tu}$$

        yaitu tentukan nilai $\alpha^2$, nilai $\text{xb}$, nilai $\text{xu}$, nilai $\text{tb}$, nilai $\text{tu}$, fungsi $f(x)$, fungsi $\text{lb}(t)$, dan fungsi $\text{rb}(t)$.

    c. Dengan $h = \Delta x = \frac{\pi}{10}$ dan $k = \Delta t = 0.1$, uraikan perhitungan nilai $\lambda$ di *file* penjelasan. Apakah $\lambda \le \frac{1}{2}$?

    d. Buatlah *script file* `soal_2d.m` berisi penggunaan metode *forward-difference* untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya (termasuk grafik solusi analitik) di *file* penjelasan. Apakah solusi numeriknya stabil?

    e. Buatlah *script file* `soal_2e.m` berisi penggunaan metode *backward-difference* untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya di *file* penjelasan. Seberapa mirip hasilnya dengan solusi analitik?

    f. Buatlah *script file* `soal_2f.m` berisi penggunaan metode Crank-Nicolson untuk mengaproksimasi solusi dari PDP tersebut. Lampirkan gambar grafiknya di *file* penjelasan. Seberapa mirip hasilnya dengan solusi analitik?

3. Diberikan persamaan gelombang

    $$\frac{\partial^2 u}{\partial t^2} - \frac{1}{16\pi^2} \frac{\partial^2 u}{\partial x^2} = 0, \quad 0 < x < 0.5, \quad 0 < t < 0.5$$

    $$u(x,0) = 0, \quad 0 \le x \le 0.5$$

    $$\frac{\partial u}{\partial t}(x,0) = \sin{4\pi x}, \quad 0 \le x \le 0.5$$

    $$u(0,t) = u(0.5, t) = 0, \quad t > 0$$

    yang diketahui solusi eksaknya adalah

    $$u(x,t) = \sin{(t)} \sin{(4\pi x)}$$

    a. Di *file* penjelasan, uraikan pemeriksaan diskriminan dari PDP tersebut untuk memastikan bahwa PDP di atas tergolong hiperbolik.

    b. Di *file* penjelasan, cocokkan persamaan gelombang di atas dengan bentuk umum

        $$\frac{\partial^2 u}{\partial t^2}\left(x,t\right) - \alpha^2 \frac{\partial^2 u}{\partial  x^2}\left(x,t\right) = 0, \quad \text{xb} < x < \text{xu}, \quad \text{tb} < t < \text{tu}$$

        $$u\left(x,0\right) = f\left(x\right), \quad \frac{\partial u}{\partial t}\left(x,0\right) = g\left(x\right), \quad \text{xb} \le x \le \text{xu}$$

        $$u\left(0,t\right) = \text{lb}\left(t\right), \quad \text{tb} < t \le \text{tu}$$

        $$u\left(l,t\right) = \text{rb}\left(t\right), \quad \text{tb} < t \le \text{tu}$$

        yaitu tentukan nilai $\alpha^2$, nilai $\text{xb}$, nilai $\text{xu}$, nilai $\text{tb}$, nilai $\text{tu}$, fungsi $f(x)$, fungsi $g(x)$, fungsi $\text{lb}(t)$, dan fungsi $\text{rb}(t)$.

    c. Buatlah *script file* `soal_3c.m` untuk mengaproksimasi solusi dari persamaan gelombang tersebut dengan $m=4$ dan $N=4$. Lampirkan hasil *output* grid-grid, *error* totalnya, dan gambar grafiknya di *file* penjelasan.

    d. Di *file* penjelsan, tulis ulang *output* grid aproksimasi dengan rapi (misalnya menggunakan fitur tabel di Word atau LaTeX) disertai nilai $x$ di tiap kolom (sebelah bawah) dan nilai $t$ di tiap baris (sebelah kiri).

        Contohnya, hasil *output* berikut dengan $x_0=0$, $t_0=0$, $\Delta x = 0.25$ dan $\Delta t = 0.25$,

        ```
            0  -0.7071  -1.0000  -0.7071        0
            0  -0.5000  -0.7071  -0.5000        0
            0        0        0  -0.0000        0
            0   0.5000   0.7071   0.5000        0
            0   0.7071   1.0000   0.7071   0.0000
        ```

        ditulis dengan rapi menjadi
        
        ```{=latex}
        \begin{tabular}{r|r|r|r|r|r}
            &&&&&\\
            $t_4 = 1$     & 0     & -0.7071 & -1.0000 & -0.7071 & 0 \\
            \hline
            $t_3 = 0.75$  & 0     & -0.5000 & -0.7071 & -0.5000 & 0 \\
            \hline
            $t_2 = 0.5$   & 0     &       0 &       0 & -0.0000 & 0 \\
            \hline
            $t_1 = 0.25$  & 0     &  0.5000 &  0.7071 &  0.5000 & 0 \\
            \hline
            $t_0 = 0$     & 0     &  0.7071 &  1.0000 &  0.7071 & 0.0000 \\
            \hline
                        & $x_0=0$ & $x_1=0.25$& $x_2=0.5$ & $x_3=0.75$& $x_4=1$
        \end{tabular}$$
        ```

    e. Di *file* penjelsan, tulis ulang *output* grid solusi eksak dengan rapi (misalnya menggunakan fitur tabel di Word atau LaTeX) disertai nilai $x$ di tiap kolom (sebelah bawah) dan nilai $t$ di tiap baris (sebelah kiri).
