---
title: "Praktikum Saindat (Sains Data) 2024 Genap (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

# Timeline

- [Modul 1: Pengenalan Pandas, Transformasi Data](./modul1.ipynb), 19-20 Februari 2024 (*offline* di Lab Komputer D.311)

- [Modul 2: Pengenalan Seaborn, Visualisasi Data](./modul2.ipynb), 26-27 Februari 2024 (*offline* di Lab Komputer D.311)

- [Modul 3: *Encoding* Data Kategorik dan Imputasi Data](./modul3.ipynb), 4-5 Maret 2024 (*offline* di Lab Komputer D.311)

- [Modul 4: Regresi](./modul4.ipynb), 13 Maret 2024 (*online* melalui Zoom)

- [Modul 5: Decision Tree, SVM](./modul5.ipynb), 16 April 2024 (*online* melalui Zoom)

- [Modul 6: K-Nearest Neighbors, K-Means Clustering](./modul6.ipynb), 22-23 April 2024

- [Modul 7: Pengantar *Neural Network* dengan TensorFlow & Keras](./modul7.ipynb), 29-30 April 2024

- [Modul 8: *Deep Learning* dengan Keras, Regresi dan Klasifikasi Gambar](./modul8.ipynb), 6-7 Mei 2024

# Rekaman praktikum

Untuk pertemuan-pertemuan praktikum Sains Data yang dilaksanakan secara *online* melalui Zoom, semua rekaman disimpan di *link* berikut.

<https://bit.ly/RekamanPrakSaindat2024Genap>
