---
title: "Praktikum Metoe Numerik 2023 Genap (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

Ini adalah versi *website* (yang baru dibuat setelah semester ini berakhir) dari modul dan soal tugas yang ada di *link* berikut: <https://bit.ly/TugasModulMetnum2023Genap> 

# Timeline

* [Modul 1: Review Python, NumPy, Tabulate](./modul1.ipynb), 27 Februari--3 Maret 2023 (*offline* di Lab Departemen Matematika D.311)

* [Modul 2: *Root-finding*](./modul2.ipynb), 6-10 Maret 2023 (*offline* di Lab Departemen Matematika D.311)

* [Tugas 1: *Root-finding*](./tugas1.docx)

    Diberikan: Minggu, 12 Maret 2023, 17.11 WIB

    *Deadline*: Sabtu, 25 Maret 2023, 23.59 WIB

* [Modul 3: Interpolasi](./modul3.ipynb), 20-24 Maret 2023 (*offline* di Lab Departemen Matematika D.311)

* [Tugas 2: Interpolasi](./tugas2.docx)

    Diberikan: Selasa, 28 Maret 2023, 19.42 WIB

    *Deadline*: Selasa, 18 April 2023, 23.59 WIB

* [Modul 4: Diferensiasi Numerik, Ekstrapolasi Richardson](./modul4.ipynb), 27-31 Maret 2023 (asinkronus)

* [Tugas 3: Diferensiasi Numerik, Ekstrapolasi Richardson](./tugas3.docx)

    Diberikan: Selasa, 18 April 2023, 11.45 WIB

    *Deadline*: Minggu, 30 April 2023, 23.59 WIB

* [Modul 5: Integrasi Numerik](./modul5.ipynb), 8-12 Mei 2023 (*offline* di Lab Departemen Matematika D.311)

* [Tugas 4: Integrasi Numerik](./tugas4.docx)

    Diberikan: Minggu, 14 Mei 2023, 18.00 WIB

    *Deadline*: Sabtu, 27 Mei 2023, 23.59 WIB

* [Modul 6: Metode Langsung untuk SPL](./modul6.ipynb), 15-19 Mei 2023 (*offline* di Lab Departemen Matematika D.311)

* [Tugas 5: Metode Numerik untuk SPL](./tugas5.docx)

    Diberikan: Senin, 29 Mei 2023, 07.00 WIB

    *Deadline*: Minggu, 4 Juni 2023, 13.00 WIB

* [Modul 7: Metode Iteratif untuk SPL](./modul7.ipynb), 29 Mei--2 Juni 2023 (*offline* di Lab Departemen Matematika D.311)

