---
title: 'Sesi 2: Praktikum Algoritma Pemrograman'
description: Offline di Departemen Matematika
date: 11/09/2024
page-navigation: true
format: html
engine: jupyter
jupyter: python3
---

Kembali ke [MIPA Open House](./mipa_open_house.qmd)

Kalian bisa men-*download* modul ini dalam format `.ipynb` dengan memencet tombol berikut:

- Sebagian sel belum diisi: [*Download* `sesi2.ipynb.zip`](./sesi2.ipynb.zip)

- Semua kode sudah diisi, seperti di sini: [*Download* `sesi2_kunjaw.ipynb.zip`](./sesi2_kunjaw.ipynb.zip)

```{python}
print("Hello world!")
```

```{python}
print("Selamat pagi")
print("Selamat siang")
print("Selamat sore")
```

Untuk membuat catatan atau *comment*, gunakan `#`

```{python}
# ini comment (catatan)
```

## Operasi Dasar

- Tambah: `+`

- Kurang: `-`

- Kali: `*`

- Bagi: `/`

- Modulo (hasil bagi): `%`

- Pangkat: `**`

```{python}
# tambah
print(1 + 2)
```

```{python}
# kurang
print(2-1)
```

```{python}
# kali
print(1*2)
```

```{python}
# bagi
print(2/1)
```

```{python}
# modulo
print(4 % 3)
print(5 % 3)
print(6 % 3)
```

```{python}
# pangkat
print(4**3)
```

$$\frac{3^2 - 5}{2} + 1 = \text{ ?}$$

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 11, status: ok, timestamp: 1731051902008, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
(3**2 - 5)/2 + 1
```

## Variabel, Input, *String*


```{python}
a = 2
b = 3
a = b
print(a)
print(b)
```

```{python}
nama = input("Masukkan nama: ")
print(nama)
```

```{python}
kalimat = "Nama saya " + nama
print(kalimat)
```

```{python}
print("Nama saya " + nama)
```

```{python}
nama = input("Masukkan nama: ")
print("Nama saya " + nama)
```

Buatlah kode yang menerima input `nama` lalu menghasilkan pesan:

> Selamat siang (nama)

```{python}
print("Selamat siang " + nama)
```

## Tipe Data

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 2020, status: ok, timestamp: 1731054256080, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
nama = input("Masukkan nama: ")
print(nama)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 10, status: ok, timestamp: 1731054257053, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(type(nama))
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 3247, status: ok, timestamp: 1731054261905, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
x_masuk = input("Masukkan angka: ")
print(x_masuk)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 8, status: ok, timestamp: 1731054263256, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(type(x_masuk))
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 9, status: ok, timestamp: 1731054264691, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
x_angka = int(x_masuk)
print(x_angka)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 331, status: ok, timestamp: 1731054267883, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(type(x_angka))
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 4929, status: ok, timestamp: 1731054277854, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
y = int(input("Masukkan angka: "))
print(y)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 6, status: ok, timestamp: 1731054278326, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(type(y))
```

## Pernyataan Bersyarat/Kondisional: `if`, `elif` (else if), `else`

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 1715, status: ok, timestamp: 1731054291197, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
x = int(input("Masukkan angka: "))
if (x % 2 == 0):
  print("Genap")
else:
  print("Ganjil")
```

## Pernyataan Berulang: `for`, `while`

Problem: hitung

$$1 + 2 + 3 + \dots + 100 = \text{ ?}$$

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 355, status: ok, timestamp: 1731053359652, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
hasil = 0
for i in range(1, 100+1):
  hasil = hasil + i
print(hasil)
```

Problem: ...

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 348, status: ok, timestamp: 1731053134749, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
n = 0
hasil = 1
while (hasil < 1000):
  hasil = hasil * 2
  n = n + 1
print(n)
print(hasil)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 387, status: ok, timestamp: 1731053145945, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(2**10)
```

## List

```{python}
buah = ["apel", "jeruk", "pisang"]
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 13, status: ok, timestamp: 1731053559907, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(buah[0])
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 7, status: ok, timestamp: 1731053559907, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(buah[1])
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 6, status: ok, timestamp: 1731053560322, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(buah[2])
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 454, status: ok, timestamp: 1731054477072, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(len(buah))
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 4, status: ok, timestamp: 1731054554406, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
for x in buah:
  print("Saya suka " + x)
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 388, status: ok, timestamp: 1731054604940, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(buah)
```

```{python}
buah[2] = "anggur"
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 7, status: ok, timestamp: 1731054605284, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(buah)
```

## Fungsi

Buatlah fungsi `jumlahkan` yang menerima input `n` lalu menghitung

$$1 + 2 + 3 + \dots + n = \text{ ?}$$

```{python}
def jumlahkan(n):
  hasil = 0
  for i in range(1, n+1):
    hasil = hasil + i
  return hasil
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 354, status: ok, timestamp: 1731053302588, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(jumlahkan(3))
```

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 339, status: ok, timestamp: 1731053373399, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
print(jumlahkan(100))
```

## Fungsi Rekursif

Barisan Fibonacci: 0, 1, 1, 2, 3, 5, 8, ...

$$F_0 = 0, \quad F_1 = 1$$

$$F_n = F_{n-1} + F_{n-2}$$

```{python}
def fib(n):
  if (n == 0):
    return 0
  elif (n == 1):
    return 1
  else:
    return fib(n-1) + fib(n-2)
```

$$F_{10} = \text{ ?}$$

```{python}
#| colab: {base_uri: https://localhost:8080/}
#| executionInfo: {elapsed: 7, status: ok, timestamp: 1731054644499, user: {displayName: Komputasi Kelas B, userId: '06926514210856024628'}, user_tz: -420}
fib(10)
```

Faktorial:

$$0! = 1$$

$$n! = n * (n-1)!$$

Contoh:

\begin{align*}
5! &= 5 * 4! \\
&= 5 * 4 * 3! \\
&= 5 * 4 * 3 * 2! \\
&= 5 * 4 * 3 * 2 * 1! \\
&= 5 * 4 * 3 * 2 * 1 * 0! \\
&= 5 * 4 * 3 * 2 * 1 * 1 \\
&= 120
\end{align*}

```{python}
def fact(n):
  if (n == 0):
    return 1
  else:
    return n * fact(n-1)
```

$$10! = \text{ ?}$$

```{python}
fact(10)
```

