---
title: "Sesi 1: Praktikum Kalkulus"
description: "Offline di Departemen Matematika"
date: 11/09/2024
page-navigation: true
format: html
engine: jupyter
jupyter: 
  kernelspec:
    name: "wolframlanguage13.1"
    language: "wolfram"
    display_name: "Wolfram Language 13.1"
---

Kembali ke [MIPA Open House](./mipa_open_house.qmd)

Selamat datang di Praktikum Kalkulus! Di sini, kalian akan mendapat *preview* tentang apa yang dipelajari dan biasa dilakukan di praktikum untuk Kalkulus 1 (mata kuliah Praktikum Matematika Dasar) dan praktikum untuk Kalkulus 2.

*Fun fact:* perangkat lunak atau *software* yang dibahas di sini juga biasa digunakan untuk praktikum-praktikum Aljabar Linier.

# Setup: Menggunakan Wolfram Cloud

Wolfram Mathematica adalah salah satu *software* CAS *(Computer Algebra System)* yang cukup fleksibel dan bisa digunakan untuk banyak keperluan, seperti kalkulator fungsi, kalkulator *plot* (grafik), analisis data, bahkan hingga *machine learning*.

Namun, sebagai CAS, Wolfram Mathematica umumnya digunakan sebagai penunjang dalam berbagai hal matematika, seperti kalkulus, aljabar linear, persamaan diferensial, dan sebagainya.

Wolfram Mathematica sebenarnya adalah *software* berbayar. Kebetulan, Wolfram menyediakan opsi gratis melalui situs resminya, yaitu Wolfram Cloud, dengan beberapa keterbatasan (Wolfram Cloud Basic).

Kali ini, kita akan menggunakan Wolfram Cloud Basic. Ikuti langkah berikut:

1. Buka <https://www.wolframcloud.com/>

2. Pilih "Sign up for free"

3. Isi *email* dan sebagainya, centang "I agree to...", lalu tekan "Create Wolfram ID"

    ***Note:* tidak harus menggunakan nama asli**

4. Buka kembali link <https://www.wolframcloud.com/>, pastikan sudah signed in

5. Pilih New Notebook

Setelah selesai menggunakan, jangan lupa simpan *file* nya dalam waktu dekat.

Cara *save:* Lihat *taskbar* di atas, pilih File > Download

::: {.callout-warning}

## *File* bisa kedaluwarsa!

Kita sedang menggunakan versi gratis dari Wolfram Cloud, yaitu Wolfram Cloud Basic. Sesuai penjelasan [di situs resminya](https://support.wolfram.com/53990), **tiap file akan *expire* (kedaluwarsa) setelah 60 hari.** Nanti setelah pulang, jangan lupa simpan/unduh *file* nya ke komputer/laptop pribadi, ya!

:::

# Mengenal Wolfram Mathematica

## Operasi Dasar dan Penulisan

Untuk memulai pemrograman di Wolfram Mathematica, Anda harus membuat sel terlebih dahulu. Sel adalah struktur dasar dari *notebook* Wolfram Mathematica. Sebuah sel dapat berisi perintah, teks ilmiah, grafik, ekspresi matematika, elemen interaktif dinamis, dan sebagainya.

Anda dapat membuat sel di Wolfram Mathematica dengan cara menekan tombol kiri pada *mouse* saat kursor menunjukkan simbol I horizontal. Setelah muncul garis horizontal pada *notebook*, silakan ketik hal yang Anda inginkan. Alternatifnya, ketika kursor menunjukkan simbol I horizontal, Anda dapat menekan tombol kanan pada *mouse* lalu pilih fitur **Insert New Cell**, kemudian pilih tipe sel yang Anda inginkan.

Sebuah sel di Wolfram Mathematica dapat dihapus dengan cara menekan tombol *backspace* setelah memilih "kurung sel" yang bersesuaian dengan sel yang ingin dihapus. "Kurung sel" yang dimaksud terletak di pojok kanan *notebook*. Alternatifnya, Anda dapat menekan Ctrl + . hingga Wolfram Mathematica menyorot "kurung sel" yang bersesuaian dengan sel yang ingin dihapus.

Secara default, sel di Wolfram Mathematica memiliki gaya input (Alt + 9). Sel dengan gaya input digunakan untuk menjalankan perintah pemrograman di Wolfram Mathematica. Jika Anda ingin menulis teks biasa di Wolfram Mathematica, gunakan gaya text dengan cara menekan Alt + 7 secara bersamaan. Ketika Anda berpindah sel, sel yang baru tidak mengikuti gaya sel sebelumnya. Sehingga, jika Anda ingin membuat sejumlah sel dengan gaya text, maka Anda harus menekan Alt + 7 untuk setiap sel yang ingin dijadikan teks. Dalam sel yang bergaya text, Anda dapat menulis kode dengan cara menekan Ctrl + ( secara bersamaan hingga muncul sebuah kotak. Kotak tersebut dapat Anda isi sesuai dengan kebutuhan. Misalkan, seperti $e^{\pi * i} + 1 = 0$. Selain itu, dalam sel yang bergaya text, terdapat tiga shortcut lain yang cukup penting, yaitu bold (Ctrl + b), italic (Ctrl + i), dan underline (Ctrl + u).

Selain gaya input dan text, Wolfram Mathematica memiliki banyak gaya penulisan lain melalui fitur Style pada menu Format. Pada fitur Style, terdapat shortcut untuk setiap gaya penulisan yang tersedia. Jadi, jika Anda lupa shortcut untuk gaya tertentu, Anda dapat mengeceknya melalui fitur Style.

Untuk menjalankan perintah di Wolfram Mathematica, Anda dapat menekan **Shift + Enter** secara bersamaan. Sebagai permulaan, Anda dapat menghitung nilai dari 3 + 4 seperti ini.

```{wolfram}
3 + 4
```

Wolfram Mathematica akan memberikan pasangan input dan *output* seperti ilustrasi di atas. Anda dapat membedakan pasangan input dan *output* tertentu berdasarkan labelnya. Untuk mengolah kembali output terakhir yang diberikan oleh Wolfram Mathematica, Anda dapat menggunakan simbol persen "%" seperti contoh di bawah ini.

```{wolfram}
% + 5
```

Anda juga bisa menjalankan sejumlah perintah sekaligus di Wolfram Mathematica. Caranya, pisahkan perintah yang berbeda pada baris berbeda dengan menekan **Enter**. Setelah sudah diketik semua, baru tekan **Shift + Enter** seperti biasa untuk menjalani semua perintah sekaligus.

```{wolfram}
3 + 4
3 + 5
3 + 6
```

Pada contoh di atas, terdapat satu kumpulan input dan tiga buah *output* yang terpisah. Jika Anda hanya ingin melihat *output* dari sebagian perintahnya saja, Anda dapat memberikan simbol titik koma ";" di akhir setiap perintah yang tidak ingin dilihat *output*-nya, seperti contoh di bawah ini. 

```{wolfram}
3 + 4
% + 5;
% + 5
```

Pada contoh di atas, *output* yang ditampilkan hanyalah *output* untuk perintah pada baris pertama dan ketiga.

Wolfram Mathematica dapat mengerjakan kalkulasi dasar dengan akurasi dan presisi tinggi. Beberapa operasi dasar yang dapat dilakukan di Wolfram Mathematica, yaitu:

```{wolfram}
3+4 (*Penjumlahan*)
3-4 (*Pengurangan*)
3*4 (*Perkalian*)
3/4 (*Pembagian*)
3^4 (*Perpangkatan*)
```

Untuk menulis *comment* di Wolfram Mathematica, gunakan simbol kurung lengkung bintang `(*` dan `*)`

*Comment* adalah catatan pada kode, yang gunanya hanya sebagai catatan kita, sehingga tidak akan dibaca oleh Wolfram Mathematica.

Tentunya, perhitungan juga bisa dilakukan dengan desimal, misalnya

```{wolfram}
0.1 + 0.2
```

Tambahan:

- Input pecahan bisa dibuat lebih bagus dengan menekan **Ctrl + /**

- Input berupa pangkat juga bisa dibuat lebih bagus dengan menekan **Ctrl + 6**

- Kalian bisa tekan `Insert > Special Characters` untuk memasukkan simbol-simbol tertentu seperti konstanta $\pi$

## Numerik

Perhitungan di Wolfram bersifat **simbolik**. Oleh karena itu, pecahan seperti $\frac{3}{4}$ akan dibiarkan begitu saja, tidak dihitung, kecuali kalau kita minta. Kita bisa meminta perhitungan **numerik** dengan `N` seperti berikut

```{wolfram}
N[3/4]
```

Kalian bisa melihat penjelasan dengan `N` dengan bertanya, dengan mengetik tanda tanya `?` diikuti namanya yaitu `N`

```{wolfram}
?N
```

Dengan demikian, kita bisa coba misalnya memperoleh bentuk numerik dari $\pi$, hingga digit yang kita inginkan:

```{wolfram}
Pi
```

```{wolfram}
N[Pi]
```

```{wolfram}
N[Pi, 100]
```

Wolfram Mathematica juga menyediakan konstanta $e$ yang bisa ditulis `E`

```{wolfram}
E
```

```{wolfram}
N[E]
```

```{wolfram}
N[E, 100]
```

Keuntungan dari pendekatan simbolik adalah presisi tingkat tinggi. Kita hanya mengubah ke dalam bentuk numerik ketika memang diperlukan. Misalnya, coba hitung

```{wolfram}
7/3 - 1
```

Bandingkan dengan hasil kalkulator.

## Variabel

Dalam Wolfram Mathematica, simbol sama dengan "=" digunakan untuk memberikan nilai ke suatu variabel.

```{wolfram}
a = 3
```

Sekarang, variabel `a` bernilai 3. Kita dapat mengecek kembali nilai dari sebuah variabel dengan cara memanggil namanya

```{wolfram}
a
```

Variabel itu bisa digunakan untuk perhitungan.

```{wolfram}
a + 2
```

Bahkan, kita bisa menyimpan hasil tersebut di variabel lain.

```{wolfram}
b = a + 2
```

```{wolfram}
b
```

Memanfaatkan sifat simbolik dari Wolfram Mathematica, kita bisa membuat variabel baru berdasarkan variabel lain yang bahkan belum ada!

```{wolfram}
y = x^2 + 2 x + 1
```

Ketika Anda menjalankan perintah di atas, akan terdapat perbedaan warna untuk variabel `x` dan `y`. Variabel berwarna hitam di Wolfram Mathematica maknanya sudah memiliki nilai, sedangkan variabel berwarna biru di Wolfram Mathematica maknanya belum memiliki nilai.

Anda dapat mensubstitusikan suatu nilai ke variabel `x` yang juga akan berdampak pada nilai dari variabel `y`

```{wolfram}
x = 2
```

Saat ini, variabel `x` sudah memiliki nilai 2. Sehingga, ketika Anda cek kembali nilai dari `y`,

```{wolfram}
y
```

Variabel `y` kini bernilai 9.

Anda perlu berhati-hati dengan sebuah variabel di Wolfram Mathematica. Jika Anda menggunakan nama variabel yang sama di dua tempat yang berbeda, maka perintah yang Anda jalankan rawan mengalami eror. Untuk menghindari terjadinya eror, Anda disarankan untuk menghapus nilai dari sebuah variabel setiap kali Anda selesai dengan urusan tertentu menggunakan fungsi built-in **Clear**

```{wolfram}
?Clear
```

```{wolfram}
Clear[a, b, x, y]
```

Setelah Anda menjalankan perintah di atas, variabel yang telah digunakan akan kehilangan nilainya ketika warnanya berubah menjadi biru.

## Fungsi

Selain `N` dan `Clear`, Wolfram Mathematica menyediakan fungsi trigonometri seperti `Sin` dan `Cos`

```{wolfram}
?Sin
```

```{wolfram}
Sin[0]
```

```{wolfram}
Sin[Pi/4]
```

```{wolfram}
Cos[Pi/4]
```

Kita juga bisa mendefinisikan fungsi sendiri.

Untuk mendefinisikan sebuah fungsi di Wolfram Mathematica, Anda perlu:

1. Memberikan nama untuk fungsi tersebut. Pastikan bahwa nama fungsi yang Anda gunakan belum pernah digunakan di Wolfram Mathematica. Indikasi nama fungsi yang belum pernah digunakan adalah dari warnanya yang biru. Jika nama fungsi yang Anda berikan berwarna hitam, maka Anda diimbau untuk menggunakan nama lain karena tandanya nama tersebut sudah digunakan oleh Wolfram Mathematica.

2. Menggunakan simbol kurung siku "[ ]" untuk menampung input atau parameter-parameter fungsinya.

3. Memberikan simbol *underscore* "_" di akhir setiap parameter fungsi.

4. Jika terdapat lebih dari satu parameter, maka pisahkan parameter yang berbeda dengan simbol koma ",".

5. Menggunakan simbol titik dua sama dengan ":=" untuk mendefinisikan fungsinya.

Contoh fungsi yang didefinisikan dengan baik di Wolfram Mathematica adalah sebagai berikut.

```{wolfram}
f[x_] = x^2 + 2 x + 1
```

Dengan didefinisikannya fungsi `f[x]` di atas, Anda dapat memanggil kembali fungsi tersebut dengan mengetik seperti ini.

```{wolfram}
f[x_]
```

Selain itu, Anda dapat mengevaluasi fungsi `f[x]` untuk nilai `x` tertentu.

```{wolfram}
f[2]
```

Selain fungsi satu variabel (parameter), Anda juga dapat mendefinisikan sebuah fungsi dengan lebih dari satu variabel (parameter) dengan aturan yang sama.

```{wolfram}
g[x_, y_] := x^2 + y^2 + 1
```

```{wolfram}
g[x,y]
```

```{wolfram}
g[5,8]
```

Fungsi built-in Wolfram Mathematica yang dapat Anda gunakan untuk menggambar grafik fungsi adalah fungsi `Plot`

```{wolfram}
?Plot
```

Berdasarkan deskripsi fungsi `Plot` di atas, terdapat banyak versi syntax yang dapat digunakan untuk menggambar grafik fungsi sesuai dengan kebutuhan Anda.

Bentuk syntax yang paling sederhana adalah `Plot[f[x], {x, a, b}]` dengan

- `f[x]` menyatakan fungsi yang ingin digambar,

- `a` menyatakan batas awal grafik, dan

- `b` menyatakan batas akhir grafik

```{wolfram}
Plot[x^2, {x, -5, 5}]
```

Selain menuliskan formula dari fungsinya secara manual, Anda juga bisa memberikan nama fungsi beserta variabelnya saja. Tentu, hal ini hanya bisa dilakukan jika sebelumnya fungsi tersebut sudah terdefinisi.

```{wolfram}
Plot[f[x], {x, -5, 5}]
```

```{wolfram}
Plot[Sin[x], {x, -5, 5}]
```

Kemudian, fungsi `Plot` juga bisa digunakan untuk menggambar lebih dari satu grafik fungsi di tempat yang sama. Jika terdapat lebih dari satu fungsi yang ingin digambar grafiknya, Anda perlu mengumpulkan fungsi-fungsi tersebut di dalam simbol kurung kurawal "{ }".

```{wolfram}
Plot[{f[x], Sin[x] Cos[x]}, {x, -5, 5}]
```

# Limit

Misalkan kita buat fungsi berikut

$$f(x) = \frac{x^3 - 1}{x - 1}$$

```{wolfram}
f[x_] := (x^3 - 1) / (x - 1)
```

Mari kita lihat dengan `Plot`

```{wolfram}
Plot[f[x], {x, 0, 3}]
```

Kita bisa hitung nilainya di 0, 1, 2...

```{wolfram}
f[0]
```

```{wolfram}
f[1]
```

```{wolfram}
f[2]
```

Ups! Ketika menghitung nilainya di 1, terjadi pembagian nol. Tapi kalau kita lihat grafiknya, harusnya ada nilainya, yaitu 3.

Kita juga bisa menghitung nilai `f[x]` untuk $x$ yang sangat dekat dengan 1. Misalnya, bisa "dari kiri" (dari nilai yang sedikit lebih kecil, terus mendekat)

```{wolfram}
f[0.9]
```

```{wolfram}
f[0.99]
```

```{wolfram}
f[0.99]
```

Bisa juga "dari kanan" (dari nilai yang sedikit lebih besar, terus mendekat)

```{wolfram}
f[1.1]
```

```{wolfram}
f[1.01]
```

```{wolfram}
f[1.001]
```

Nilainya sama-sama mendekati 3, baik dari kiri ataupun dari kanan. Seolah-olah, nilai di $x=1$ harusnya memang 3.

Konsep ini disebut **limit** dan kita bisa tulis

$$\lim_{x \to 1} f(x) = 3$$

yaitu ketika nilai $x$ mendekati 1, nilai $f(x)$ mendekati 3. Limit bisa ada, walaupun hasil fungsinya tidak ada ketika dihitung persis di nilai itu.

Wolfram Mathematica bisa menghitung limit:

```{wolfram}
Limit[f[x], x -> 1]
```

Gunakan tanda panah untuk melambangkan "menuju". Bisa diketik dengan `->`

Contoh lain dari limit, perhaikan fungsi

$$g(x) = \frac{1}{x}$$

```{wolfram}
g[x_] := 1/x
```

Kita bisa gambar

```{wolfram}
Plot[g[x], {x, -5, 5}]
```

Lihat di sekitar $x=0$. Kita bisa mendekati $x=0$ dari kiri menggunakan **limit kiri**, dengan memberi keterangan `Direction -> 1`

```{wolfram}
Limit[g[x], x -> 0, Direction -> 1]
```

Karena mendekati dari bilangan negatif, hasil limit kiri bisa ditulis

$$\lim_{x \to 0^-} g(x) = -\infty$$

Sedangkan, kita bisa mendekati dari kanan, yaitu menghitung **limit kanan**, dengan memberi keterangan `Direction -> -1`

```{wolfram}
Limit[g[x], x -> 0, Direction -> -1]
```

Karena mendekati dari bilangan positif, hasil limit kanan bisa ditulis

$$\lim_{x \to 0^+} g(x) = \infty$$

Suatu fungsi memiliki **limit** (saja) apabila

- memiliki limit kiri,

- memiliki limit kanan, dan

- limit kiri sama dengan limit kanan

Sayangnya, untuk fungsi $g(x)$, limit kiri dan limit kanan untuk $x=0$ tidak sama. Sehingga,

$$\lim_{x \to 0} g(x) \quad \text{tidak ada}$$

```{wolfram}
Limit[g[x], x -> 0]
```

# Turunan

$$f(x) = x^3$$

```{wolfram}
f[x_] := x^3
```

```{wolfram}
f[x_]
```

Turunannya adalah $f'(x) = 3x^2$

```{wolfram}
f'[x_]
```

Sintaks (penulisan) lain: dengan fungsi `D`

```{wolfram}
?D
```

```{wolfram}
D[f[x], x]
```

```{wolfram}
D[f[x], {x, 1}]
```

Kalian juga bisa menghitung $f''(x)$ dengan mengganti angka 1 menjadi 2

```{wolfram}
D[f[x], {x, 2}]
```

Juga bisa $f'''(x)$ dan seterusnya dengan cara yang sama

```{wolfram}
D[f[x], {x, 3}]
```

```{wolfram}
D[f[x], {x, 4}]
```

```{wolfram}
D[f[x], {x, 5}]
```

# Sumasi dan Integral

Untuk menghitung jumlahan seperti $1 + 2 + \dots + 100$, yaitu

$$\sum_{i=1}^{100} i$$

Gunakan fungsi `Sum`

```{wolfram}
?Sum
```

```{wolfram}
Sum[i, {i, 1, 100}]
```

Contoh lain, jumlahan $1^2 + 2^2 + \dots + 100^2$, yaitu

$$\sum_{i=1}^{100} i^2$$

```{wolfram}
Sum[i^2, {i, 1, 100}]
```

Integral adalah luas di bawah kurva. Perhatikan fungsi berikut

$$f(x) = x+1$$

```{wolfram}
f[x_] := x + 1
```

```{wolfram}
Plot[f[x], {x, 0, 2}]
```

Perhitungan integral bisa dilakukan dengan fungsi *integrate*

```{wolfram}
?Integrate
```

Misalkan kita ingin menghitung luas di bawah kurva $f(x)$ dari $x=0$ sampai $x=2$. Artinya, kita ingin menghitung integral

$$\int_{0}^{2} f(x) dx$$

```{wolfram}
Integrate[f[x], {x, 0, 2}]
```
