---
title: "modul"
---

Halo pembaca, Bagaimana kabar kalian? Semoga sehat selalu ya. Sebelumnya aku tebak dulu, kalian pembaca adalah Asisten Laboratorium ya? Kalau iya, semoga modul ini dapat membantu kalian dalam perjalanan asistensi ya. Kalau bukan, semoga kalian berkesempatan menambah pengalaman menjadi asistensi laboratorium ya.

Sebelumnya, Asistensi Laboratorium itu berbeda dengan asisten mata kuliah pengajar dan asisten mata kuliah koreksi tugas. Perbedaan tersebut mencakup dalam pengajaran, tugas, penilaian, dan manajerial barang dan tim. Lebih detailnya ada di arsip Asisten Lab Kak Bisma ya. Pada kesempatan ini penulis akan membantu kalian dalam pengajaran.

# Quarto

Sebenarnya, banyak sekali yang bisa di eksplor dari bahasan quarto. Mungkin jika berkesempatan kedepannya akan disediakan tentang panduan, yakni:

-   Instalasi quarto local

-   quarto for learning, etc.

Namun, pada kesempatan kali ini hanya akan disediakan pegangan (Hands-on) untuk membantu asisten Lab dalam membuat modul.

## Hands-On
