---
title: "Praktikum Struktur Data 2023 Ganjil"
---

Kembali ke [Praktikum](../../praktikum.qmd)

# Modul

## Part 1: Sebelum UTS

Psst... UTS Struktur Data itu "jenis" soalnya sama seperti ujian Alprog: ada beberapa soal pilihan ganda serta satu/dua soal esai berupa menulis *pseudocode*. Kalau kalian lancar di praktikum, mungkin UTS kalian akan lancar jaya~ aamiin.

* [Modul 0: Instalasi dan konfigurasi *software*](Strukdat2023_Modul00.qmd)
* [Modul 1: Pengenalan 1, bahasa pemrograman C](Strukdat2023_Modul01.qmd)
* [Modul 2: Pengenalan 2, bahasa pemrograman C](Strukdat2023_Modul02.qmd)
* [Modul 3: Operasi *array*, algoritma *searching* dan *sorting*](Strukdat2023_Modul03.qmd)
* [Modul 4: Modul 4: *Pointer*, memori, CodeChef, input dan manipulasi *string*](Strukdat2023_Modul04.qmd)
    + [Modul 4a (opsional): ASCII, Unicode, `inttypes.h`, dan manipulasi *text file*](Strukdat2023_Modul04a.qmd)
    * Modul 4b (opsional): membuat *command-line interface* (CLI) dengan `argv`
* Modul 5: *Linked-list* dengan *struct* dan *pointer*
    + Modul 5a (opsional): Visualisasi berbagai jenis *linked-list* dengan graphviz

## Part 2: Setelah UTS

Semangat terus ya! Setelah mempelajari dasar-dasar bahasa pemrograman C, hingga *array* dan *linked list*, kalian akan mempelajari struktur data yang lebih kompleks, yang sebenarnya memanfaatkan konsep *array* maupun *linked list*.

* Modul 6: *Stack* (tumpukan)
    + Modul 6a (opsional): notasi *prefix*, *infix*, dan *postfix*
* Modul 7: *Queue* (antrian)
* Modul 8: *Binary Tree*, *Binary Search Tree* (BST), dan *N-ary Tree*
    + Modul 8a (opsional): DFS (*depth-first search*) dan BFS (*breadth-first search*) untuk *tree*
    + Modul 8b (opsional): Visualisasi sembarang *binary tree* dengan graphviz
    + Modul 8c (opsional): Visualisasi sembarang *N-ary tree* dengan graphviz
* Modul 9: *"Balance Tree"* (AVL), *Max Heap*, *Min Heap*, dan *B-Tree*
    + Modul 9a (opsional): Konversi antara bentuk *array* (BFS) dan bentuk *pointer* untuk sembarang *binary tree*, termasuk *heap*
    + Modul 9b (opsional): Visualisasi *B-Tree* dengan graphviz
* Modul 10: Pengantar *database* (basis data) dengan SQLite

## Part 3 (pengayaan): Python

Meskipun semua materi pada bagian ini bersifat pengayaan dan tidak akan dibahas di sesi praktikum, ada baiknya tetap dibaca untuk sekadar menambah wawasan. (Apabila Anda nekat berniat menggunakan bahasa pemrograman Python untuk proyek akhir Struktur Data, semoga materi pengayaan ini membantu.)

* Modul 11: Struktur data yang khas Python
* Modul 12: Pengantar OOP dengan `class` di Python, pengganti `struct` di C
* Modul 13: I/O dan *text file* di Python
* Modul 14: Visualisasi *tree* (pohon) dengan graphviz di Python