---
title: "Praktikum Metode Numerik 2024 Genap (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

# Timeline

* [Modul 0: *Review* Python, NumPy, Matplotlib](./modul0.ipynb), tidak dibahas di sesi praktikum

* [Modul 1: Tabulate, SymPy, Metode *Root-finding*](./modul1.ipynb), 26-27 Februari 2024 (*offline* di Lab Komputer D.311)

* [Tugas 1: Metode *root-finding*](./tugas1.ipynb)

    Diberikan: Jumat, 8 Maret 2024

    *Deadline*: Sabtu, 23 Maret 2024, 23.59 WIB

* [Modul 2: Interpolasi](./modul2.ipynb), 18 Maret 2024 (*online* melalui Zoom)

* [Modul 3: Diferensiasi Numerik, Ekstrapolasi Richardson](./modul3.ipynb), 22-23 April 2024 (*offline* di Lab Komputer D.311)

* [Latihan (Wajib) Diferensiasi Numerik](./latdifmetnum.ipynb)

    Diberikan: Senin/Selasa, 22/23 April 2024 (ketika praktikum Diferensiasi Numerik & Ekstrapolasi Richardson)

    *Deadline*: Rabu, 24 April 2024, 23.59 WIB

* [Modul 4: Integrasi Numerik](./modul4.ipynb), 29-30 April 2024 (*offline* di Lab Komputer D.311)

* [Latihan (Wajib) Integrasi Numerik](./latintegrasinum.ipynb)

    Diberikan: Senin/Selasa, 29/30 April 2024 (ketika praktikum Integrasi Numerik)

    *Deadline*: Minggu, 5 Mei 2024, 23.59 WIB

* [Modul 5: Metode Langsung untuk SPL](./modul5.ipynb), 6-7 Mei 2024 (*offline* di Lab Komputer D.311)

* [Tugas 2: Interpolasi, Diferensiasi Numerik](./tugas2.ipynb)

    Diberikan: Selasa, 7 Mei 2024

    *Deadline*: Rabu, 22 Mei 2024, 23.59 WIB

# Rekaman praktikum

Untuk pertemuan-pertemuan praktikum Metode Numerik yang dilaksanakan secara *online* melalui Zoom, semua rekaman disimpan di *link* berikut.

<https://bit.ly/RekamanPrakMetnum2024Genap>
