---
title: "Modul 3.1 Sains Data: Regresi (Teori)"
subtitle: "Regresi Linier Sederhana, Regresi Linier Berganda, dan Regresi Logistik"
date: 21/03/2025
page-navigation: true
format: html
---

# Regresi Linier Sederhana
## Pengenalan Regresi Linier Sederhana

## Asumsi Model Regresi Linier Sederhana

## Metode *Least Squares* Untuk Regresi Linier Sederhana

## Uji Signifikansi Parameter

## Berbagai Variasi Model Regresi Linier Sederhana
### Model dengan Transformasi Prediktor Kuantitatif


### Model dengan Prediktor Kualitatif 


## Koefisien Korelasi dan Koefisien Determinasi


# Regresi Linier Berganda
## Bentuk Umum Regresi Linier Berganda

## Asumsi Model Regresi Linier Berganda

## Metode *Least Squares* Untuk Regresi Linier Berganda

## Uji Signifikansi Parameter

## Berbagai Variasi Model dan Interpretasi Parameter Regresi Linier Berganda

### Model Orde Satu dengan Prediktor Kuantitatif

### Model Orde Dua dengan Prediktor Kuantitatif

### Model Orde Satu dengan Interaksi antar Prediktor Kuantitatif

### Model dengan Prediktor Kualitatif


## Koefisien Determinasi

# Regresi Logistik

## Bentuk Umum Model Logistik

## Interpretasi Parameter


Ensemble Learning adalah teknik dalam machine learning yang menggabungkan beberapa model untuk meningkatkan kinerja prediksi dibandingkan dengan model tunggal. Tujuan utama dari pendekatan ini adalah untuk mengurangi varians, bias, dan meningkatkan generalisasi model terhadap data yang belum pernah dilihat sebelumnya. Model yang paling umum digabungkan untuk ensemble learning adalah model Decision Tree. 

Jenis-jenis Ensemble Learning
- Bagging (Bootstrap Aggregating), yaitu membangun beberapa model yang independen satu sama lain menggunakan dataset yang berbeda, yang diperoleh melalui bootstrap sampling (sampling dengan pengembalian). Hasil prediksi dari semua model kemudian digabungkan. Contohnya adalah Random Forest.

- Boosting, yaitu membangun beberapa model yang independen secara sekuensial, di mana setiap model berikutnya berusaha memperbaiki kesalahan model sebelumnya. Contohnya adalah AdaBoost (Adaptive Boosting) dan XGBoost (Extreme Gradient Boosting).

Kita akan coba bandingkan model Decision Tree sebelumnya dengan model-model yang dibangun dengan ensemble learning.