# Tugas 02 (End to End machine learning regresi)

Kembali ke [Sains Data](../sainsdata2023.qmd)

## Petunjuk umum
1. Kerjakan secara individu

2. Kerjakan tugas ini dengan bahasa pemrograman python. Anda disarankan
menggunakan jupyter untuk mengerjakan tugas ini.

3. Untuk setiap proses sains data (pembersihan data, transformasi data, EDA, dan pemodela ) yang dilakukan Anda diperlukan untuk menuliskan justifikasi-nya. Justifikasi-nya dapat berupa penjelasan singkat mengenai proses yang dilakukan, dan penjelasan mengenai alasan mengapa anda melakukan proses tersebut.

4. File yang harus diunggah terdiri dari:
    * beberapa model dalam format .pkl. Penamaan untuk model dibebaskan, namun harus jelas mengenai model apa yang disimpan.
    * satu file python notebook (file berbentuk .ipynb BUKAN .py) dengan ketentuan serupa.

5. Semua file disatukan dalam 1 (satu) file .zip, dengan format penamaan: Nama_NPM_Kelas SIAK Sains Data_Tugas2PrakSainsData.zip.
contoh: Itadori-Yuji_190688675_A_Tugas2PrakSainsData.zip


6. Batas pengumpulan tugas ini adalah 21  April 2023 pukul 23.59. Tugas dikumpulkan sesuai dengan link berikut: [https://ristek.link/tugas-sains-data-02](https://ristek.link/tugas-sains-data-02)


7. Dilarang melakukan **plagiarisme** atau menduplikasi dalam mengerjakan tugas ini.
Apabila terdapat kesamaan program atau penjelasan pada tugas yang dikumpulkan,
**NILAI TUGAS PRAKTIKUM SAINS DATA ANDA LANGSUNG MENJADI 0** TANPA
PERINGATAN bagi semua pihak yang terlibat plagiarisme dalam tugas ini.

8. Gunakan module (python package) yang telah dipelajari di praktikum atau kelas. Anda diperbolehkan untuk menggunakan module (python package) lain dengan catatan bahwa Anda harus menuliskan penjelasan singkat mengenai module tersebut.

9. Apabila ada yang ingin ditanyakan anda dapat bertanya pada kolom komentar atau, silakan mengontak salah satu kontak berikut:
    * LINE: Carles_Octavianus (carles)


## Soal

\[akses-data\]: [https://drive.google.com/open?id=1whKzd5rd-Rtg8bGmEYeBonsXLQMKfxTB&authuser=carlesoctavianus%40gmail.com&usp=drive_fs](https://drive.google.com/open?id=1whKzd5rd-Rtg8bGmEYeBonsXLQMKfxTB&authuser=carlesoctavianus%40gmail.com&usp=drive_fs)

Kerjakan secara end-to-end (pembersihan data, transformasi data , EDA, dan pemodelan)  untuk memprediksi harga rumah berdasarkan data yang diberikan. Gunakan metode yang telah dipelajari di praktikum ataupun kelas (model regresi).


