---
title: "Modul 0 Struktur Data: Instalasi dan konfigurasi *software*"
---

Kembali ke [Struktur Data](strukdat2023.qmd)

Untuk praktikum Struktur Data, kita akan menggunakan bahasa pemrograman C, sehingga perlu diinstal beberapa *software*, terutama gcc dan aplikasi Visual Studio Code. Apabila Anda tidak bersedia menginstal *software* tersebut di laptop, Anda tetap dapat menggunakan [Sololearn Compiler Playground](https://www.sololearn.com/compiler-playground) atau situs serupa. Kebetulan, aplikasi Sololearn juga tersedia untuk *smartphone* ([Android](https://play.google.com/store/apps/details?id=com.sololearn), [iOS](https://apps.apple.com/us/app/sololearn-learn-to-code-apps/id1210079064)).

Selain itu, di praktikum terakhir, kita juga akan mulai membahas *database* dan SQL menggunakan SQLite, termasuk aplikasi DB Viewer (*database viewer*) untuk SQLite, sehingga keduanya perlu diinstal juga.

Ada juga graphviz (opsional) apabila Anda berniat ingin membuat visualisasi untuk berbagai struktur data, terutama berbagai jenis *tree*.

# Outline

* *Software* utama
  + Instalasi gcc
  + Instalasi dan konfigurasi Visual Studio Code
  + Instalasi SQLite
  + Instalasi DB Browser for SQLite (DB4S)
    - Windows: dari *installer*
    - macOS: dari *file* DMG

* Opsional
  + Instalasi graphviz
    - Windows: dari *installer*
    - macOS: dari *source code*
  + Konfigurasi Visual Studio Code untuk graphviz

* Alternatif *online*
  + Sololearn Compiler Playground
  + Graphviz Online

# *Software* utama

## Instalasi gcc

blabla

## Instalasi dan konfigurasi Visual Studio Code

blabla

## Instalasi SQLite

<https://www.sqlite.org/download.html>

blabla

## Instalasi DB Browser for SQLite (DB4S)

### Windows: dari *installer*

*Storage* yang dibutuhkan: perkiraan 50-70 MB

1. Buka situs <https://sqlitebrowser.org/dl/>, *scroll* ke bagian "Windows", lalu pencet tulisan "DB Browser for SQLite - Standard installer for 64-bit Windows" untuk men-*download*/mengunduh *installer* untuk DB Browser for SQLite.
2. Setelah proses *download* selesai, buka *installer* nya. Ikuti saja. Secara keseluruhan, Anda tinggal menekan Next berkali-kali sampai proses instalasi selesai. Apabila ada persetujuan seperti EULA (End-User License Agreement), setujui saja (centang). Namun, akan ada bagian Shortcuts, di mana Anda bisa mencentang semua pilihan untuk DB Browser (SQLite). Abaikan "SQLCipher" (tidak perlu dicentang).
3. Setelah menekan Next beberapa kali, akan ada semacam proses *loading*, yang artinya proses instalasi sedang berjalan. Tunggu saja selama perkiraan 1 (satu) menit.
4. Nantinya, apabila proses instalasi sudah selesai, tombol Next akan berubah menjadi Finish, maka tekan Finish. Anda boleh menghapus *installer* nya.

### macOS: dari *file* DMG

*Storage* yang dibutuhkan: perkiraan 50-70 MB

1. Tentukan apakah laptop Anda memiliki prosesor Intel atau Apple Silicon. Di ujung kiri atas layar laptop Anda, tekan tombol Apple (), lalu "About This Mac". Setelah itu, akan muncul beberapa informasi tentang MacBook Anda, termasuk keterangan prosesor atau chip, apakah Apple M1/M2 (Apple Silicon) atau Intel.
2. Buka situs <https://sqlitebrowser.org/dl/>, *scroll* ke bagian "macOS", lalu pencet tulisan "DB Browser for SQLite" yang sesuai dengan prosesor laptop Anda (antara Intel atau Apple Silicon) untuk men-*download*/mengunduh *installer* DB Browser for SQLite, yang berupa *file* DMG.
3. Setelah proses *download* selesai, buka *file* DMG tersebut. Apabila muncul peringatan bahwa aplikasi tidak dikenal, tidak masalah, pencet Open saja.
4. Akan muncul gambar/*icon* aplikasinya, dengan tulisan "DB Browser for SQLite", serta folder Applications di sampingnya (dan ada panah di antaranya). Tarik gambar aplikasinya ke folder Applications tersebut, sesuai panah. Sebenarnya, ini adalah proses *copy-paste* agar aplikasinya menjadi tersedia di laptop Anda. Tunggu saja selama perkiraan 1 (satu) menit.
5. Proses instalasi sudah selesai dan aplikasi DB Browser untuk SQLite sudah bisa dibuka melalui folder Applications. Apabila, di Desktop, muncul semacam *file* Disk Image dengan tulisan DB Browser atau semacamnya, klik kanan lalu Eject saja. Anda boleh menghapus *file* DMG nya.

# Opsional

## Instalasi graphviz

### Windows: dari *installer*

<https://graphviz.gitlab.io/download/>

blabla

### macOS: dari *source code*

*Storage* yang dibutuhkan: perkiraan 200-500 MB

1. Buka situs <https://graphviz.gitlab.io/download/source/>, *scroll* ke bagian "Stable Releases", lalu unduh/*download* versi yang terbaru (teratas), dengan menekan tulisan biru yang berakhiran "gz" (bukan yang sha256).
2. Setelah proses *download* selesai, akan muncul *file* yang berakhiran `.tar.gz`. Itulah *file* yang telah diunduh. Klik *file* tersebut dua kali, seolah-olah ingin membuka suatu aplikasi. (Proses ini bernama *extraction/unzipping*. Daripada klik dua kali, Anda juga bisa klik kanan lalu "Extract".) Kemudian, akan muncul folder baru dengan nama yang sama, tetapi tanpa akhiran `.tar.gz`, kira-kira bernama "graphviz-(versi)", yang selanjutnya akan kita sebut "folder graphviz".
3. Klik kanan pada folder graphviz tersebut, lalu pencet "New Terminal at Folder". Akan muncul Terimnal, yaitu semacam cmd atau command prompt untuk macOS.
4. Ketik `./configure`, lalu tekan enter. Akan muncul banyak tulisan yang terus membanjiri Terminal. Tunggu saja selama perkiraan 3 (tiga) menit, sampai banjir berhenti. (Tentu saja, sambil menunggu, Anda boleh sambil melakukan hal lain, menggunakan aplikasi lain dan sebagainya, selama tidak menutup Terminal.)
5. Lalu, ketik `make`, tekan enter. Akan muncul banyak tulisan yang terus membanjiri Terminal lagi, tetapi kali ini lebih lama. Tunggu saja selama perkiraan 10 (sepuluh) menit, sampai banjir berhenti.
6. Terakhir, ketik `make install`, dan tekan enter. Akan muncul banyak tulisan yang membanjiri Terminal lagi, tetapi tidak lama. Tunggu saja selama perkiraan 1 (satu) menit.
7. Setelah banjir berhenti, proses instalasi sudah selesai dan Anda boleh menutup Terminal.

Setelah instalasi selesai, Anda bisa membuka aplikasi Terminal (ada di folder Applications, lalu masuk folder Utilities) kapan saja, di mana saja, lalu menggunakan command `dot` untuk menggunakan graphviz. Contohnya, Anda bisa mengetik `dot -V` untuk memeriksa versi graphviz yang telah terinstal, atau mengetik `dot -?` untuk melihat daftar command yang ada.

## Konfigurasi Visual Studio Code untuk graphviz

blabla

# Alternatif *online*

## Sololearn Compiler Playground

<https://www.sololearn.com/compiler-playground/>

## Graphviz Online

<https://dreampuf.github.io/GraphvizOnline/>