# Tugas Praktikum 1 PD NUMERIK

Kembali ke [Persamaan Diferensial Numerik](../pdnum2023.qmd)

## Petunjuk Pengumpulan Tugas

1. Tugas ini dikerjakan secara individu.

2. Terdapat satu (1) soal yang harus dijawab.

3. File yang harus diunggah terdiri dari:

a. beberapa function file sesuai kebutuhan. Penamaan untuk function file dibebaskan, selama masih relevan dengan isi fungsinya (dilarang menamakan function file "adamsorde5.m" jika isinya adalah metode Runge-Kutta).

b. satu (1) script file untuk jawaban. Penamaannya adalah "soal.m" untuk soal yang diberikan.

c. satu (1) file PDF untuk penjelasan keseluruhan soal. Penjelasan diketik dalam Word atau sejenisnya dengan format penamaan "Penjelasan.pdf".

4. Semua file disatukan dalam satu file .zip dengan format penamaan:

[Nama]_[NPM]_[Kelas SIAK]_Tugas 1_Prak PDNum.zip

Contoh: "Cristiano Ronaldo_2101234567_C_Tugas 1_Prak PDNum.zip"

5. Batas pengumpulan tugas ini adalah Selasa, 21 Maret 2023, pukul 23.59 WIB.

Tugas dikumpulkan melalui gform sesuai dengan kelas masing-masing:

Link: [https://bit.ly/Tugas1PrakPDNum](https://bit.ly/Tugas1PrakPDNum)

*mohon perhatikan waktu pengumpulan yang tertera dan kumpulkan tugas secara tepat waktu.

6. Dilarang melakukan plagiarisme. Jika terdapat mahasisya yang terindikasi melakukan plagiarisme, maka mahasiswa tersebut memperoleh nilai 0 untuk tugas ini.

7. Apabila ada pertanyaan, harap huibungi CP:

Tulus Setiawan (WA/LINE: tlsnew/081213679316) Diberikan suatu initial value problem


## SOAL

$$
\begin{aligned}
& y^{\prime}=\frac{y^{2}}{1+t}, \quad 1 \leq t \leq 2 \\
& y(1)=-(\ln 2)^{-1}
\end{aligned}
$$

Diketahui solusi eksak dari IVP tersebut adalah:

$$
y(t)=-\frac{1}{\ln (t+1)}
$$

a. Gunakan tiga metode one-step pilihan Anda untuk mengaproksimasi dan membandingkan solusi dari IVP tersebut menggunakan stepsize $h=0.05$.

b. Buatlah grafik perbandingan dari metode tersebut. 



