---
title: "Praktikum Sains Data 2023 Genap (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

Modul ini adalah salinan dari: [https://github.com/carlesoctav/sains-data-2023](https://github.com/carlesoctav/sains-data-2023)

# Timeline

- [modul-tahun-lalu](./main-module/module-tahun-lalu.qmd)

- [praktikum-1](./main-module/week-01.ipynb): 1 Maret 2023, presensi [ristek.link/presensi-sains-data-01](https://ristek.link/presensi-sains-data-01)
- [praktikum-2](./main-module/week-02.ipynb): 8 Maret 2023, presensi [ristek.link/presensi-sains-data-02](https://ristek.link/presensi-sains-data-02)
- [praktikum-3](./main-module/week-03.ipynb): 15 Maret 2023, presensi [ristek.link/presensi-sains-data-03](https://ristek.link/presensi-sains-data-03)

- Tugas-1: 22 Maret 2023, tempat pengumpulan: [bit.ly/Tugas1PrakSainsData](https://bit.ly/Tugas1PrakSainsData)

- [Tugas-2](./tugas/tugas-2.qmd): 21 April 2023, tempat pengumpulan: [https://ristek.link/tugas-sains-data-02](https://ristek.link/tugas-sains-data-02)

- [Tugas-3](./tugas/tugas-3.qmd): 21 April 2023, tempat pengumpulan: [https://ristek.link/tugas-sains-data-03](https://ristek.link/tugas-sains-data-03)

- [praktikum-4](./main-module/week-04.ipynb): 26 April 2023, presensi [ristek.link/presensi-sains-data-04](https://ristek.link/presensi-sains-data-04)

- [praktikum-5](./main-module/week-05.ipynb): 3 Mei 2023, presensi [ristek.link/presensi-sains-data-05](https://ristek.link/presensi-sains-data-05)

- [praktikum-6](./main-module/week-06.ipynb): 10 Mei 2023, presensi [ristek.link/presensi-sains-data-06](https://ristek.link/presensi-sains-data-06)

- [tugas-akhir](./tugas/tugas-akhir.qmd)