<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-11-18">
<meta name="description" content="Offline di Departemen Matematika">

<title>(Pertemuan 08) Pengujian Hipotesis Menggunakan R – Lab Praktikum Departemen Matematika FMIPA UI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Lab Praktikum Departemen Matematika FMIPA UI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/praktikum.html"> 
<span class="menu-text">Praktikum</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/Announcement.html"> 
<span class="menu-text">Announcement</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/Jadwal.html"> 
<span class="menu-text">Informasi Praktikum Departemen Matematika</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pengantar-statistika-inferensia" id="toc-pengantar-statistika-inferensia" class="nav-link active" data-scroll-target="#pengantar-statistika-inferensia">Pengantar Statistika Inferensia</a></li>
  <li><a href="#taksiran-titik" id="toc-taksiran-titik" class="nav-link" data-scroll-target="#taksiran-titik">Taksiran Titik</a></li>
  <li><a href="#taksiran-interval" id="toc-taksiran-interval" class="nav-link" data-scroll-target="#taksiran-interval">Taksiran Interval</a></li>
  <li><a href="#pengujian-hipotesis" id="toc-pengujian-hipotesis" class="nav-link" data-scroll-target="#pengujian-hipotesis">Pengujian Hipotesis</a></li>
  <li><a href="#pengayaan-perhitungan-probabilitas-terjadinya-galat-menggunakan-r" id="toc-pengayaan-perhitungan-probabilitas-terjadinya-galat-menggunakan-r" class="nav-link" data-scroll-target="#pengayaan-perhitungan-probabilitas-terjadinya-galat-menggunakan-r">(Pengayaan) Perhitungan Probabilitas Terjadinya Galat Menggunakan R</a></li>
  <li><a href="#pengayaan-pengujian-hipotesis-untuk-sampel-berpasangan" id="toc-pengayaan-pengujian-hipotesis-untuk-sampel-berpasangan" class="nav-link" data-scroll-target="#pengayaan-pengujian-hipotesis-untuk-sampel-berpasangan">(Pengayaan) Pengujian Hipotesis untuk Sampel Berpasangan</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">(Pertemuan 08) Pengujian Hipotesis Menggunakan R</h1>
<p class="subtitle lead">Hypothesis Testing in R</p>
</div>

<div>
  <div class="description">
    Offline di Departemen Matematika
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 18, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Kembali ke <a href="../../../../../semuahalaman/modulprak/2024/ganjil/psd/psd2024.html">Pengantar Sains Data</a></p>
<section id="pengantar-statistika-inferensia" class="level2">
<h2 class="anchored" data-anchor-id="pengantar-statistika-inferensia">Pengantar Statistika Inferensia</h2>
<p>Dalam statistika, terdapat dua cabang utama yang sering menjadi dasar dalam penerapan dan pengembangan ilmu ini, yaitu statistika deskriptif dan statistika inferensia. Pada pertemuan-pertemuan sebelumnya, kita sudah membahas banyak hal mulai dari menghitung statistik-statistik dasar seperti mean dan variansi, visualisasi data, dan distribusi-distribusi diskrit dan kontinu. Semua hal itu termasuk ke dalam cabang statistika yang dinamakan statistika deskriptif.</p>
<p>Berbeda dengan statistika deskriptif, statistika inferensia digunakan untuk membuat prediksi mengenai populasi berdasarkan data sampel. Dalam melakukan prediksi ini, digunakanlah metode-metode seperti pengujian hipotesis, taksiran titik, dan taksiran interval, yang semuanya didasari oleh teori probabilitas dan teori distribusi statistika.</p>
<p>Pada pertemuan hari ini, kita akan membahas bagaimana cara melakukan taksiran titik, taksiran interval, dan pengujian hipotesis pada data sampel menggunakan R. Dengan menggunakan software seperti R, kita bisa mempersingkat waktu yang diperlukan untuk melakukan inferensia.</p>
</section>
<section id="taksiran-titik" class="level2">
<h2 class="anchored" data-anchor-id="taksiran-titik">Taksiran Titik</h2>
<p>Dalam ilmu statistika, seringkali kita ingin mengetahui mean atau variansi dari populasi. Misalnya, ingin mengetahui rata-rata pendapatan per tahun semua orang dewasa di Indonesia, atau ingin mengetahui persebaran tinggi badan semua siswa SMA di Indonesia. Tentu saja, tidak mungkin jika kita menanyakan pendapatan tahunan ke semua orang dewasa di Indonesia, bukan? Oleh karena itu, sulit untuk mengetahui secara pasti rata-rata pendapatan tahunan orang dewasa di Indonesia. Hal yang sama juga terjadi dalam kasus persebaran tinggi badan siswa SMA.</p>
<p>Meskipun demikian, menggunakan distribusi sampling yang sudah kita bahas pada pertemuan sebelumnya, kita tahu bahwa sampling dari suatu populasi akan berdistribusi normal untuk ukuran sampel yang cukup besar, apapun distribusi populasinya. Teori ini (disebut Teorema Limit Pusat) menjadi sangat bermanfaat dalam melakukan prediksi pada populasi, karena kita hanya perlu mengambil beberapa sampel dari populasi dan bisa melakukan prediksi pada populasi. Sebagai contoh, untuk kasus pendapatan tahunan sebelumnya, itu berarti kita cukup mengambil sampel yang cukup besar (misalnya <span class="math inline">\(50\)</span> atau <span class="math inline">\(100\)</span> orang) yang acak dan tak bias, dan menggunakan data ini saja kita sudah bisa melakukan prediksi mengenai rata-rata pendapatan tahunan semua orang dewasa di Indonesia.</p>
<p>Untuk melakukan taksiran titik di R, pertama kita akan membutuhkan datanya terlebih dahulu. Misalkan kita ingin menaksir mean dan variansi untuk kolom <code>mpg</code> (miles per gallon) pada data <code>mtcars</code>. Pertama, kita masukkan data <code>mtcars</code> terlebih dahulu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<p>Untuk menghitung taksiran mean dan variansi pada data <code>mpg</code>, kita gunakan fungsi <code>mean</code> dan fungsi <code>var</code> sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mpg_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>mpg)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>mpg_var <span class="ot">&lt;-</span> <span class="fu">var</span>(mtcars<span class="sc">$</span>mpg)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mpg_mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.09062</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mpg_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36.3241</code></pre>
</div>
</div>
<p>Dengan demikian, kita bisa menyimpulkan bahwa taksiran mean untuk miles per gallon mobil adalah <span class="math inline">\(20.09062\)</span> dan taksiran variansi untuk miles per gallon mobil adalah <span class="math inline">\(36.3241\)</span>.</p>
<p>Selain melakukan prediksi pada mean dan variansi, kita juga bisa melakukan prediksi pada proporsi. Prediksi untuk proporsi ini sangat bermanfaat jika kita sudah mengetahui terlebih dahulu bahwa distribusi yang kita miliki berdistribusi binomial. Contohnya, pada kolom <code>am</code> (<code>0</code> = mobil matic, <code>1</code> = mobil manual) kita bisa menaksir proporsi mobil matic dan proporsi mobil manual di antara semua mobil.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>matic_prop <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>)<span class="sc">/</span><span class="fu">nrow</span>(mtcars)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>manual_prop <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>)<span class="sc">/</span><span class="fu">nrow</span>(mtcars)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(matic_prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.59375</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(manual_prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.40625</code></pre>
</div>
</div>
<p>Jadi, taksiran proporsi mobil matic adalah <span class="math inline">\(0.59375\)</span> dan taksiran proporsi mobil manual adalah <span class="math inline">\(0.40625\)</span>.</p>
</section>
<section id="taksiran-interval" class="level2">
<h2 class="anchored" data-anchor-id="taksiran-interval">Taksiran Interval</h2>
<p>Meskipun kita bisa menaksir mean, variansi, atau proporsi untuk suatu populasi, kita masih tidak bisa <span class="math inline">\(100\%\)</span> yakin bahwa memang mean, variansi, atau proporsinya benar-benar persis sama dengan taksiran kita. Bahkan, kemungkinan besar, taksiran titik kita akan berbeda dengan nilai sebenarnya. Untuk itu, kita memerlukan suatu pendekatan yang memberikan rentang nilai di mana parameter populasi kemungkinan besar berada. Pendekatan ini disebut taksiran interval atau lebih dikenal dengan <strong>confidence intervals (CI)</strong>. Taksiran interval memberikan estimasi dalam bentuk suatu interval, yang dikaitkan dengan tingkat kepercayaan tertentu, misalnya <span class="math inline">\(95\%\)</span> atau <span class="math inline">\(99\%\)</span>.</p>
<p>Dengan menggunakan taksiran interval, kita bisa memprediksi dengan suatu tingkat kepercayaan tertentu (seperti <span class="math inline">\(95\%\)</span> atau <span class="math inline">\(99\%\)</span>) bahwa mean dari populasi yang kita inginkan berada di antara suatu interval (sebenarnya, interpretasi seperti ini kurang tepat, tetapi untuk intuisi dasar mengenai interval kepercayaan, untuk sementara akan kita gunakan). Bahkan, menggunakan taksiran interval, kita juga bisa melakukan prediksi mengenai beda mean atau beda proporsi untuk dua populasi.</p>
<p>Untuk menentukan interval kepercayaan untuk mean jika variansi populasi diketahui, kita gunakan rumus berikut.</p>
<p><span class="math display">\[
\text{CI} = \bar{x} \pm z_{1-\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>Menggunakan R, kita bisa menggunakan rumus tersebut untuk menentukan interval kepercayaan. Misalnya menggunakan contoh <code>mtcars</code> tadi, kita bisa membuat interval kepercayaan <span class="math inline">\(95\%\)</span> (<span class="math inline">\(\alpha = 0.05\)</span>) untuk mean dari miles per gallon mobil. Misalkan pula kita mengetahui bahwa variansi mpg pada populasi adalah <span class="math inline">\(36\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mpg_mean_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>mpg)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>mpg_var_1 <span class="ot">&lt;-</span> <span class="dv">36</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mpg_sd_1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(mpg_var)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>mpg_count_1 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(mtcars)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>lower_bound_1 <span class="ot">&lt;-</span> mpg_mean_1 <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> mpg_sd_1 <span class="sc">/</span> <span class="fu">sqrt</span>(mpg_count_1)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>upper_bound_1 <span class="ot">&lt;-</span> mpg_mean_1 <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> mpg_sd_1 <span class="sc">/</span> <span class="fu">sqrt</span>(mpg_count_1)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk mean mpg adalah (%.4f, %.4f)."</span>, lower_bound_1, upper_bound_1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk mean mpg adalah (18.0024, 22.1788).</code></pre>
</div>
</div>
<p>Namun, pada kasus ini, sebenarnya kita tidak mengetahui variansi mpg pada populasi. Oleh karena itu, kita akan menggunakan rumus berikut untuk menentukan interval kepercayaan untuk mean jika variansi populasi tidak diketahui.</p>
<p><span class="math display">\[
\text{CI} = \bar{x} \pm t_{1-\alpha/2;n-1} \cdot \frac{s}{\sqrt{n}}
\]</span></p>
<p>Menggunakan R, interval kepercayaan <span class="math inline">\(95\%\)</span> nya didapat sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mpg_mean_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>mpg)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mpg_var_2 <span class="ot">&lt;-</span> <span class="fu">var</span>(mtcars<span class="sc">$</span>mpg)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>mpg_sd_2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(mpg_var)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>mpg_count_2 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(mtcars)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>lower_bound_2 <span class="ot">&lt;-</span> mpg_mean_2 <span class="sc">-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> mpg_count_2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> mpg_sd_2 <span class="sc">/</span> <span class="fu">sqrt</span>(mpg_count_2)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>upper_bound_2 <span class="ot">&lt;-</span> mpg_mean_2 <span class="sc">+</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> mpg_count_2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> mpg_sd_2 <span class="sc">/</span> <span class="fu">sqrt</span>(mpg_count_2)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk mean mpg adalah (%.4f, %.4f)."</span>, lower_bound_2, upper_bound_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk mean mpg adalah (17.9177, 22.2636).</code></pre>
</div>
</div>
<p>Perhatikan bahwa panjang dari interval kepercayaan saat variansi tidak diketahui lebih panjang dibandingkan dengan saat variansinya diketahui. Hal ini karena kita menghilangkan informasi mengenai variansi pada kasus variansi tidak diketahui. Karena informasinya berkurang, maka ketidakpastian untuk mean juga tentu semakin bertambah. Hal ini mengakibatkan meningkatnya panjang dari interval kepercayaan, padahal tingkat kepercayaannya sama, yaitu <span class="math inline">\(95\%\)</span>.</p>
<p>Selain untuk mean 1 populasi, kita juga bisa membuat interval kepercayaan untuk perbedaan mean untuk 2 populasi independen. Misalnya, kita ingin menghitung beda mean antara Sepal Length pada iris spesies setosa dengan iris spesies versicolor. Untuk itu, kita bisa menggunakan dataset bawaan R yaitu <code>iris</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
<p>Ada beberapa kasus dalam menentukan interval kepercayaan untuk perbedaan mean antara 2 populasi independen. Pertama, untuk kasus variansi kedua populasi diketahui, rumusnya yaitu sebagai berikut.</p>
<p><span class="math display">\[
\text{CI} = (\bar{x}_1 - \bar{x}_2) \pm z_{1-\alpha/2} \cdot \sqrt {\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}
\]</span></p>
<p>Sebagai contoh, misalkan telah diketahui sebelumnya bahwa variansi dari Sepal Length pada spesies setosa adalah <span class="math inline">\(0.15\)</span> dan pada spesies versicolor adalah <span class="math inline">\(0.25\)</span>. Maka interval kepercayaan <span class="math inline">\(95\%\)</span> untuk perbedaan mean antara Sepal Length setosa dengan versicolor dapat dihitung menggunakan R sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mean_s_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mean_v_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>])</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>var_s_1 <span class="ot">&lt;-</span> <span class="fl">0.15</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>var_v_1 <span class="ot">&lt;-</span> <span class="fl">0.25</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>count_s_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>count_v_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>lower_bound_3 <span class="ot">&lt;-</span> (mean_v_1 <span class="sc">-</span> mean_s_1) <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(var_v_1<span class="sc">/</span>count_v_1 <span class="sc">+</span> var_s_1<span class="sc">/</span>count_s_1)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>upper_bound_3 <span class="ot">&lt;-</span> (mean_v_1 <span class="sc">-</span> mean_s_1) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(var_v_1<span class="sc">/</span>count_v_1 <span class="sc">+</span> var_s_1<span class="sc">/</span>count_s_1)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk beda mean Sepal Length setosa dengan versicolor adalah (%.4f, %.4f)."</span>, lower_bound_3, upper_bound_3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk beda mean Sepal Length setosa dengan versicolor adalah (0.7547, 1.1053).</code></pre>
</div>
</div>
<p>Untuk kasus variansi kedua populasi tidak diketahui, tetapi diketahui sama, pertama hitung variansi poolednya, yaitu</p>
<p><span class="math display">\[
s_{p}^2 = \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}
\]</span></p>
<p>Kemudian barulah menghitung interval kepercayaannya, yaitu</p>
<p><span class="math display">\[
\text{CI} = (\bar{x}_1 - \bar{x}_2) \pm t_{1-\alpha/2;n_1 + n_2 - 2} \cdot s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}
\]</span></p>
<p>Sebagai contoh, misalkan kali ini kita belum mengetahui variansi dari Sepal Length pada spesies setosa dan spesies versicolor, tetapi kita tahu bahwa variansi keduanya sama. Maka interval kepercayaan 95% untuk perbedaan mean antara Sepal Length setosa dengan versicolor dapat dihitung menggunakan R sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mean_s_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>])</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mean_v_2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>])</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>var_s_2 <span class="ot">&lt;-</span> <span class="fu">var</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>])</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>var_v_2 <span class="ot">&lt;-</span> <span class="fu">var</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>])</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>count_s_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>count_v_2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>var_pooled <span class="ot">&lt;-</span> ((count_s_2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> var_s_2 <span class="sc">+</span> (count_v_2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> var_v_2) <span class="sc">/</span> (count_s_2 <span class="sc">+</span> count_v_2 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>sd_pooled <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_pooled)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>lower_bound_4 <span class="ot">&lt;-</span> (mean_v_2 <span class="sc">-</span> mean_s_2) <span class="sc">-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> count_v_2 <span class="sc">+</span> count_s_2 <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> sd_pooled <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>count_v_2 <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>count_s_2)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>upper_bound_4 <span class="ot">&lt;-</span> (mean_v_2 <span class="sc">-</span> mean_s_2) <span class="sc">+</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> count_v_2 <span class="sc">+</span> count_s_2 <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> sd_pooled <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>count_v_2 <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>count_s_2)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk beda mean Sepal Length setosa dengan versicolor adalah (%.4f, %.4f)."</span>, lower_bound_4, upper_bound_4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk beda mean Sepal Length setosa dengan versicolor adalah (0.7546, 1.1054).</code></pre>
</div>
</div>
<p>Untuk kasus terakhir yaitu saat variansi kedua populasi tidak diketahui dan belum tentu sama, maka pertama hitung derajat bebas yang perlu digunakan terlebih dahulu.</p>
<p><span class="math display">\[
v = \frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\frac{(s_1^2/n_1)^2}{n_1-1} + \frac{(s_2^2/n_2)^2}{n_2-2}}
\]</span></p>
<p>Biasanya, derajat bebas yang didapat menggunakan rumus ini hampir selalu bukan bilangan bulat. Keuntungan dari menggunakan R adalah bahwa R bisa menangani kasus saat derajat bebas ini berupa desimal dan bukan bilangan bulat. Berbeda dengan saat menghitung manual, dimana derajat bebas ini harus dibulatkan ke bawah.</p>
<p>Setelah derajat bebas ini diperoleh, barulah kita hitung interval kepercayaannya, yaitu</p>
<p><span class="math display">\[
\text{CI} = (\bar{x}_1 - \bar{x}_2) \pm t_{1-\alpha/2;v} \cdot \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}
\]</span></p>
<p>Sebagai contoh, misalkan kali ini kita tidak mengetahui variansi dari Sepal Length spesies setosa maupun spesies versicolor, dan kita juga tidak mengetahui apakah kedua spesies ini memiliki variansi yang sama. Maka, interval kepercayaan <span class="math inline">\(95\%\)</span> untuk perbedaan mean antara Sepal Length setosa dengan versicolor dapat dihitung menggunakan R sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mean_s_3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>])</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mean_v_3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>])</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>var_s_3 <span class="ot">&lt;-</span> <span class="fu">var</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>var_v_3 <span class="ot">&lt;-</span> <span class="fu">var</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>])</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>count_s_3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"setosa"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>count_v_3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(iris<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"versicolor"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> (var_s_3<span class="sc">/</span>count_s_3 <span class="sc">+</span> var_v_3<span class="sc">/</span>count_v_3)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> ((var_s_3<span class="sc">/</span>count_s_3)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(count_s_3 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> (var_v_3<span class="sc">/</span>count_v_3)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(count_v_3 <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>lower_bound_5 <span class="ot">&lt;-</span> (mean_v_3 <span class="sc">-</span> mean_s_3) <span class="sc">-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df) <span class="sc">*</span> <span class="fu">sqrt</span>(var_v_3<span class="sc">/</span>count_v_3 <span class="sc">+</span> var_s_3<span class="sc">/</span>count_s_3)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>upper_bound_5 <span class="ot">&lt;-</span> (mean_v_3 <span class="sc">-</span> mean_s_3) <span class="sc">+</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df) <span class="sc">*</span> <span class="fu">sqrt</span>(var_v_3<span class="sc">/</span>count_v_3 <span class="sc">+</span> var_s_3<span class="sc">/</span>count_s_3)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk beda mean Sepal Length setosa dengan versicolor adalah (%.4f, %.4f)."</span>, lower_bound_5, upper_bound_5))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk beda mean Sepal Length setosa dengan versicolor adalah (0.7543, 1.1057).</code></pre>
</div>
</div>
<p>Pada ketiga kasus beda mean di atas, populasi yang digunakan adalah populasi yang independen (populasi yang tidak ada korelasinya sama sekali). Bagaimana dengan populasi yang dependen? Terkadang, ada kasus dimana kita ingin menentukan beda mean antar populasi yang saling berpasangan. Misalnya, dalam dataset <code>sleep</code> bawaan R, terdapat <span class="math inline">\(10\)</span> partisipan yang diberikan dua jenis obat tidur yang berbeda, dan kemudian penambahan waktu tidur setiap subjek didata pada setiap obat. Data seperti ini merupakan jenis data sampel berpasangan, dan akibatnya metode sebelumnya yang mengasumsikan sampelnya independen tidak dapat digunakan (bisa dilakukan, tetapi tidak akan akurat).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(sleep)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  extra group ID
1   0.7     1  1
2  -1.6     1  2
3  -0.2     1  3
4  -1.2     1  4
5  -0.1     1  5
6   3.4     1  6</code></pre>
</div>
</div>
<p>Untuk menangani masalah ini, kita bisa menggunakan taksiran interval untuk sampel berpasangan. Pertama, kita buat kolom baru yang berisi data perbedaan antara kedua sampel, yaitu</p>
<p><span class="math display">\[
d_i = x_{2i} - x_{1i}
\]</span></p>
<p>Kemudian baru menghitung mean dan variansi pada sampel berpasangan ini, yaitu dihitung dengan</p>
<p><span class="math display">\[
\bar{d} = \frac{1}{n} \sum_{i = 1}^{n}{d_i}
\]</span></p>
<p><span class="math display">\[
s_d^2 = \frac{1}{n - 1} \sum_{i = 1}^{n}{(d_i - \bar{d})^2}
\]</span></p>
<p>Dan terakhir, interval kepercayaannya yaitu</p>
<p><span class="math display">\[
\text{CI} = \bar{d} \pm t_{1-\alpha/2;n - 1} \cdot \frac{s_d}{\sqrt{n}}
\]</span></p>
<p>Sebagai contoh, misalkan kita ingin mengetahui interval kepercayaan <span class="math inline">\(95\%\)</span> untuk perbedaan penambahan waktu tidur untuk kedua jenis obat tidur (1 dan 2) dari data <code>sleep</code>. Menggunakan R, interval kepercayaan <span class="math inline">\(95\%\)</span> nya dapat dihitung sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> <span class="fu">with</span>(sleep, extra[group <span class="sc">==</span> <span class="dv">2</span>] <span class="sc">-</span> extra[group <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>mean_diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(diff)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>var_diff <span class="ot">&lt;-</span> <span class="fu">var</span>(diff)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>sd_diff <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_diff)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>count_diff <span class="ot">&lt;-</span> <span class="fu">length</span>(diff)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>lower_bound_6 <span class="ot">&lt;-</span> mean_diff <span class="sc">-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> count_diff <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> sd_diff <span class="sc">/</span> <span class="fu">sqrt</span>(count_diff)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>upper_bound_6 <span class="ot">&lt;-</span> mean_diff <span class="sc">+</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> count_diff <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> sd_diff <span class="sc">/</span> <span class="fu">sqrt</span>(count_diff)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk beda mean kedua obat tidur adalah (%.4f, %.4f)."</span>, lower_bound_6, upper_bound_6))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk beda mean kedua obat tidur adalah (0.7001, 2.4599).</code></pre>
</div>
</div>
<p>Selain untuk mean dan perbedaan mean, kita juga bisa menentukan interval kepercayaan untuk perbedaan dua proporsi. Contohnya adalah menentukan interval kepercayaan perbedaan proporsi mahasiswa pria pada dua universitas yang berbeda. Contoh lain adalah menentukan interval kepercayaan perbedaan proporsi mobil dengan miles per gallon lebih dari <span class="math inline">\(20\)</span> pada mobil matic dengan mobil manual, yang dapat dilakukan menggunakan data <code>mtcars</code>.</p>
<p>Interval kepercayaan untuk perbedaan proporsi antara dua populasi independen yaitu</p>
<p><span class="math display">\[
\text{CI} = (\hat{p}_1 - \hat{p}_2) \pm z_{1-\alpha/2} \cdot \sqrt{\frac{\hat{p}_1\hat{q}_1}{n_1} + \frac{\hat{p}_2\hat{q}_2}{n_2}}
\]</span></p>
<p>dengan <span class="math inline">\(\hat{p}_1\)</span> dan <span class="math inline">\(\hat{p}_2\)</span> adalah taksiran untuk proporsi pada kedua populasi secara berurutan, <span class="math inline">\(\hat{q}_1 = 1 - \hat{p}_1\)</span>, dan <span class="math inline">\(\hat{q}_2 = 1 - \hat{p}_2\)</span>.</p>
<p>Sebagai contoh, kita gunakan kembali data <code>mtcars</code> untuk menentukan interval kepercayaan <span class="math inline">\(95\%\)</span> perbedaan proporsi mobil dengan <code>mpg</code> lebih dari <span class="math inline">\(20\)</span> pada mobil matic (<code>am</code> = 0) dengan mobil manual (<code>am</code> = 1). Menggunakan R, interval kepercayaannya dapat ditentukan sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>high_mpg <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(mtcars<span class="sc">$</span>mpg <span class="sc">&gt;</span> <span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>count_matic <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>count_manual <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>p_matic <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>high_mpg[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>])<span class="sc">/</span><span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>q_matic <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> p_matic</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>p_manual <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>high_mpg[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>])<span class="sc">/</span><span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>q_manual <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> p_manual</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span> <span class="co">#alpha = 100% - 95%</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>lower_bound_7 <span class="ot">&lt;-</span> (p_manual <span class="sc">-</span> p_matic) <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(p_manual <span class="sc">*</span> q_manual <span class="sc">/</span> count_manual <span class="sc">+</span> p_matic <span class="sc">*</span> q_matic <span class="sc">/</span> count_matic)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>upper_bound_7 <span class="ot">&lt;-</span> (p_manual <span class="sc">-</span> p_matic) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(p_manual <span class="sc">*</span> q_manual <span class="sc">/</span> count_manual <span class="sc">+</span> p_matic <span class="sc">*</span> q_matic <span class="sc">/</span> count_matic)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"CI 95%% untuk beda proporsi mpg &gt; 20 mobil manual dengan matic adalah (%.4f, %.4f)."</span>, lower_bound_7, upper_bound_7))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CI 95% untuk beda proporsi mpg &gt; 20 mobil manual dengan matic adalah (0.2653, 0.8521).</code></pre>
</div>
</div>
</section>
<section id="pengujian-hipotesis" class="level2">
<h2 class="anchored" data-anchor-id="pengujian-hipotesis">Pengujian Hipotesis</h2>
<p>Selain taksiran titik dan taksiran interval, terdapat cara lain untuk melakukan inferensia, yaitu melakukan pengujian hipotesis. Pengujian hipotesis biasanya lebih disukai dan lebih sering digunakan dibandingkan dengan taksiran interval, karena kesimpulannya lebih jelas dan interpretasinya sederhana, dan aplikasinya jauh lebih banyak dibandingkan dengan interval kepercayaan. Meskipun demikian, teori statistika dibalik pengujian hipotesis juga lebih sulit dibandingkan dengan teori pada taksiran titik dan interval.</p>
<p>Pada mata kuliah Pengantar Sains Data, kita hanya akan membahas uji-uji hipotesis yang paling sederhana, yaitu uji-z dan uji-t. Secara umum, langkah-langkah yang perlu dilakukan dalam melakukan pengujian hipotesis adalah:</p>
<ol type="1">
<li>Medefinisikan variabel acak dan menentukan tujuan uji hipotesis,</li>
<li>Menentukan hipotesis null (<span class="math inline">\(H_0\)</span>) dan hipotesis alternatif (<span class="math inline">\(H_1\)</span>),</li>
<li>Menentukan taraf signifikansi <span class="math inline">\(\alpha\)</span>,</li>
<li>Menghitung statistik uji,</li>
<li>Menentukan aturan penolakan,</li>
<li>Mengambil kesimpulan.</li>
</ol>
<p>Sebagai contoh pertama, misalkan pada data <code>mtcars</code> kita ingin menguji apakah variabel <code>disp</code> memiliki mean <span class="math inline">\(\mu = 250\)</span>. Untuk menguji hipotesis mean seperti ini, biasanya kita akan menggunakan uji-z jika ukuran sampel lebih dari <span class="math inline">\(30\)</span> atau variansi populasi diketahui, dan menggunakan uji-t jika ukuran sampel berukuran 30 ke bawah dan variansi populasi tidak diketahui.</p>
<p>Statistik uji untuk uji-z yaitu</p>
<p><span class="math display">\[
Z = \frac{\bar{x}-\mu_0}{\sigma/\sqrt{n}}
\]</span></p>
<p>Dalam kasus variansi populasi tidak diketahui tetapi ukuran sampel masih cukup besar, <span class="math inline">\(\sigma\)</span> bisa diganti dengan <span class="math inline">\(s\)</span>.</p>
<p>Statistik uji untuk uji-t yaitu</p>
<p><span class="math display">\[
T = \frac{\bar{x}-\mu_0}{s/\sqrt{n}}
\]</span></p>
<p>Berikut adalah pengujian hipotesis dua ekor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis dua ekor.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu = 250</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu /= 250</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>disp_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>disp_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>disp_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(mtcars)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (disp_mean <span class="sc">-</span> mu_0) <span class="sc">/</span> (disp_sd <span class="sc">/</span> <span class="fu">sqrt</span>(disp_count))</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>Z_lower <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>Z_upper <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika Z &lt; Z_lower atau Z &gt; Z_upper.</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(Z <span class="sc">&lt;</span> Z_lower <span class="sc">|</span> Z <span class="sc">&gt;</span> Z_upper,</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil tidak sama dengan 250."</span>,</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan bisa juga dengan p-value</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(Z)))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil tidak sama dengan 250."</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji Z = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu Z &lt; %.4f atau Z &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, Z, Z_lower, Z_upper, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji Z = -0.8799
Daerah penolakannya yaitu Z &lt; -1.9600 atau Z &gt; 1.9600
P-value = 0.378914</code></pre>
</div>
</div>
<p>Berikut adalah pengujian hipotesis ekor kiri:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis ekor kiri.</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu &gt;= 250</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu &lt; 250</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>disp_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>disp_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>disp_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(mtcars)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (disp_mean <span class="sc">-</span> mu_0) <span class="sc">/</span> (disp_sd <span class="sc">/</span> <span class="fu">sqrt</span>(disp_count))</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>Z_lower <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika Z &lt; Z_lower.</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(Z <span class="sc">&lt;</span> Z_lower,</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih kecil dari 250."</span>,</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan bisa juga dengan p-value</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(Z)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih kecil dari 250."</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji Z = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu Z &lt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, Z, Z_lower, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji Z = -0.8799
Daerah penolakannya yaitu Z &lt; -1.6449
P-value = 0.189457</code></pre>
</div>
</div>
<p>Berikut adalah pengujian hipotesis ekor kanan:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis ekor kanan.</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu &lt;= 250</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu &gt; 250</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>disp_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>disp_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(mtcars<span class="sc">$</span>disp)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>disp_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(mtcars)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (disp_mean <span class="sc">-</span> mu_0) <span class="sc">/</span> (disp_sd <span class="sc">/</span> <span class="fu">sqrt</span>(disp_count))</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>Z_upper <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha)</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika Z &gt; Z_upper.</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(Z <span class="sc">&gt;</span> Z_upper,</span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih besar dari 250."</span>,</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan bisa juga dengan p-value</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(Z)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih besar dari 250."</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih besar dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih besar dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji Z = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu Z &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, Z, Z_upper, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji Z = -0.8799
Daerah penolakannya yaitu Z &gt; 1.6449
P-value = 0.810543</code></pre>
</div>
</div>
<p>Pada contoh ini, uji-z dilakukan karena ukuran sampelnya lebih dari 30. Meskipun demikian, sebagai demonstrasi, akan dilakukan uji-t pada data yang sama. Kode untuk uji-t lebih sederhana karena ada fungsi bawaan untuk uji-t pada R, yaitu <code>t.test</code>.</p>
<p>Berikut adalah pengujian hipotesis dua ekor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis dua ekor.</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu = 250</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu /= 250</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mtcars<span class="sc">$</span>disp, <span class="at">mu =</span> mu_0, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>T_ <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(result<span class="sc">$</span>statistic)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> result<span class="sc">$</span>parameter</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>T_lower <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>T_upper <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span><span class="sc">-</span>alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika T_ &lt; T_lower atau T_ &gt; T_upper.</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(T_ <span class="sc">&lt;</span> T_lower <span class="sc">|</span> T_ <span class="sc">&gt;</span> T_upper,</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil tidak sama dengan 250."</span>,</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa dengan p-value</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> result<span class="sc">$</span>p.value</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil tidak sama dengan 250."</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji T = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu T &lt; %.4f atau T &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, T_, T_lower, T_upper, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji T = -0.8799
Daerah penolakannya yaitu T &lt; -2.0395 atau T &gt; 2.0395
P-value = 0.385684</code></pre>
</div>
</div>
<p>Berikut adalah pengujian hipotesis ekor kiri:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis ekor kiri.</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu &gt;= 250</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu &lt; 250</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mtcars<span class="sc">$</span>disp, <span class="at">mu =</span> mu_0, <span class="at">alternative =</span> <span class="st">"less"</span>)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>T_ <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(result<span class="sc">$</span>statistic)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> result<span class="sc">$</span>parameter</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>T_lower <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha, <span class="at">df =</span> df)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika T_ &lt; T_lower.</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(T_ <span class="sc">&lt;</span> T_lower,</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih kecil dari 250."</span>,</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa dengan p-value</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> result<span class="sc">$</span>p.value</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih kecil dari 250."</span>,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji T = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu T &lt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, T_, T_lower, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji T = -0.8799
Daerah penolakannya yaitu T &lt; -1.6955
P-value = 0.192842</code></pre>
</div>
</div>
<p>Berikut adalah pengujian hipotesis ekor kanan:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D yang menyatakan displacement mobil.</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis ekor kanan.</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu &lt;= 250</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu &gt; 250</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">250</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mtcars<span class="sc">$</span>disp, <span class="at">mu =</span> mu_0, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>T_ <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(result<span class="sc">$</span>statistic)</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> result<span class="sc">$</span>parameter</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>T_upper <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, <span class="at">df =</span> df)</span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika T_ &gt; T_upper.</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(T_ <span class="sc">&gt;</span> T_upper,</span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih dari 250."</span>,</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa dengan p-value</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> result<span class="sc">$</span>p.value</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha.</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value <span class="sc">&lt;</span> alpha,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean dari displacement mobil lebih dari 250."</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 diterima. Jadi, mean dari displacement mobil lebih kecil dari atau sama dengan 250."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji T = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu T &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, T_, T_upper, p_value))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji T = -0.8799
Daerah penolakannya yaitu T &gt; 1.6955
P-value = 0.807158</code></pre>
</div>
</div>
<p>Untuk uji-uji hipotesis selanjutnya, hanya pengujian dua hipotesis dua ekor yang akan ditampilkan, karena kodenya tidak berbeda jauh antara uji dua ekor, ekor kiri, dan ekor kanan.</p>
<p>Selain untuk menguji mean 1 populasi, uji-z dan uji-t juga dapat dilakukan untuk menguji beda mean antara 2 populasi. Sama seperti pada interval kepercayaan, untuk populasi independen, terdapat 3 kasus yaitu saat variansi kedua populasi diketahui, saat variansi kedua populasi tidak diketahui tetapi sama, dan saat variansi kedua populasi tidak diketahui dan tidak sama.</p>
<p>Sebagai contoh, misalkan kita ingin menguji hipotesis bahwa mean displacement pada mobil matic tidak sama dengan mean displacement pada mobil manual.</p>
<p>Untuk kasus variansi kedua populasi diketahui, statistik ujinya adalah</p>
<p><span class="math display">\[
Z = \frac{(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)}{\sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}}
\]</span></p>
<p>Untuk kasus pertama, misalkan kita mengetahui standar deviasi displacement pada mobil matic yaitu <span class="math inline">\(\sigma_1 = 100\)</span> dan standar deviasi displacement pada mobil manual yaitu <span class="math inline">\(\sigma_2 = 90\)</span>. Menggunakan R, pengujian hipotesisnya yaitu sebagai berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D_1 yang menyatakan displacement mobil matic dan variabel acak D_2 yang menyatakan displacement mobil manual.</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis dua ekor.</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu_1 - mu_2 = 0</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu_1 - mu_2 /= 0</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>diff_0 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>matic_disp_mean_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>])</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>manual_disp_mean_1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>diff_disp_1 <span class="ot">&lt;-</span> matic_disp_mean_1 <span class="sc">-</span> manual_disp_mean_1</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>matic_disp_var_1 <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>manual_disp_var_1 <span class="ot">&lt;-</span> <span class="dv">90</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>matic_count_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>manual_count_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> (diff_disp_1 <span class="sc">-</span> diff_0) <span class="sc">/</span> <span class="fu">sqrt</span>(matic_disp_var_1<span class="sc">/</span>matic_count_1 <span class="sc">+</span> manual_disp_var_1<span class="sc">/</span>manual_count_1)</span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>Z_lower <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>Z_upper <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb65-20"><a href="#cb65-20" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika Z &lt; Z_lower atau Z &gt; Z_upper</span></span>
<span id="cb65-21"><a href="#cb65-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(Z <span class="sc">&lt;</span> Z_lower <span class="sc">|</span> Z <span class="sc">&gt;</span> Z_upper,</span>
<span id="cb65-22"><a href="#cb65-22" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb65-23"><a href="#cb65-23" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa menggunakan p-value</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>p_value_1 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(Z)))</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value_1 <span class="sc">&lt;</span> alpha,</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji Z = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu Z &lt; %.4f atau Z &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, Z, Z_lower, Z_upper, p_value_1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji Z = 4.3315
Daerah penolakannya yaitu Z &lt; -1.9600 atau Z &gt; 1.9600
P-value = 0.000015</code></pre>
</div>
</div>
<p>Untuk kasus variansi kedua populasi tidak diketahui, tetapi sama, statistik ujinya adalah</p>
<p><span class="math display">\[
T = \frac{(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)}{s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}
\]</span></p>
<p>dengan variansi pooled <span class="math inline">\(s_p^2\)</span> nya adalah</p>
<p><span class="math display">\[
s_p^2 = \frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}
\]</span></p>
<p>Kita akan menggunakan kasus displacement mobil matic dan mobil manual pada data <code>mtcars</code> lagi sebagai contoh, kali ini dengan variansi yang tidak diketahui tapi dianggap sama.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D_1 yang menyatakan displacement mobil matic dan variabel acak D_2 yang menyatakan displacement mobil manual.</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis dua ekor.</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu_1 - mu_2 = 0</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu_1 - mu_2 /= 0</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>diff_0 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>result_1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>], mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>], <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> mu_0, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>T_1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(result_1<span class="sc">$</span>statistic)</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>df_1 <span class="ot">&lt;-</span> result_1<span class="sc">$</span>parameter</span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>T_lower <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df_1)</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>T_upper <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df_1)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika T_1 &lt; T_lower atau T_1 &gt; T_upper</span></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(T_1 <span class="sc">&lt;</span> T_lower <span class="sc">|</span> T_1 <span class="sc">&gt;</span> T_upper,</span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa menggunakan p-value</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>p_value_2 <span class="ot">&lt;-</span> result_1<span class="sc">$</span>p.value</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value_2 <span class="sc">&lt;</span> alpha,</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji T = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu T &lt; %.4f atau T &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, T_1, T_lower, T_upper, p_value_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji T = -2.8204
Daerah penolakannya yaitu T &lt; -2.0423 atau T &gt; 2.0423
P-value = 0.008421</code></pre>
</div>
</div>
<p>Untuk kasus variansi kedua populasi tidak diketahui dan belum tentu sama, statistik ujinya adalah</p>
<p><span class="math display">\[
T = \frac{(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}
\]</span></p>
<p>Statistik uji ini akan berdistribusi t dengan derajat bebas yaitu</p>
<p><span class="math display">\[
v = \frac{(s_1^2/n_1 + s_2^2/n_2)^2}{\frac{(s_1^2/n_1)^2}{n_1-1} + \frac{(s_2^2/n_2)^2}{n_2-2}}
\]</span></p>
<p>Sekali lagi, kita akan menggunakan kasus displacement mobil matic dan mobil manual pada data <code>mtcars</code> sebagai contoh, dan kali ini dengan variansi yang tidak diketahui dan tidak dianggap sama.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definisikan variabel acak D_1 yang menyatakan displacement mobil matic dan variabel acak D_2 yang menyatakan displacement mobil manual.</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan dilakukan uji hipotesis dua ekor.</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 : mu_1 - mu_2 = 0</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="co"># H1 : mu_1 - mu_2 /= 0</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>diff_0 <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan digunakan taraf signifikansi alpha = 0.05.</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perhitungan statistik ujinya yaitu</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>result_2 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">0</span>], mtcars<span class="sc">$</span>disp[mtcars<span class="sc">$</span>am <span class="sc">==</span> <span class="dv">1</span>], <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu =</span> mu_0, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>T_2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(result_2<span class="sc">$</span>statistic)</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Akan ditentukan aturan penolakannya</span></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>df_2 <span class="ot">&lt;-</span> result_2<span class="sc">$</span>parameter</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>T_lower <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df_2)</span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>T_upper <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> df_2)</span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika T_2 &lt; T_lower atau T_2 &gt; T_upper</span></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(T_2 <span class="sc">&lt;</span> T_lower <span class="sc">|</span> T_2 <span class="sc">&gt;</span> T_upper,</span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb77-18"><a href="#cb77-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aturan penolakan juga bisa menggunakan p-value</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>p_value_3 <span class="ot">&lt;-</span> result_2<span class="sc">$</span>p.value</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="co"># H0 ditolak jika p-value &lt; alpha</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">ifelse</span>(p_value_3 <span class="sc">&lt;</span> alpha,</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</span>,</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"H0 diterima. Jadi, mean displacement antara mobil matic dengan mobil manual sama."</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "H0 ditolak. Jadi, mean displacement antara mobil matic dengan mobil manual berbeda."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Statistik uji T = %.4f</span><span class="sc">\n</span><span class="st">Daerah penolakannya yaitu T &lt; %.4f atau T &gt; %.4f</span><span class="sc">\n</span><span class="st">P-value = %.6f"</span>, T_2, T_lower, T_upper, p_value_3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistik uji T = -2.9486
Daerah penolakannya yaitu T &lt; -2.0444 atau T &gt; 2.0444
P-value = 0.006217</code></pre>
</div>
</div>
</section>
<section id="pengayaan-perhitungan-probabilitas-terjadinya-galat-menggunakan-r" class="level2">
<h2 class="anchored" data-anchor-id="pengayaan-perhitungan-probabilitas-terjadinya-galat-menggunakan-r">(Pengayaan) Perhitungan Probabilitas Terjadinya Galat Menggunakan R</h2>
<p><em>(work in progress)</em></p>
</section>
<section id="pengayaan-pengujian-hipotesis-untuk-sampel-berpasangan" class="level2">
<h2 class="anchored" data-anchor-id="pengayaan-pengujian-hipotesis-untuk-sampel-berpasangan">(Pengayaan) Pengujian Hipotesis untuk Sampel Berpasangan</h2>
<p><em>(work in progress)</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>