---
title: "Praktikum Struktur Data 2023 Ganjil dengan Python (Kurikulum 2020)"
---

Kembali ke [Praktikum](../../../../praktikum.qmd)

Praktikum Struktur Data tahun 2023 semester ganjil ini akan dilaksanakan menggunakan bahasa pemrograman Python.

# Modul per pertemuan dan tugas

* [Modul 1: Tipe Data di Python](Strukdat2023_Modul01.ipynb), 14-15 September 2023 (*offline* di Lab Departemen Matematika D.311)

* [Modul 2: Pengantar OOP](Strukdat2023_Modul02.ipynb), 21-22 September 2023 (*online* melalui Zoom)

* [Modul 3: I/O, CodeChef](Strukdat2023_Modul03.ipynb), 29 September 2023 (*online* melalui Zoom)

* [Modul 4: Array, Searching, Sorting](Strukdat2023_Modul04.ipynb), 5-6 Oktober 2023 (*online* melalui Zoom)

* [Modul 5: Graphviz, Linked List](Strukdat2023_Modul05.ipynb), 12-13 Oktober 2023 (*online* melalui Zoom)

* [Tugas 1: Array, Linked List, OOP](Strukdat2023_Tugas1.ipynb)

    Diberikan: Minggu, 22 Oktober 2023

    *Deadline*: Minggu, 5 November 2023, 23.59 WIB

* [Modul 6: Stack](Strukdat2023_Modul06.ipynb), 2-3 November 2023 (*online* melalui Zoom)

* [Modul 7: Queue](Strukdat2023_Modul07.ipynb), 9-10 November 2023 (*online* melalui Zoom)

* [Modul 8: Binary Tree, Binary Search Tree (BST)](Strukdat2023_Modul08.ipynb), 16-17 November 2023 (*online* melalui Zoom)

* [Modul 9: Heap Tree, AVL/Balance Tree](Strukdat2023_Modul09.ipynb), 23-24 November 2023 (*online* melalui Zoom)

    * [(coming soon) Modul 9a: A-B Tree dan variasinya (B-Tree, 2-3 Tree, dsb)](./Strukdat2023_Modul09a.ipynb)

* [Tugas 2: Stack, Queue, dan berbagai Binary Tree](./Strukdat2023_Tugas2.ipynb)

    Diberikan: Sabtu, 25 November 2023

    *Deadline*: Sabtu, 9 Desember 2023, 23.59 WIB

* [Modul 10: Pengantar *database* dengan SQLite](./Strukdat2023_Modul10.ipynb), 30 November--1 Desember 2023 (*online* melalui Zoom)

# Rekaman praktikum

Semua rekaman praktikum Struktur Data (yang dilaksanakan secara *online* melalui Zoom) disimpan di *link* berikut.

[https://bit.ly/RekamanPrakStrukdat2023Ganjil](https://bit.ly/RekamanPrakStrukdat2023Ganjil)

Tiap kali ada praktikum, rekaman akan di-*upload* ke *folder* Google Drive tersebut beberapa hari kemudian.

Antara praktikum kelas A dan kelas B, materinya sama saja; apabila untuk materi tertentu hanya ada rekaman untuk salah satu kelas, tonton saja yang ada, harusnya tidak masalah.