---
title: 'TUGAS 2 Praktikum Metode Numerik: Ekstrapolasi dan Integrasi'
subtitle: Assignment
author:
  - Laboratorium Komputasi Matematika
  - Departemen Matematika FMIPA UI
description: Online dan Offline di Departemen Matematika
date: 05/02/2025
page-navigation: true
format: html
execute:
  enabled: false
jupyter: python3
---

### Petunjuk Umum:

1. Kerjakan secara Individu
2. Kerjakan tugas ini menggunakan bahasa pemrograman Python dengan file format berupa interactive Python notebook (yaitu file berbentuk .ipynb BUKAN .py), yang bisa dibuat misalnya menggunakan Jupyter Notebook atau Google Colaboratory.
3. **Harap sertakan penjelasan untuk setiap variabel yang digunakan dan setiap proses secara singkat** di samping potongan kode (dengan comment, ‘#'). Selain itu, **sertakan juga penjelasan program** (yang bisa mencakupi idenya apa, bagaimana cara eksekusi program, atau tentang algoritma program yang digunakan) **pada *cell* di sebelah (atas/bawah) program**.
4. Format nama *file* untuk Tugas 2 ini adalah:

    Nama Lengkap_NPM_Kelas SIAK_Tugas2PrakMetnum.ipynb

    Contoh penamaan yang benar:

    Luthfi Athallah Herdita Wiryaman_2206826980_Kelas G_Tugas1PrakMetnum_OnSite.ipynb

    Luthfi Athallah Herdita Wiryaman_2206826980_Kelas G_Tugas1PrakMetnum_OnSite_revisi1.ipynb

5. Pengumpulan tugas dilakukan ke Google Forms berikut ini, sesuai dengan kelas Anda di SIAK NG (link akan selalu sama untuk semua tugas praktikum metode numerik):
- Kelas A: [https://forms.gle/3xguPQVR2HJGbi456](https://forms.gle/7WhpRfnXv1bvmmRb8)
- Kelas B: [https://forms.gle/XfxJAUyAdwDLgMwj6](https://forms.gle/cCM65Q6esQbAzJzp6)
- Kelas C: [https://forms.gle/ihiKuSjU65fpxEZ67](https://forms.gle/RDNKibWRkxh24BBa6)
- Kelas D: [https://forms.gle/15BVmErcputb5NrX8](https://forms.gle/smY8ca8gDCgeSusw5)
- Kelas E: [https://forms.gle/MydWb7kku6iyvdNNA](https://forms.gle/MRdEe2fYUUSzK5xYA)
- Kelas F: [https://forms.gle/RuKXWpwQeu7Jbt5YA](https://forms.gle/sfTdcfZ4t8S9AKLn6)

6. Durasi pengerjaan Tugas 2 ini adalah 9 (sembilan) hari, dan tenggat waktu (deadline) pengumpulan Tugas 2 ini adalah Sabtu, 10 Mei 2025 pukul 23.59 WIB.
Mohon manfaatkan waktu Anda dengan baik (seperti mencicil pengerjaan, bahkan sudah selesai dari jauh-jauh hari) agar mengumpulkan tugas sebelum deadline. Keterlambatan pengumpulan bisa dikenakan pengurangan nilai atau bahkan dianggap tidak mengumpulkan, tergantung kesepakatan dari dosen. Meskipun demikian, lebih baik terlambat mengumpulkan daripada tidak mengumpulkan sama sekali.

7. Sesuai standar Universitas Indonesia, **plagiarisme dilarang keras** dan bisa menyebabkan nilai tugas praktikum **menjadi nol untuk semua pihak yang terlibat, tanpa peringatan apapun**.

8. *Module* atau *package* Python yang boleh digunakan (di-import) untuk Tugas 2 ini hanyalah numpy, tabulate, matplotlib, dan sympy. Apabila Anda berniat ingin menggunakan module lain, harap konfirmasikan ke narahubung terlebih dahulu (bisa saja diperbolehkan).
Narahubung untuk Tugas 1 Praktikum Metode Numerik adalah:
    - 📞 Fasya (LINE: ifasyai)


### Diferensiasi Numerik

Buatlah suatu program dengan nama **turunkan()** yaitu program yang menerima sembarang input berupa fungsi $f(x)$, titik evaluasi fungsi $x_0$, dan stepsize $h$ untuk dilakukan diferensiasi numerik.

Isi program tersebut meliputi:
1. Input fungsi yang bisa ditetapkan pengguna sesuka hati.
2. Input nilai $x_0$ dan stepsize $h$ yang ditetapkan bersamaan dengan fungsi.
3. Kondisi untuk mengulang program berkali-kali.
4. Handling error yang mungkin dapat terjadi.

Output program berupa tabel yang berisi nilai eksak turunan fungsi, hasil diferensiasi numerik Metode Forward-Backward, Three-Point, dan Five-Point (Three point dan five point termasuk juga).

Lalu, menurut anda berdasarkan fungsi-fungsi yang telah anda gunakan sebagai output (minimal 5 fungsi), metode mana yang terbaik dalam mengaproksimasi nilai turunan dari fungsi-fungsi tersebut, jelaskan pada cell markdown!

Contoh Output sebagai berikut.

```{python}
#| colab: {base_uri: https://localhost:8080/}
turunkan()
```

### Ekstrapolasi Numerik

Diberikan suatu fungsi $f(x)$ yang ingin dicari nilai turunannya menggunakan Metode Ekstrapolasi Richardson untuk $h$ pangkat genap.

Buatlah suatu program yang dinamakan **PrintAll()** yang menerima input berupa sembarang fungsi $f(x)$, nilai evaluasi turunan $x_0$ dan $h$!

Output fungsi berupa tabel yang berisi perbandingan hasil ekstrapolasi menggunakan metode-metode turunan Numerik hingga $O(h^{16})$. Tambahan nilai jika anda membuat program dapat ditambahkan suku $O(h^{2j})$ berikutnya.

Berikut contoh output menggunakan fungsi $f(x) = x^2 $.

```{python}
PrintAll(f, 2, 0.01)
```

### Integrasi Numerik

Soal 1

Diberikan fungsi 

$$ g(x) = \cfrac{1}{\sigma \sqrt{2\pi}} e^{-\cfrac{(x-\mu)^2}{2\sigma ^ 2}} \text{ , pada interval } -1000 + \mu \leq x \leq 1000 + \mu $$

di mana $\mu$ adalah digit terakhir NPM dan $\sigma$ adalah kode kelas anda. Contoh: 220602512**3** berarti $\mu = 3$.

**Kode Kelas**

- A = 1

- B = 2

- C = 3

- D = 4

- E = 5

- F = 6

Buatlah program **IntegrateAll1()** dengan parameter yang sesuai menurut anda untuk melakukan integrasi numerik pada fungsi dengan batas tersebut menggunakan Metode Kuadratur Adaptif dengan semua Metode Newton-Cotes yang sudah anda pelajari pada praktikum (Open dan Closed)! Berikan juga hasil output dari setiap metode dalam satu tabel!


Contoh output untuk fungsi $g(x) = x^3$ dengan batas $[-1, 1]$

```{python}
def g(x):
    return x ** 3

IntegrateAll1(g, -1, 1, 0.000001)
```

Soal 2 dibagi menjadi berdasarkan NPM.

- Untuk NPM dengan digit terakhir ganjil, diberikan fungsi:

$$
f(x) = \begin{cases}
      \tan^5(\sin(\cos(x^2)) & -3\leq x\leq 0 \\
      -\tan^5(\sin(\cos(x^2)) & 0< x\leq 3 \\
   \end{cases}
$$

- Untuk NPM dengan digit terakhir genap, diberikan fungsi:

$$
f(x) = \begin{cases}
      -\tan^5(\sin(\cos(x^2)) & -3\leq x\leq 0 \\
      \tan^5(\sin(\cos(x^2)) & 0< x\leq 3 \\
   \end{cases}
$$

Buatlah program **IntegrateAll2()** dengan parameter yang sesuai menurut anda untuk melakukan integrasi numerik pada fungsi dengan batas tersebut menggunakan Metode Kuadratur Adaptif dengan semua Metode Newton-Cotes yang sudah anda pelajari pada praktikum (Open dan Closed)! Berikan juga hasil output dari setiap metode dalam satu tabel! 

Contoh output sama persis dengan contoh output pada nomor 1.

