---
title: "modul"
---

Halo pembaca, Bagaimana kabar kalian? Semoga sehat selalu ya. Sebelumnya aku tebak dulu, kalian pembaca adalah Asisten Laboratorium ya? Kalau iya, semoga modul ini dapat membantu kalian dalam perjalanan asistensi ya. Kalau bukan, semoga kalian berkesempatan menambah pengalaman menjadi asistensi laboratorium ya.

Sebelumnya, Asistensi Laboratorium itu berbeda dengan asisten mata kuliah pengajar dan asisten mata kuliah koreksi tugas. Perbedaan tersebut mencakup dalam pengajaran, tugas, penilaian, dan manajerial barang dan tim. Lebih detailnya ada di arsip Asisten Lab Kak Bisma ya. Pada kesempatan ini penulis akan membantu kalian dalam pengajaran.

# Quarto

Sebenarnya, banyak sekali yang bisa di eksplor dari bahasan quarto. Mungkin jika berkesempatan kedepannya akan disediakan tentang panduan, yakni:

-   Instalasi quarto local

-   quarto for learning, etc.

Namun, pada kesempatan kali ini hanya akan disediakan pegangan (Hands-on) untuk membantu asisten Lab dalam membuat modul.

## Cara pakai Hands-On

Bagian ini akan dijelaskan cara pakai Hands-On agar dapat memaksimalkan fungsi nya selagi akan datang pembaruan di masa yang akan datang.

\<!-- Nanti disini cara pakai Hands-On --!\>

\<!-- Nanti disini Hyperlink ke Hands-On --!\>

## Modul Quarto

Karena Hands-On adalah pegangan untuk memudahkan. Khusus di bagian modul quarto akan berfokus untuk lebih detail tentang panduan quarto websites untuk pemula.

* [Modul Quarto](./modulQuarto/modulQuarto.qmd)

# Git

sedikit banyak git akan berguna untuk proyek bersama. Jadi, diharapkan asisten praktikum menguasai Git dan Github. Mungkin jika berkesempatan kedepannya akan disediakan tentang panduan, yakni:

-   HuggingFace

-   Kaggle

-   Posit, etc.

## Git CI (Continuous Integration)

Bagian ini akan dijelaskan secara umum penggunaan git di rstudio dan visual studio code local

\<!-- Nanti disini Hyperlink ke Modul GIT CI --!\>

## Github

Bagian ini akan dijelaskan secara umum penggunaan github baik untuk personal dan bersama.

\<!-- Nanti disini Hyperlink ke Modul Github --!\>

# Content Delivery Network

Bagian ini akan dijelaskan bagaimana penyimpanan asset. Fungsinya asset tersebut tidak berada di dalam direktori github. Sehingga, alokasi aset tersebut membuat github lebih ringan. Disini akan dibedakan tentang bagaimana embbedding gambar, video dan tugas untuk download. Mungkin jika berkesempatan kedepannya akan disediakan tentang panduan, yakni:

-   cloudinary API

-   cloud server (AWS)

-   server web development

-   pdf reader (extension or addon acrobat viewer)

## Panduan CDN Tugas

Pada panduan CDN untuk tugas akan diberikan penjelasan tentang bagaimana cara embedding asset yang berkaitan dengan tugas.

\<!-- Nanti disini Hyperlink ke Modul CDN Tugas --!\>

## Panduan CDN Materi

Apa yang dipelajari di CDN tugas sebenarnya bisa juga diterapkan pada CDN materi di website. Tapi, fokus kita ke embed suara dan gambar.

\<!-- Nanti disini Hyperlink ke Modul Dasar Cloudinary--!\>

# Latex

Seorang asistensi laboratorium juga harus dapat membuat pelaporan yang baik untuk dilaporkan berupa file formal. Oleh karenanya, jangan sampai seorang asisten Laboratorium unfamiliar dengan latex baik itu simbol maupun situsnya.

\<!-- Nanti disini Hyperlink ke Modul Latex Online dan Offline --!\>

\<!-- Nanti disini Hyperlink ke Modul Dasar Latex --!\>
