---
title: "(Pertemuan 06) Distribusi Kontinu di R, Inverse Transform Sampling, Distribusi di Excel"
subtitle: "Continuous Distributions in R, Inverse Transform Sampling, Distributions in Excel"
description: "Offline di Departemen Matematika"
date: 10/28/2024
page-navigation: true
format: html
---

Kembali ke [Pengantar Sains Data](./psd2024.qmd)

Melanjutkan dari pertemuan sebelumnya tentang distribusi diskirt di R, pada pertemuan kali ini, kita akan membahas tentang beberapa distribusi kontinu di R, tepatnya distribusi *uniform* (kontinu) dan distribusi normal. Memanfaatkan distribusi *uniform*, kita juga akan mempelajari tentang *inverse transform sampling*, yaitu metode yang umum digunakan untuk menghasilkan data *random* dari distribusi apapun. Terakhir, kita akan belajar cara menggunakan Excel untuk menghasilkan data *random*, memanfaatkan metode *inverse transform sampling* tersebut.

# Distribusi Kontinu dengan *base R*

## Distribusi Uniform (Kontinu)

## Distribusi Normal

## *Inverse Transform Sampling*

# Distribusi Kontinu dengan `distr`

## Distribusi Uniform (Kontinu)

## Distribusi Normal

# Distribusi di Excel

Silakan unduh *worksheet* berikut: [Worksheet Pertemuan 6](./worksheet_pertemuan6.xlsx)
