<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-11-25">
<meta name="description" content="Offline di Departemen Matematika">

<title>Logistic Regression – Lab Praktikum Departemen Matematika FMIPA UI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Lab Praktikum Departemen Matematika FMIPA UI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/praktikum.html"> 
<span class="menu-text">Praktikum</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/Announcement.html"> 
<span class="menu-text">Announcement</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../semuahalaman/Jadwal.html"> 
<span class="menu-text">Informasi Praktikum Departemen Matematika</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#struktur-pembelajaran" id="toc-struktur-pembelajaran" class="nav-link active" data-scroll-target="#struktur-pembelajaran">Struktur Pembelajaran</a>
  <ul class="collapse">
  <li><a href="#mempersiapkan-code" id="toc-mempersiapkan-code" class="nav-link" data-scroll-target="#mempersiapkan-code">Mempersiapkan code</a>
  <ul class="collapse">
  <li><a href="#attach-data" id="toc-attach-data" class="nav-link" data-scroll-target="#attach-data">Attach Data</a></li>
  <li><a href="#pre-processing-data" id="toc-pre-processing-data" class="nav-link" data-scroll-target="#pre-processing-data">Pre-Processing Data</a></li>
  <li><a href="#cleaning-data" id="toc-cleaning-data" class="nav-link" data-scroll-target="#cleaning-data">Cleaning Data</a></li>
  <li><a href="#handling-missing-value" id="toc-handling-missing-value" class="nav-link" data-scroll-target="#handling-missing-value">Handling Missing Value</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Logistic Regression</h1>
<p class="subtitle lead">Pembelajaran regresi logistic</p>
</div>

<div>
  <div class="description">
    Offline di Departemen Matematika
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="struktur-pembelajaran" class="level1">
<h1>Struktur Pembelajaran</h1>
<p>Halo, selamat sejahtera semua. Kali ini kita akan masuk pembelajaran regresi logistik. Pembelajaran kali ini akan memiliki bertujuan untuk mengetahui secara sederhana untuk kalian dapat menentukan kapan kalian menggunakan regresi linear sederhana &amp; regresi logistik sederhana.</p>
<p>Akan tetapi, bagi kalian yang ingin memahami secara penuh, kita tetap menyediakan penjelasan pada link halaman lainnya.</p>
<section id="mempersiapkan-code" class="level2">
<h2 class="anchored" data-anchor-id="mempersiapkan-code">Mempersiapkan code</h2>
<section id="attach-data" class="level3">
<h3 class="anchored" data-anchor-id="attach-data">Attach Data</h3>
<p>Kita akan mendapatkan koleksi data <em>real</em> dari <a href="http://archive.ics.uci.edu/">repositori pembelajaran mesin UCI</a> khususnya kita akan mengambil data <a href="http://archive.ics.uci.edu/ml/datasets/Heart+Disease">penyakit jantung</a></p>
<p>Kita mulai dengan membuat variabel bernama URL dan menyetelnya ke lokasi data yang kita inginkan</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/StatQuest/logistic_regression_demo/master/processed.cleveland.data"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url, <span class="at">header=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>beginilah cara <code>R</code> membaca <code>collection</code> data dari URL.</p>
<p>Fungsi <code>head</code> menunjukkan kepada kita 6 baris data pertama, sayangnya tidak ada kolom yang diberi <strong>label</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  V1 V2 V3  V4  V5 V6 V7  V8 V9 V10 V11 V12 V13 V14
1 63  1  1 145 233  1  2 150  0 2.3   3 0.0 6.0   0
2 67  1  4 160 286  0  2 108  1 1.5   2 3.0 3.0   2
3 67  1  4 120 229  0  2 129  1 2.6   2 2.0 7.0   1
4 37  1  3 130 250  0  0 187  0 3.5   3 0.0 3.0   0
5 41  0  2 130 204  0  2 172  0 1.4   1 0.0 3.0   0
6 56  1  2 120 236  0  0 178  0 0.8   1 0.0 3.0   0</code></pre>
</div>
</div>
<p><strong>Oh no!</strong></p>
<p>Data nya tidak rapih. Kalau begitu, sekarang …</p>
</section>
<section id="pre-processing-data" class="level3">
<h3 class="anchored" data-anchor-id="pre-processing-data">Pre-Processing Data</h3>
<p>Kita menamai kolom tersebut dengan nama yang terdaftar di situs web UCI.</p>
<p>Mari kita format ulang data nya agar:</p>
<ol type="1">
<li><strong>Mudah digunakan</strong></li>
<li><strong>Ditafsirkan</strong> <em>( interpreted )</em> dengan benar oleh <code>glm()</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"age"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"sex"</span>,<span class="co"># 0 = female, 1 = male</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cp"</span>, <span class="co"># chest pain</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1 = typical angina,</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2 = atypical angina,</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3 = non-anginal pain,</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 4 = asymptomatic</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"trestbps"</span>, <span class="co"># resting blood pressure (in mm Hg)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"chol"</span>, <span class="co"># serum cholestoral in mg/dl</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"fbs"</span>,  <span class="co"># fasting blood sugar if less than 120 mg/dl, 1 = TRUE, 0 = FALSE</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"restecg"</span>, <span class="co"># resting electrocardiographic results</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1 = normal</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2 = having ST-T wave abnormality</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3 = showing probable or definite left ventricular hypertrophy</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"thalach"</span>, <span class="co"># maximum heart rate achieved</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"exang"</span>,   <span class="co"># exercise induced angina, 1 = yes, 0 = no</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"oldpeak"</span>, <span class="co"># ST depression induced by exercise relative to rest</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"slope"</span>, <span class="co"># the slope of the peak exercise ST segment</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1 = upsloping</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2 = flat</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3 = downsloping</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ca"</span>, <span class="co"># number of major vessels (0-3) colored by fluoroscopy</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"thal"</span>, <span class="co"># this is short of thalium heart scan</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3 = normal (no cold spots)</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 6 = fixed defect (cold spots during rest and exercise)</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 7 = reversible defect (when cold spots only appear during exercise)</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"hd"</span> <span class="co"># (the predicted attribute) - diagnosis of heart disease</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 0 if less than or equal to 50% diameter narrowing</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1 if greater than 50% diameter narrowing</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hoorayy 🥰 sekarang ketika kita melihat 6 baris pertama dengan fungsi <code>head</code> segalanya terlihat jauh lebih baik🎉</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age sex cp trestbps chol fbs restecg thalach exang oldpeak slope  ca thal hd
1  63   1  1      145  233   1       2     150     0     2.3     3 0.0  6.0  0
2  67   1  4      160  286   0       2     108     1     1.5     2 3.0  3.0  2
3  67   1  4      120  229   0       2     129     1     2.6     2 2.0  7.0  1
4  37   1  3      130  250   0       0     187     0     3.5     3 0.0  3.0  0
5  41   0  2      130  204   0       2     172     0     1.4     1 0.0  3.0  0
6  56   1  2      120  236   0       0     178     0     0.8     1 0.0  3.0  0</code></pre>
</div>
</div>
<p>Namun, fungsi <code>str</code> yang menjelaskan struktur data memberi tahu kita bahwa beberapa kolom sedang kacau saat ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data) <span class="co"># this shows that we need to tell R which columns contain factors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   303 obs. of  14 variables:
 $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
 $ sex     : num  1 1 1 1 0 1 0 0 1 1 ...
 $ cp      : num  1 4 4 3 2 2 4 4 4 4 ...
 $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
 $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
 $ fbs     : num  1 0 0 0 0 0 0 0 0 1 ...
 $ restecg : num  2 2 2 0 2 0 2 0 2 2 ...
 $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
 $ exang   : num  0 1 1 0 0 0 0 1 0 1 ...
 $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
 $ slope   : num  3 2 2 3 1 1 3 1 2 3 ...
 $ ca      : chr  "0.0" "3.0" "2.0" "0.0" ...
 $ thal    : chr  "6.0" "3.0" "7.0" "3.0" ...
 $ hd      : int  0 2 1 0 0 0 3 0 2 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># it also shows us that there are some missing values. There are "?"s</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># in the dataset. These are in the "ca" and "thal" columns...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>kekacauannya adalah sebagai berikut:</p>
<ol type="1">
<li><code>sex</code> adalah angka (<strong>number</strong>) tetapi seharusnya menjadi <strong>factor</strong> di mana nol mewakili perempuan dan satu mewakili laki laki</li>
<li><code>CP</code> alias nyeri dada juga seharusnya menjadi <strong>factor</strong> di mana level 1 hingga 3 mewakili berbagai jenis nyeri dan 4 tidak mewakili nyeri dada</li>
<li><code>CA</code> dan <code>Thal</code> disebut dengan benar sebagai <strong>faktor</strong> tetapi salah satu levelnya adalah <em>tanda tanya</em> saat kita membutuhkannya</li>
</ol>
<p>Jadi kita harus melakukan <strong>pembersihan</strong></p>
</section>
<section id="cleaning-data" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-data">Cleaning Data</h3>
<p>Hal pertama yang kita lakukan adalah</p>
<ul>
<li>mengubah <em>tanda tanya</em> menjadi <code>NA</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## First, convert "?"s to NAs...</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>data[data <span class="sc">==</span> <span class="st">"?"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>lalu hanya untuk mempermudah melihat data kita mengubah angka nol dalam <code>sex</code> menjadi F untuk perempuan dan yang menjadi M untuk laki laki</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Now add factors for variables that are factors and clean up the factors</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="do">## that had missing data...</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>data[data<span class="sc">$</span>sex <span class="sc">==</span> <span class="dv">0</span>,]<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"F"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>data[data<span class="sc">$</span>sex <span class="sc">==</span> <span class="dv">1</span>,]<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="st">"M"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>terakhir kita mengubah kolom yang seharusnya menjadi <strong>factor</strong> karena memang seharusnya demikian lihat situs web UCI</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>cp <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>cp)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>fbs <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>fbs)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>restecg <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>restecg)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>exang <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>exang)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>slope <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Oh no! Coba perhatikan yang lain sekarang. Karena kolom <code>CA</code> awalnya memiliki <em>tanda tanya</em> di dalamnya alih-alih menganggap itu kolom <code>string</code>, kita mengoreksi asumsi itu dengan memberi tahu bahwa itu adalah kolom <code>integer</code> dan kemudian kita mengubahnya menjadi <strong>factor</strong>, lalu kita melakukan hal yang sama untuk <code>Thal</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ca <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(data<span class="sc">$</span>ca) <span class="co"># since this column had "?"s in it</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># R thinks that the levels for the factor are strings, but</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># we know they are integers, so first convert the strings to integers...</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>ca <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>ca)  <span class="co"># ...then convert the integers to factor levels</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>thal <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(data<span class="sc">$</span>thal) <span class="co"># "thal" also had "?"s in it.</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>thal <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>thal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>hal lain yang perlu kita lakukan pada data adalah menjadikan <code>HD</code> alias penyakit jantung sebagai <strong>factor</strong> yang mudah dilihat.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## This next line replaces 0 and 1 with "Healthy" and "Unhealthy"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>hd <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="at">test=</span>data<span class="sc">$</span>hd <span class="sc">==</span> <span class="dv">0</span>, <span class="at">yes=</span><span class="st">"Healthy"</span>, <span class="at">no=</span><span class="st">"Unhealthy"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>hd <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>hd) <span class="co"># Now convert to a factor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Di sini saya menggunakan trik <em>fancy</em> dengan fungsi <code>if-else</code> untuk mengubah angka nol menjadi sehat dan yang menjadi tidak sehat.</p>
<p>Kita bisa saja melakukan trik serupa untuk <code>sex</code> tapi saya ingin menunjukkan kepada Anda, kedua cara ini untuk mengubah angka menjadi <code>string</code>.</p>
<p>Setelah selesai memperbaiki data, kita periksa bahwa kita telah membuat perubahan yang sesuai kita harapkan dengan fungsi <code>str</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data) <span class="do">## this shows that the correct columns are factors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   303 obs. of  14 variables:
 $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
 $ sex     : Factor w/ 2 levels "F","M": 2 2 2 2 1 2 1 1 2 2 ...
 $ cp      : Factor w/ 4 levels "1","2","3","4": 1 4 4 3 2 2 4 4 4 4 ...
 $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
 $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
 $ fbs     : Factor w/ 2 levels "0","1": 2 1 1 1 1 1 1 1 1 2 ...
 $ restecg : Factor w/ 3 levels "0","1","2": 3 3 3 1 3 1 3 1 3 3 ...
 $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
 $ exang   : Factor w/ 2 levels "0","1": 1 2 2 1 1 1 1 2 1 2 ...
 $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
 $ slope   : Factor w/ 3 levels "1","2","3": 3 2 2 3 1 1 3 1 2 3 ...
 $ ca      : Factor w/ 4 levels "0","1","2","3": 1 4 3 1 1 1 3 1 2 1 ...
 $ thal    : Factor w/ 3 levels "3","6","7": 2 1 3 1 1 1 1 1 3 3 ...
 $ hd      : Factor w/ 2 levels "Healthy","Unhealthy": 1 2 2 1 1 1 2 1 2 2 ...</code></pre>
</div>
</div>
<p>hoooraaayy berhasil 🎉🎉🎉</p>
</section>
<section id="handling-missing-value" class="level3">
<h3 class="anchored" data-anchor-id="handling-missing-value">Handling Missing Value</h3>
<p>Sekarang kita melihat berapa banyak baris sampel data yang memiliki nilai <code>na</code>. nanti kita akan memutuskan apakah kita bisa membuang sampel ini atau apakah kita harus memasukkan nilai untuk <code>NA</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Now determine how many rows have "NA" (aka "Missing data"). If it's just</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## a few, we can remove them from the dataset, otherwise we should consider</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="do">## imputing the values with a Random Forest or some other imputation method.</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data[<span class="fu">is.na</span>(data<span class="sc">$</span>ca) <span class="sc">|</span> <span class="fu">is.na</span>(data<span class="sc">$</span>thal),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data[<span class="fu">is.na</span>(data<span class="sc">$</span>ca) <span class="sc">|</span> <span class="fu">is.na</span>(data<span class="sc">$</span>thal),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age sex cp trestbps chol fbs restecg thalach exang oldpeak slope   ca thal
88   53   F  3      128  216   0       2     115     0     0.0     1    0 &lt;NA&gt;
167  52   M  3      138  223   0       0     169     0     0.0     1 &lt;NA&gt;    3
193  43   M  4      132  247   1       2     143     1     0.1     2 &lt;NA&gt;    7
267  52   M  4      128  204   1       0     156     1     1.0     2    0 &lt;NA&gt;
288  58   M  2      125  220   0       0     144     0     0.4     2 &lt;NA&gt;    7
303  38   M  3      138  175   0       0     173     0     0.0     1 &lt;NA&gt;    3
           hd
88    Healthy
167   Healthy
193 Unhealthy
267 Unhealthy
288   Healthy
303   Healthy</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## so 6 of the 303 rows of data have missing values. This isn't a large</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="do">## percentage (2%), so we can just remove them from the dataset</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 303</code></pre>
</div>
</div>
<p>6 baris sampel data memiliki <code>NA</code> di dalamnya.</p>
<p>kita dapat melihat sampel di dalamnya dengan memilih baris tersebut dari <code>dataframe</code> dan di sanalah mereka di sini adalah nilai <code>NA</code> lima dari enam sampel adalah laki-laki dan dua dari enam memiliki penyakit jantung.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>data[<span class="fu">is.na</span>(data<span class="sc">$</span>ca) <span class="sc">|</span> <span class="fu">is.na</span>(data<span class="sc">$</span>thal),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age sex cp trestbps chol fbs restecg thalach exang oldpeak slope   ca thal
88   53   F  3      128  216   0       2     115     0     0.0     1    0 &lt;NA&gt;
167  52   M  3      138  223   0       0     169     0     0.0     1 &lt;NA&gt;    3
193  43   M  4      132  247   1       2     143     1     0.1     2 &lt;NA&gt;    7
267  52   M  4      128  204   1       0     156     1     1.0     2    0 &lt;NA&gt;
288  58   M  2      125  220   0       0     144     0     0.4     2 &lt;NA&gt;    7
303  38   M  3      138  175   0       0     173     0     0.0     1 &lt;NA&gt;    3
           hd
88    Healthy
167   Healthy
193 Unhealthy
267 Unhealthy
288   Healthy
303   Healthy</code></pre>
</div>
</div>
<p>jika kita mau, kita dapat mengaitkan nilai untuk <code>NA</code> menggunakan <code>random forest</code> atau metode lain. namun untuk contoh ini kita hanya akan menghapus sampel ini termasuk enam sampel dalam <code>NA</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 303</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data[<span class="sc">!</span>(<span class="fu">is.na</span>(data<span class="sc">$</span>ca) <span class="sc">|</span> <span class="fu">is.na</span>(data<span class="sc">$</span>thal)),]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 297</code></pre>
</div>
</div>
<p>ada tiga ratus tiga sampel kemudian kita menghapus enam sampel yang memiliki <code>NA</code>, dan setelah menghapus sampel tersebut ada dua ratus sembilan puluh tujuh sampel yang tersisa.</p>
<p>Sekarang kita perlu memastikan bahwa sampel yang sehat dan berpenyakit berasal dari setiap jenis kelamin perempuan dan laki-laki.</p>
<p>jika hanya sampel laki-laki yang memiliki penyakit jantung, kita mungkin harus menghapus semua perempuan dari model tersebut.</p>
<p>kita melakukan ini dengan fungsi <code>xtabs</code> kita meneruskan <code>xtabs</code> data dan menggunakan sintaks model untuk memilih kolom dalam data yang ingin kita buat tabelnya. Dalam hal ini kita menginginkan tabel dengan penyakit jantung dan <code>sex</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> sex, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           sex
hd            F   M
  Healthy    71  89
  Unhealthy  25 112</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Most of the females are healthy and most of the males are unhealthy.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Being female is likely to decrease the odds in being unhealthy.</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="do">##    In other words, if a sample is female, the odds are against it that it</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="do">##    will be unhealthy</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Being male is likely to increase the odds in being unhealthy...</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="do">##    In other words, if a sample is male, the odds are for it being unhealthy</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>pasien sehat dan tidak sehat sama-sama diwakili oleh banyak sampel wanita dan pria singkatnya dilaporkan oleh sekelompok pasien.</p>
<div class="cell">
<pre class="shell cell-code"><code>## Most of the females are healthy and most of the males are unhealthy.
## Being female is likely to decrease the odds in being unhealthy.
##    In other words, if a sample is female, the odds are against it that it
##    will be unhealthy
## Being male is likely to increase the odds in being unhealthy...
##    In other words, if a sample is male, the odds are for it being unhealthy</code></pre>
</div>
<p>sekarang mari kita verifikasi bahwa keempat tingkat nyeri dada <code>CP</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Now we can do some quality control by making sure all of the factor</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="do">## levels are represented by people with and without heart disease (hd)</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="do">## </span><span class="al">NOTE</span><span class="do">: We also want to exclude variables that only have 1 or 2 samples in</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="do">## a category since +/- one or two samples can have a large effect on the</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="do">## odds/log(odds)</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> cp, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           cp
hd            1   2   3   4
  Healthy    16  40  65  39
  Unhealthy   7   9  18 103</code></pre>
</div>
</div>
<p>Kemudian kita melakukan hal yang sama untuk semua variabel <code>boolean</code> dan <code>categoric</code> yang kita gunakan untuk memprediksi penyakit jantung.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> fbs, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           fbs
hd            0   1
  Healthy   137  23
  Unhealthy 117  20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> restecg, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           restecg
hd           0  1  2
  Healthy   92  1 67
  Unhealthy 55  3 79</code></pre>
</div>
</div>
<p>Inilah sesuatu yang dapat menyebabkan masalah pada hasil istirahat elektrokardiografi. Hanya 4 pasien yang mewakili level 1, hal ini berpotensi menghalangi pencarian jalur yang paling pas (<em>fit</em>). Namun untuk saat ini kita hanya akan membiarkannya dan melihat apa yang terjadi dan kemudian kita terus melihat variabel yang tersisa untuk memastikan bahwa semuanya diwakili oleh sejumlah pasien.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> exang, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           exang
hd            0   1
  Healthy   137  23
  Unhealthy  63  74</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> slope, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           slope
hd            1   2   3
  Healthy   103  48   9
  Unhealthy  36  89  12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> ca, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           ca
hd            0   1   2   3
  Healthy   129  21   7   3
  Unhealthy  45  44  31  17</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> hd <span class="sc">+</span> thal, <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           thal
hd            3   6   7
  Healthy   127   6  27
  Unhealthy  37  12  88</code></pre>
</div>
</div>
<p>oke kita sudah melakukan semua hal yang membosankan sekarang mari kita lakukan regresi logistik mari kita mulai dengan model yang sangat sederhana.</p>
<p>kita akan mencoba memprediksi penyakit jantung hanya dengan menggunakan jenis kelamin setiap pasien. inilah <code>code call</code> kita ke fungsi GLM fungsi yang menjalankan <strong>G</strong>eneralized <strong>L</strong>inear <strong>M</strong>odels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(hd <span class="sc">~</span> sex, <span class="at">data=</span>data, <span class="at">family=</span><span class="st">"binomial"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>pertama kita menggunakan rumus sintaks untuk menentukan bahwa kita ingin menggunakan jenis kelamin untuk memprediksi penyakit jantung. Kita ingin menggunakan jenis kelamin untuk memprediksi penyakit jantung kemudian kita menentukan data yang kita gunakan untuk model tersebut. Terakhir kita menetapkan bahwa kita menginginkan keluarga binomial dari model linier umum, hal ini membuat fungsi GLM melakukan regresi logistik dibandingkan dengan beberapa jenis model linier umum lainnya.</p>
<p>Oh, saya hampir lupa menyebutkan bahwa kita menyimpan output dari fungsi GLM dalam variabel yang disebut logistic. kita kemudian menggunakan fungsi ringkasan untuk mendapatkan detail tentang regresi logistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = hd ~ sex, family = "binomial", data = data)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0438     0.2326  -4.488 7.18e-06 ***
sexM          1.2737     0.2725   4.674 2.95e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 409.95  on 296  degrees of freedom
Residual deviance: 386.12  on 295  degrees of freedom
AIC: 390.12

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## The intercept is the log(odds) a female will be unhealthy. This is because</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="do">## female is the first factor in "sex" (the factors are ordered,</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="do">## alphabetically by default,"female", "male")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>baris pertama memiliki panggilan asli ke fungsi GLM</li>
<li>baris kedua memberi ringkasan <code>deviance residuals</code>. mereka terlihat bagus karena hampir berpusat pada nol dan kira-kira simetris .</li>
</ol>
<p>jika Anda ingin tahu lebih banyak tentang <code>deviance residuals</code>, lihat modul <a href="devianceresidual.qmd">deviance residuals</a> yang dijelaskan dengan jelas.</p>
<ul>
<li>kemudian kita memiliki koefisien. Mereka bersesuaiaian dengan model.</li>
</ul>
<p><span class="math display">\[
\text{heart disease} = -1.0438 + 1.2737 \times \text{pasien laki-laki}
\]</span> Variabel pasien laki-laki sama dengan nol ketika pasien perempuan dan satu ketika pasien laki-laki.</p>
<ul>
<li>jadi jika kita memprediksi penyakit jantung untuk pasien wanita kita. kita mendapatkan persamaan berikut.</li>
</ul>
<p><span class="math display">\[
\text{heart disease} = -1.0438 + 1.2737 \times 0 = -1.0438
\]</span> Oleh karena itu, kemungkinan log (odds) bahwa seorang wanita memiliki penyakit jantung $ = -1.0438 $.</p>
<p>jika kita memprediksi penyakit jantung untuk pasien laki-laki, kita mendapatkan persamaan berikut <span class="math display">\[
\text{heart disease} = -1.0438 + 1.2737 \times 1 = -1.0438 + 1.2737
\]</span> karena persamaan pertama adalah log(odds) seorang wanita terkena penyakit jantung, persamaan kedua menunjukkan peningkatan log(odds) seorang pria terkena penyakit jantung.</p>
<p>Dengan kata lain, suku persamaan kedua adalah log <strong>rasio</strong> peluang seorang <strong>pria</strong> terkena penyakit jantung terhadap kemungkinan seorang <strong>wanita</strong> terkena penyakit jantung.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>female.log.odds <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">25</span> <span class="sc">/</span> <span class="dv">71</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>female.log.odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.043804</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>female.log.odds <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">25</span> <span class="sc">/</span> <span class="dv">71</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>female.log.odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.043804</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="do">## sexM is the log(odds ratio) that tells us that if a sample has sex=M, the</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="do">## odds of being unhealthy are, on a log scale, 1.27 times greater than if</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="do">## a sample has sex=F.</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>male.log.odds.ratio <span class="ot">&lt;-</span> <span class="fu">log</span>((<span class="dv">112</span> <span class="sc">/</span> <span class="dv">89</span>) <span class="sc">/</span> (<span class="dv">25</span><span class="sc">/</span><span class="dv">71</span>))</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>male.log.odds.ratio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.273667</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = hd ~ sex, family = "binomial", data = data)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0438     0.2326  -4.488 7.18e-06 ***
sexM          1.2737     0.2725   4.674 2.95e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 409.95  on 296  degrees of freedom
Residual deviance: 386.12  on 295  degrees of freedom
AIC: 390.12

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Bagian <code>Std. Error</code> dan <code>z Value</code> dari keluaran regresi logistik ini menunjukkan bagaimana <strong>Wald</strong> dihitung untuk kedua koefisien dan ini adalah <code>P-Value</code>.</li>
</ol>
<p>kedua <code>P-Value</code> jauh di bawah 0,05 dan dengan demikian <code>log(odds)</code> dan <code>log(odds_ratio)</code> keduanya <strong>signifikan secara statistik</strong> tetapi ingat <code>P-Value</code> yang kecil saja tidak <em>menentukan</em>.</p>
<p>kita juga menginginkan ukuran <strong>efek</strong> yang besar dan itulah yang dikatakan oleh <code>log(odds)</code> dan <code>log(odds_ratio)</code>.</p>
<p>Jika Anda ingin mengetahui detail lebih lanjut tentang</p>
<ul>
<li><code>koefisien</code> dan <code>uji Wald</code>, lihat <a href="regresilogistic.qmd">modul</a> berikut dan</li>
<li><code>log(odds)</code> dijelaskan dengan jelas - <a href="regresilogistic.qmd"><code>odds_ratio</code></a> dan</li>
<li><code>log(odds_ratio)</code> dijelaskan dengan jelas dalam detail <a href="regresilogistic.qmd">regresi logistik bagian 1</a>.</li>
</ul>
<ol start="4" type="1">
<li>selanjutnya kita melihat parameter dispersi default yang digunakan untuk regresi logistik ini.</li>
</ol>
<p>Ketika kita melakukan regresi linier sederhana, kita memperkirakan mean dan varians dari data yang berbeda.</p>
<p>Secara kontras, ketika regresi logistik kita memperkirakan rata-rata data sedangkan varians diturunkan dari mean. Karena kita tidak memperkirakan varians dari data dan sebaliknya hanya menurunkannya dari mean ada kemungkinan varians tersebut <code>underestimated</code>. Kalau begitu, Anda dapat menyesuaikan dispersi kita di dalam <code>summary</code> command.</p>
<ol start="5" type="1">
<li>Kita memiliki <code>Null deviance</code> dan <code>Residual Deviance</code>. Ini dapat digunakan untuk membandingkan model yang menghitung <code>$R^2$</code> dan keseluruhan <code>p-value</code>.</li>
</ol>
<p>untuk detail lebih lanjut, lihat detail <a href="regresilogistic.qmd">regresi logistik</a> <code>$R^2$</code> dan <code>p-value</code>-nya dan <a href="regresilogistic.qmd">Saturated Models dan Deviance Statistics</a> dijelaskan dengan jelas.</p>
<ol start="6" type="1">
<li><p>kemudian kita memiliki AIC (Akaike Information Criterion) yang dalam konteks ini hanyalah <code>Residual Deviance</code> yang <strong>disesuaikan</strong> dengan jumlah parameter dalam model. <strong>AIC</strong> dapat digunakan untuk membandingkan satu model dengan model lainnya.</p></li>
<li><p>terakhir, kita memiliki <code>Number of Fisher Scoring Iteration</code> yang hanya memberi tahu kita seberapa cepat fungsi <code>GLM</code> <em>coverge</em> pada <strong>Maximum Likelihood Estimates</strong> untuk koefisien.</p></li>
</ol>
<p>jika Anda ingin detail lebih lanjut tentang bagaimana koefisien diestimasi, lihat detail <a href="logisticregression.qmd">regresi logistik bagian kedua</a> <strong>…menyesuaikan garis dengan kemungkinan maksimum</strong>.</p>
<p>sekarang kita telah melakukan regresi logistik sederhana hanya dengan menggunakan salah satu variabel (<strong><code>sex</code></strong>) untuk memprediksi penyakit jantung, kita dapat membuat model <em>fancy</em> yang menggunakan semua variabel untuk memprediksi penyakit jantung sintaks dengan rumus ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="do">#####################################</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Now we will use all of the data available to predict heart disease</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="do">#####################################</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(hd <span class="sc">~</span> ., <span class="at">data=</span>data, <span class="at">family=</span><span class="st">"binomial"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong><code>.</code></strong> berarti kita ingin memodelkan HD penyakit jantung menggunakan semua variabel dalam data frame kita yang disebut data, kita kemudian dapat melihat seperti apa model kita dengan fungsi <code>summary</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = hd ~ ., family = "binomial", data = data)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -6.253978   2.960399  -2.113 0.034640 *  
age         -0.023508   0.025122  -0.936 0.349402    
sexM         1.670152   0.552486   3.023 0.002503 ** 
cp2          1.448396   0.809136   1.790 0.073446 .  
cp3          0.393353   0.700338   0.562 0.574347    
cp4          2.373287   0.709094   3.347 0.000817 ***
trestbps     0.027720   0.011748   2.359 0.018300 *  
chol         0.004445   0.004091   1.087 0.277253    
fbs1        -0.574079   0.592539  -0.969 0.332622    
restecg1     1.000887   2.638393   0.379 0.704424    
restecg2     0.486408   0.396327   1.227 0.219713    
thalach     -0.019695   0.011717  -1.681 0.092781 .  
exang1       0.653306   0.447445   1.460 0.144267    
oldpeak      0.390679   0.239173   1.633 0.102373    
slope2       1.302289   0.486197   2.679 0.007395 ** 
slope3       0.606760   0.939324   0.646 0.518309    
ca1          2.237444   0.514770   4.346 1.38e-05 ***
ca2          3.271852   0.785123   4.167 3.08e-05 ***
ca3          2.188715   0.928644   2.357 0.018428 *  
thal6       -0.168439   0.810310  -0.208 0.835331    
thal7        1.433319   0.440567   3.253 0.001141 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 409.95  on 296  degrees of freedom
Residual deviance: 183.10  on 276  degrees of freedom
AIC: 225.1

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>kita melihat bahwa usia bukanlah prediktor yang berguna karena memiliki <code>p-value</code> yang <strong>besar</strong>. Namun <code>rata-rata</code> usia dalam dataframe kita adalah <span class="math inline">\(56\)</span> tahun. Jadi sebagian besar orang sudah cukup tua dan itu menjelaskan mengapa usia tidak terlalu <strong>berguna</strong>.</p>
<p><code>Gender</code> masih merupakan prediktor yang <strong>baik</strong>. Meskipun begitu, kita melihat bahwa <code>residual deviance</code> dan <code>AIC</code> keduanya jauh lebih <strong>kecil</strong> untuk model <em>fancy</em> ini daripada fungsi untuk model sederhana yakni ketika kita hanya menggunakan <strong>jenis kelamin</strong> untuk memprediksi <strong>penyakit jantung</strong>.</p>
<p>jika kita ingin menghitung <strong>pseudo r-squared McFadden</strong>, kita dapat mengambil <strong>log-likelihood null model</strong> dari variabel <strong>logistik</strong>, dengan mendapatkan nilai <strong>null deviance</strong> dan membaginya dengan <span class="math inline">\(-2\)</span>,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Now calculate the overall "Pseudo R-squared" and its p-value</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="do">## </span><span class="al">NOTE</span><span class="do">: Since we are doing logistic regression...</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Null devaince = 2*(0 - LogLikelihood(null model))</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="do">##               = -2*LogLikihood(null model)</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Residual deviacne = 2*(0 - LogLikelihood(proposed model))</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="do">##                   = -2*LogLikelihood(proposed model)</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>ll.null <span class="ot">&lt;-</span> logistic<span class="sc">$</span>null.deviance<span class="sc">/-</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>dan kita dapat mengambil <strong>log-likelihood null model</strong> untuk model <em>fancy</em> dari variabel <strong>logistik</strong> dengan mendapatkan nilai <strong>residual deviance</strong> dan membaginya dengan <span class="math inline">\(-2\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Now calculate the overall "Pseudo R-squared" and its p-value</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="do">## </span><span class="al">NOTE</span><span class="do">: Since we are doing logistic regression...</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Null devaince = 2*(0 - LogLikelihood(null model))</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="do">##               = -2*LogLikihood(null model)</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Residual deviacne = 2*(0 - LogLikelihood(proposed model))</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="do">##                   = -2*LogLikelihood(proposed model)</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>ll.proposed <span class="ot">&lt;-</span> logistic<span class="sc">$</span>deviance<span class="sc">/-</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>kemudian kita hanya menghitung dan kita mendapatkan <strong>pseudo r-squared McFadden</strong> <span class="math inline">\(= 0,55\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## McFadden's Pseudo R^2 = [ LL(Null) - LL(Proposed) ] / LL(Null)</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>(ll.null <span class="sc">-</span> ll.proposed) <span class="sc">/</span> ll.null</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5533531</code></pre>
</div>
</div>
<p>ini dapat diartikan sebagai ukuran <strong><code>efek</code> keseluruhan</strong> dan kita dapat menggunakan <strong>log-likelihood</strong> yang sama untuk menghitung <code>p-value</code> untuk <code>$R^2$</code> tersebut menggunakan distribusi <strong>Chi-Square</strong> dalam hal ini <code>p-value</code> kecil sehingga nilai <code>$R^2$</code> bukan karena keberuntungan yang bodoh.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="do">## chi-square value = 2*(LL(Proposed) - LL(Null))</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="do">## The p-value for the R^2</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span><span class="sc">*</span>(ll.proposed <span class="sc">-</span> ll.null), <span class="at">df=</span>(<span class="fu">length</span>(logistic<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>((logistic<span class="sc">$</span>null.deviance <span class="sc">-</span> logistic<span class="sc">$</span>deviance), <span class="at">df=</span>(<span class="fu">length</span>(logistic<span class="sc">$</span>coefficients)<span class="sc">-</span><span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value = 1 - pchisq(chi-square value, df = 2-1)</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="co">#1 - pchisq(2*(ll.proposed - ll.null), df=1)</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co">#1 - pchisq((logistic$null.deviance - logistic$deviance), df=1)</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Lastly, let's  see what this logistic regression predicts, given</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="do">## that a patient is either female or male (and no other data about them).</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>predicted.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability.of.hd=</span>logistic<span class="sc">$</span>fitted.values,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex=</span>data<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Detail lebih lanjut tentang <code>$R^2$</code> dan <code>p-value</code> dapat ditemukan di <a href="regresilogistic.qmd">logistic regression details</a> bagian <code>$R^2$</code> dan <code>p-value</code>.</p>
<p>Terakhir kita dapat menggambar grafik yang menunjukkan probabilitas yang diprediksi bahwa setiap pasien memiliki penyakit jantung seiring dengan status penyakit jantung yang mereka miliki.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="do">## We can plot the data...</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>predicted.data, <span class="fu">aes</span>(<span class="at">x=</span>sex, <span class="at">y=</span>probability.of.hd)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>sex), <span class="at">size=</span><span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Sex"</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Predicted probability of getting heart disease"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul6_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Since there are only two probabilities (one for females and one for males),</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="do">## we can use a table to summarize the predicted probabilities.</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> probability.of.hd <span class="sc">+</span> sex, <span class="at">data=</span>predicted.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     sex
probability.of.hd     F M
  0.00109849687364516 1 0
  0.00257595371589279 1 0
  0.00302860987165499 1 0
  0.00309742157453941 1 0
  0.00316552701639565 1 0
  0.0036173662362176  1 0
  0.00424728930168456 1 0
  0.004252341397993   1 0
  0.00458417821874386 1 0
  0.0055715691281947  1 0
  0.00612498312810293 1 0
  0.00732920502686092 1 0
  0.00798129825868711 1 0
  0.00821700650426802 1 0
  0.00835492978391896 1 0
  0.0090345742813764  1 0
  0.0102421214716949  1 0
  0.0110000338134468  1 0
  0.0113857038790058  0 1
  0.0119829653935482  1 0
  0.0129839840898876  1 0
  0.0132010374672948  1 0
  0.0141501041600713  0 1
  0.0144510378661266  0 1
  0.0145542087033473  0 1
  0.0150339481250764  1 0
  0.0158412350206649  0 1
  0.0158757921057526  1 0
  0.0163581355975179  0 1
  0.016419911634928   0 1
  0.0167460183841822  0 1
  0.0190015918666313  1 0
  0.0190266058956531  1 0
  0.0194413243424079  1 0
  0.0212397745714133  0 1
  0.0229666682951821  0 1
  0.0234657185428947  0 1
  0.0236604112915081  1 0
  0.0238167919846595  1 0
  0.0249489781010545  1 0
  0.0250971117932175  0 1
  0.0262539988650925  1 0
  0.0285145909079672  1 0
  0.0286625790957844  1 0
  0.0287950230604837  0 1
  0.03037420675039    1 0
  0.0309572735380999  1 0
  0.0311566200786876  0 1
  0.0314432385823954  0 1
  0.0336251680707966  0 1
  0.0355198593538869  0 1
  0.0366238014259639  0 1
  0.0367647167117863  1 0
  0.0386514722522503  0 1
  0.0391214089398116  1 0
  0.0410922083688951  0 1
  0.041439655434854   1 0
  0.0430109609043515  1 0
  0.04367053603076    1 0
  0.0437225372526803  1 0
  0.0440712130839445  1 0
  0.0452121237382874  1 0
  0.0465775926224517  0 1
  0.0490190635751614  0 1
  0.0491266441808808  0 1
  0.0508426014065071  1 0
  0.0508810224168613  1 0
  0.0514768857230768  0 1
  0.052258068609248   0 1
  0.0523329737612425  0 1
  0.0558810524873025  0 1
  0.056834143513995   0 1
  0.0573839959190046  0 1
  0.0583873956994075  0 1
  0.0587245196686592  1 0
  0.0598220299171169  0 1
  0.062099415895352   0 1
  0.0622084822411599  0 1
  0.0644149704119884  0 1
  0.0663940933217283  1 0
  0.0663993133043969  1 0
  0.066924128810457   0 1
  0.0799839139207208  1 0
  0.0896929021776774  1 0
  0.091311778029208   0 1
  0.0924348053526441  1 0
  0.0961869627789141  1 0
  0.096559426661432   0 1
  0.104585965563636   0 1
  0.105461312926022   0 1
  0.110839079905231   0 1
  0.110915898255908   0 1
  0.111011538132575   1 0
  0.113609757343521   0 1
  0.114492942195124   0 1
  0.116842845453753   0 1
  0.124269406166327   0 1
  0.126544057761247   1 0
  0.130489782221405   0 1
  0.138707035572436   1 0
  0.139632265793722   0 1
  0.140838233391067   1 0
  0.142744928155097   1 0
  0.142803306424549   0 1
  0.145321481619698   1 0
  0.154759366190523   0 1
  0.157514867215368   0 1
  0.158988022312673   0 1
  0.160933162511404   1 0
  0.161325645912614   0 1
  0.163686615140895   0 1
  0.16891743464227    1 0
  0.182860431522722   0 1
  0.187798107412366   1 0
  0.207789639077226   0 1
  0.209015413260763   1 0
  0.212072900541564   0 1
  0.214730318385278   1 0
  0.222771394627878   0 1
  0.224006063963778   1 0
  0.227745780140376   1 0
  0.228054267741691   0 1
  0.239284007626666   0 1
  0.241638846352508   0 1
  0.248886621454535   0 1
  0.250309803525568   1 0
  0.254486059487984   0 1
  0.260147992666944   1 0
  0.260211313582116   0 1
  0.270926284230502   0 1
  0.273754102353528   0 1
  0.274486678472416   0 1
  0.277710691706252   0 1
  0.278686451963224   1 0
  0.280420159791897   0 1
  0.28213252291425    1 0
  0.284808944916844   0 1
  0.288415392116847   0 1
  0.290319802806465   1 0
  0.290656356340781   0 1
  0.306943077761505   0 1
  0.311482759100001   0 1
  0.312001019774412   1 0
  0.321379987652644   0 1
  0.324438352928596   1 0
  0.348367591872858   1 0
  0.352439406579044   1 0
  0.361345491709285   0 1
  0.365212639286825   0 1
  0.367992856225714   1 0
  0.368698797256461   1 0
  0.37667186598856    0 1
  0.377552339146292   0 1
  0.381366127903862   0 1
  0.382113408855146   0 1
  0.38673600054482    0 1
  0.38706254718615    1 0
  0.391477771446765   0 1
  0.399258886071222   0 1
  0.422661163229807   0 1
  0.432020604805412   0 1
  0.438010086324275   0 1
  0.445261104770905   0 1
  0.450309481745517   0 1
  0.450534711787278   1 0
  0.451753243490256   0 1
  0.469440882870818   0 1
  0.475457614278839   0 1
  0.47943697237974    0 1
  0.480560386782782   0 1
  0.492615945542668   0 1
  0.509159663847104   0 1
  0.52277745210901    0 1
  0.541141848438452   0 1
  0.544980767718397   0 1
  0.545109373133998   0 1
  0.545390099142261   0 1
  0.546140317975364   0 1
  0.547420365803636   0 1
  0.570442122864816   0 1
  0.578952477298274   0 1
  0.631198562161651   0 1
  0.647739412692096   0 1
  0.658242621846726   0 1
  0.684782513929224   1 0
  0.687452168310232   0 1
  0.70248880783581    0 1
  0.705874158517764   0 1
  0.708644163082159   0 1
  0.717750550408683   0 1
  0.719224535252244   1 0
  0.72005769588199    0 1
  0.728266034396439   1 0
  0.750503476070541   0 1
  0.751145818144816   0 1
  0.754971450824077   0 1
  0.770892650822427   0 1
  0.775235459955928   0 1
  0.796637679798201   1 0
  0.800662839378138   0 1
  0.806879666034612   1 0
  0.811489542804712   1 0
  0.81216422254804    0 1
  0.813179938467691   0 1
  0.813804721189549   0 1
  0.824574972085284   0 1
  0.826936305100827   0 1
  0.845142336159083   0 1
  0.849972280247194   0 1
  0.853137161783436   0 1
  0.856640939423002   0 1
  0.865310778796839   0 1
  0.866587227490961   0 1
  0.880856759614595   0 1
  0.888731337279975   1 0
  0.889990950377614   0 1
  0.894275652973582   0 1
  0.898795127851473   0 1
  0.900556819701189   0 1
  0.913251802637605   1 0
  0.916958660271168   0 1
  0.920857416507447   0 1
  0.922972892897101   0 1
  0.923564289790845   0 1
  0.925103473375611   0 1
  0.92538048837472    1 0
  0.926670249647006   0 1
  0.932562076418011   0 1
  0.940551673245513   0 1
  0.941739080251273   0 1
  0.943991082194031   0 1
  0.954226066930809   0 1
  0.954699941321568   0 1
  0.954869282725921   0 1
  0.957285535359092   0 1
  0.958591574115299   0 1
  0.962311675299815   0 1
  0.962665557808326   1 0
  0.964616179254019   1 0
  0.967083158492448   0 1
  0.972585443725781   0 1
  0.973118236613765   0 1
  0.974849358728931   0 1
  0.974864179016031   1 0
  0.975154296989085   0 1
  0.975923511872864   0 1
  0.976316797250771   0 1
  0.976863952714786   1 0
  0.980524845402496   0 1
  0.981052201584332   0 1
  0.98129752479769    0 1
  0.981593207229319   0 1
  0.981856493751978   0 1
  0.982652584859067   0 1
  0.983817695154674   1 0
  0.984232291394245   1 0
  0.984513939155071   0 1
  0.985418186890805   0 1
  0.986597517143917   0 1
  0.986804485638748   0 1
  0.986878593097864   0 1
  0.987235288448108   0 1
  0.987553136341569   0 1
  0.988237660078016   1 0
  0.988632504331469   0 1
  0.989466670937826   0 1
  0.989498212732539   1 0
  0.990420853263466   0 1
  0.990686567185108   0 1
  0.992386273612647   0 1
  0.993102290185761   0 1
  0.993376136192944   0 1
  0.993471762504122   0 1
  0.993897346285488   0 1
  0.994017714835227   0 1
  0.994109137892823   0 1
  0.994384275170445   0 1
  0.994429272052204   0 1
  0.994568332042835   0 1
  0.994621317393877   0 1
  0.994884640329228   1 0
  0.994921517669052   0 1
  0.995593851495599   0 1
  0.996285859662292   0 1
  0.996938268641653   0 1
  0.997135274510168   0 1
  0.997439675632816   0 1
  0.997935717327889   0 1
  0.99805927561475    0 1
  0.99809095901409    0 1
  0.998313153430203   0 1
  0.998418346757509   1 0
  0.998657002941138   0 1
  0.998862240850775   0 1
  0.998977158173268   0 1
  0.99906284448998    0 1
  0.999172369060652   0 1</code></pre>
</div>
</div>
<p>Sebagian besar pasien dengan penyakit jantung yang ada di warna <strong>Turqoise</strong> diprediksi memiliki kemungkinan Tinggi terkena penyakit jantung &amp; Sebagian besar pasien tanpa penyakit jantung yang ada di <strong>salmon</strong> diprediksi memiliki kemungkinan rendah terkena penyakit jantung sehingga regresi logistik kita telah melakukan pekerjaan yang cukup baik.</p>
<p>Namun, kita dapat menggunakan <strong>cross validation</strong> untuk mendapatkan ide yang lebih baik tentang seberapa baik kinerjanya dengan data baru. Tetapi kita akan menyimpannya untuk kesempatan lain.</p>
<ul>
<li>Untuk menggambar grafik kita mulai dengan membuat data frame baru yang berisi probabilitas terkena penyakit jantung bersama dengan status penyakit jantung yang sebenarnya.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="do">## now we can plot the data</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>predicted.data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability.of.hd=</span>logistic<span class="sc">$</span>fitted.values,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">hd=</span>data<span class="sc">$</span>hd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>kemudian kita mengurutkan data frame dari probabilitas rendah ke tinggi probabilitas</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>predicted.data <span class="ot">&lt;-</span> predicted.data[</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">order</span>(predicted.data<span class="sc">$</span>probability.of.hd, <span class="at">decreasing=</span><span class="cn">FALSE</span>),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>kemudian kita tambahkan kolom baru ke data frame yang memiliki <strong>rank</strong> masing-masing sampel, dari probabilitas rendah ke probabilitas tinggi</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>predicted.data<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(predicted.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>kemudian kita memuat library <code>**ggplot2**</code> sehingga kita dapat menggambar grafik yang bagus</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>kemudian kita memuat library <code>**cowplot**</code> sehingga<code>**ggplot2**</code> memiliki tampilan yang bagus secara defaults</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>kemudian kita memanggil <code>ggplot()</code> dan menggunakan <code>geom_point()</code> untuk menggambar data dan</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Lastly, we can plot the predicted probabilities for each sample having</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="do">## heart disease and color by whether or not they actually had heart disease</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>predicted.data, <span class="fu">aes</span>(<span class="at">x=</span>rank, <span class="at">y=</span>probability.of.hd)) <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>hd), <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">shape=</span><span class="dv">4</span>, <span class="at">stroke=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Index"</span>) <span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Predicted probability of getting heart disease"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul6_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>terakhir kita memanggil <code>ggsave()</code> untuk menyimpan grafik sebagai file PDF triple.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"heart_disease_probabilities.pdf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>