{
  "hash": "5980963846a6ebd7e492c184245a3177",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modul 3: R - Statistik Deskriptif dan Visualisasi Frekuensi\"\nsubtitle: \"Studi Kasus: Analisis Dataset Bunga Iris\"\nauthor: \"Tim Asisten Lab Matematika UI\"\ndate: \"2025-09-11\"\n---\n\n\n\n<a href=\"../psd2025.qmd\" class=\"btn btn-outline-primary mb-4\">\n<i class=\"fa-solid fa-arrow-left\"></i> Kembali ke Arsip Praktikum PSD 2025\n</a>\n\n## Tujuan Pembelajaran\n\nSetelah menyelesaikan modul ini, mahasiswa diharapkan mampu:\n\n* **1. Melakukan Operasi Dasar R**\n    * Menggunakan R untuk operasi aritmatika dan logika.\n    * Memahami dan membuat objek dasar di R, yaitu *vector*.\n\n* **2. Mengelola Data di RStudio**\n    * Mengimpor *dataset* dari file `.csv` ke dalam R sebagai sebuah *data frame*.\n    * Melakukan inspeksi dasar pada *data frame* untuk memahami struktur dan isinya.\n    * Memfilter (*subsetting*) data berdasarkan kriteria tertentu.\n\n* **3. Menganalisis dan Memvisualisasikan Data**\n    * Menghitung statistik deskriptif dasar (mean, median, min, max, standar deviasi).\n    * Membuat tabel frekuensi untuk data kategorik.\n    * Membuat visualisasi frekuensi yang sesuai dengan tipe datanya (*bar chart*, *pie chart*, *histogram*).\n\n---\n\n## 1. Skenario: Misteri Bunga Iris 🕵️\n\nSelamat datang kembali! Di modul sebelumnya, kita sudah berhasil menyiapkan \"bengkel\" kerja kita. Sekarang, saatnya menggunakan alat-alat tersebut untuk memecahkan kasus pertama kita.\n\nSeorang botanis (ahli tumbuhan) datang kepada kita dengan *dataset* berisi pengukuran 150 bunga Iris. Data ini terdiri dari tiga spesies berbeda. Sang botanis punya beberapa pertanyaan:\n1.  \"Apa karakteristik umum dari data yang saya kumpulkan ini?\"\n2.  \"Apakah ada spesies yang cenderung memiliki kelopak (*sepal*) yang lebih panjang dibandingkan yang lain?\"\n\nTugas kita adalah menggunakan R untuk **mengeksplorasi data, menghitung statistik dasar, dan membuat visualisasi** untuk menjawab pertanyaan-pertanyaan tersebut.\n\n:::{.callout-note}\n\n### Tentang Dataset `iris`\n*Dataset* `iris` adalah data klasik dalam dunia statistika, berisi pengukuran empat fitur (panjang & lebar kelopak dan mahkota bunga) dari tiga spesies Iris. *Dataset* ini sudah tersedia secara *built-in* di R, jadi kita bisa langsung menggunakannya.\n\n:::\n\n---\n\n## 2. Pemanasan: Operasi Dasar & *Vector*\n\nSebelum membedah *dataset* `iris`, mari kita hangatkan jari kita dengan beberapa operasi dasar yang akan sering kita gunakan.\n\n### 2.1. Aritmatika dan Variabel\n\nSeperti yang kita pelajari di modul pertama, R bisa berfungsi sebagai kalkulator. Kita juga bisa menyimpan hasil perhitungan dalam variabel menggunakan `<-`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Operasi dasar\n2 * (5 + 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Menyimpan hasil ke variabel\nlebar_kelopak <- 2.5\npanjang_kelopak <- 4.5\nluas_kelopak <- lebar_kelopak * panjang_kelopak\nluas_kelopak\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11.25\n```\n\n\n:::\n:::\n\n\n\n### 2.2. Vector: Menyimpan Kumpulan Data\n\nSaat menganalisis data, kita jarang bekerja dengan satu angka saja. Kita akan bekerja dengan sekumpulan data. Di R, cara paling dasar untuk menyimpan sekumpulan data adalah dengan **vector**, menggunakan fungsi `c()` (*combine*).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Vector berisi data numerik (lebar kelopak dari 3 bunga)\nkumpulan_lebar <- c(2.5, 3.1, 2.8)\nkumpulan_lebar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.5 3.1 2.8\n```\n\n\n:::\n\n```{.r .cell-code}\n# Vector berisi data teks/karakter (nama spesies)\nkumpulan_spesies <- c(\"setosa\", \"versicolor\", \"virginica\")\nkumpulan_spesies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"setosa\"     \"versicolor\" \"virginica\" \n```\n\n\n:::\n:::\n\n\nSetiap kolom dalam sebuah tabel data di R pada dasarnya adalah sebuah *vector*.\n\n---\n\n## 3. Investigasi Data Iris\n\nSekarang kita siap untuk memulai investigasi. Mari kita muat dan periksa data `iris`.\n\n### 3.1. Memuat dan Melihat Data\n\n*Dataset* `iris` sudah tersedia di R. Kita cukup memanggilnya untuk melihatnya.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Memuat dataset (sebenarnya sudah aktif, tapi ini cara memastikannya)\ndata(\"iris\")\n\n# Melihat 6 baris pertama dari data\nhead(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n4          4.6         3.1          1.5         0.2  setosa\n5          5.0         3.6          1.4         0.2  setosa\n6          5.4         3.9          1.7         0.4  setosa\n```\n\n\n:::\n:::\n\n\n\nUntuk mendapatkan gambaran umum tentang struktur data, gunakan `str()` (*structure*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Melihat struktur data: jumlah baris, kolom, nama kolom, dan tipe datanya\nstr(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t150 obs. of  5 variables:\n $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...\n $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...\n $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...\n $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...\n $ Species     : Factor w/ 3 levels \"setosa\",\"versicolor\",..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nDari sini kita tahu ada 150 observasi, 5 kolom, dan tipe datanya adalah numerik (`num`) dan kategorik (`Factor` untuk Spesies).\n\n### 3.2. Menjawab Pertanyaan 1: Statistik Deskriptif\n\nUntuk menjawab pertanyaan pertama botanis (\"Apa karakteristik umum dari data ini?\"), kita bisa menggunakan statistik deskriptif.\n\n* **Ringkasan Cepat**: Gunakan fungsi `summary()` untuk mendapatkan ringkasan statistik (Min, Median, Mean, Max, Kuartil) untuk setiap kolom numerik.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   \n Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  \n 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  \n Median :5.800   Median :3.000   Median :4.350   Median :1.300  \n Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  \n 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  \n Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  \n       Species  \n setosa    :50  \n versicolor:50  \n virginica :50  \n                \n                \n                \n```\n\n\n:::\n:::\n\n\n* **Perhitungan Spesifik**: Anda juga bisa menghitung statistik satu per satu. Untuk mengakses satu kolom, gunakan simbol `$`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rata-rata panjang kelopak (Sepal.Length)\nmean(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.843333\n```\n\n\n:::\n\n```{.r .cell-code}\n# Standar deviasi panjang kelopak\nsd(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8280661\n```\n\n\n:::\n\n```{.r .cell-code}\n# Nilai minimum dan maksimum\nmin(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(iris$Sepal.Length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.9\n```\n\n\n:::\n:::\n\n\nIni memberikan kita gambaran umum yang bagus tentang rentang dan pusat data kita.\n\n### 3.3. Menjawab Pertanyaan 2: Perbandingan Spesies\n\nSekarang pertanyaan kedua: \"Apakah ada spesies yang cenderung memiliki kelopak (*sepal*) yang lebih panjang?\" Untuk menjawab ini, kita perlu **memfilter** data dan **memvisualisasikannya**.\n\n#### Memfilter Data\nKita ingin melihat data hanya untuk spesies tertentu atau untuk bunga dengan kriteria tertentu. Gunakan fungsi `subset()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Membuat data frame baru yang hanya berisi spesies 'virginica'\niris_virginica <- subset(iris, Species == \"virginica\")\n\n# Melihat 6 baris pertama dari data baru kita\nhead(iris_virginica)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species\n101          6.3         3.3          6.0         2.5 virginica\n102          5.8         2.7          5.1         1.9 virginica\n103          7.1         3.0          5.9         2.1 virginica\n104          6.3         2.9          5.6         1.8 virginica\n105          6.5         3.0          5.8         2.2 virginica\n106          7.6         3.0          6.6         2.1 virginica\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Membuat data frame baru yang hanya berisi bunga dengan Sepal.Length > 7.0\niris_panjang <- subset(iris, Sepal.Length > 7.0)\n\n# Melihat hasilnya\niris_panjang\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species\n103          7.1         3.0          5.9         2.1 virginica\n106          7.6         3.0          6.6         2.1 virginica\n108          7.3         2.9          6.3         1.8 virginica\n110          7.2         3.6          6.1         2.5 virginica\n118          7.7         3.8          6.7         2.2 virginica\n119          7.7         2.6          6.9         2.3 virginica\n123          7.7         2.8          6.7         2.0 virginica\n126          7.2         3.2          6.0         1.8 virginica\n130          7.2         3.0          5.8         1.6 virginica\n131          7.4         2.8          6.1         1.9 virginica\n132          7.9         3.8          6.4         2.0 virginica\n136          7.7         3.0          6.1         2.3 virginica\n```\n\n\n:::\n:::\n\n\nDengan memfilter, kita bisa melihat bahwa bunga dengan kelopak sangat panjang mayoritas adalah spesies `virginica`.\n\n#### Visualisasi Frekuensi\nCara terbaik untuk membandingkan adalah dengan visualisasi. Mari kita lihat distribusi frekuensi dari data kita.\n\n* **Tabel Frekuensi**: Pertama, kita hitung ada berapa bunga untuk setiap spesies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabel_spesies <- table(iris$Species)\ntabel_spesies\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    setosa versicolor  virginica \n        50         50         50 \n```\n\n\n:::\n:::\n\n\n\n* **Bar Chart**: Visualisasi ini paling cocok untuk membandingkan jumlah antar kategori.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(tabel_spesies, \n        main = \"Distribusi Spesies Bunga Iris\",\n        xlab = \"Spesies\",\n        ylab = \"Jumlah Bunga\",\n        col = c(\"skyblue\", \"salmon\", \"lightgreen\"))\n```\n\n::: {.cell-output-display}\n![](modul-03_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n    Dari sini terlihat bahwa jumlah data untuk setiap spesies sama (50).\n\n* **Histogram**: Untuk melihat distribusi data numerik seperti `Sepal.Length`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(iris$Sepal.Length,\n     main = \"Distribusi Panjang Kelopak (Sepal)\",\n     xlab = \"Panjang Kelopak (cm)\",\n     ylab = \"Frekuensi\",\n     col = \"lavender\")\n```\n\n::: {.cell-output-display}\n![](modul-03_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n    Histogram ini menunjukkan bahwa mayoritas bunga memiliki panjang kelopak antara 5.5 dan 6.5 cm.\n\n### Kesimpulan Investigasi\n\nDengan analisis singkat ini, kita bisa kembali ke sang botanis dengan jawaban:\n1.  Karakteristik umum data menunjukkan panjang kelopak (Sepal) berkisar antara 4.3 hingga 7.9 cm, dengan rata-rata 5.84 cm.\n2.  Ya, ada spesies yang cenderung memiliki kelopak lebih panjang. Data menunjukkan bahwa bunga dengan panjang kelopak di atas 7 cm hampir seluruhnya adalah spesies `virginica`.\n\n### Latihan\n\n1.  Hitung **rata-rata** `Petal.Length` (panjang mahkota) untuk spesies `setosa` saja. (Gunakan `subset()` terlebih dahulu).\n2.  Buatlah **histogram** untuk variabel `Petal.Width` (lebar mahkota). Beri judul dan warna yang sesuai.\n\n---\n\n### Lampiran: Impor Data dari File Lokal\n\nDi dunia nyata, data tidak selalu ada di dalam R. Seringkali Anda akan mendapatkannya dalam bentuk file `.csv` atau `.xlsx`.\n\n:::{.panel-tabset}\n\n#### Impor dari `.csv`\nUntuk mengimpor file `.csv`, Anda perlu *library* `readr`.\n```r\n# install.packages(\"readr\") # Jalankan sekali jika belum terinstal\nlibrary(readr)\n\n# Misalkan file Iris.csv ada di folder data\ndata_csv <- read_csv(\"data/Iris.csv\")\n```\n\n#### Impor dari `.xlsx`\nUntuk mengimpor file Excel, Anda perlu *library* `readxl`.\n```r\n# install.packages(\"readxl\") # Jalankan sekali jika belum terinstal\nlibrary(readxl)\n\n# Misalkan file Iris.xlsx ada di folder data\ndata_excel <- read_excel(\"data/Iris.xlsx\")\n```\n:::\n\n---\n\n<a href=\"../psd2025.qmd\" class=\"btn btn-outline-primary mb-4\">\n<i class=\"fa-solid fa-arrow-left\"></i> Kembali ke Arsip Praktikum PSD\n</a>",
    "supporting": [
      "modul-03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}