# Tugas Akhir

Kembali ke [Persamaan Diferensial Numerik](../pdnum2023.qmd)

Tulisan di bawah ini adalah salinan dari: [https://linevoom.line.me/post/1168595921012325899](https://linevoom.line.me/post/1168595921012325899)

**[TUGAS AKHIR PRAKTIKUM SAINS DATA dan PDNUM]**

Selamat sore, warga Departemen Matematika!

Berikut ini adalah tugas praktikum yang harus dikerjakan bagi mahasiswa yang mengambil mata kuliah Sains Data dan PDNum.

[https://drive.google.com/drive/folders/10hEyh6MTFnrx2kwC4IEL74cOCo-_NoNQ](https://drive.google.com/drive/folders/10hEyh6MTFnrx2kwC4IEL74cOCo-_NoNQ)

Tugas dikerjakan secara individu dengan ketentuan yang sudah tentukan di masing masing tugas yang tertera pada tautan di atas.

Tugas dikumpulkan paling lambat pada hari Rabu, 21 Juni 2023 pukul 23.59 WIB melalui tautan berikut.

Sains Data: [https://forms.gle/4i2tj8Zf7v7kDPoG7](https://forms.gle/4i2tj8Zf7v7kDPoG7)

PDNum: [https://forms.gle/m8s6iqyufpH9g3fUA](https://forms.gle/m8s6iqyufpH9g3fUA)

Demikian informasi yang dapat kami sampaikan. Jika ada pertanyaan lebih lanjut, silakan hubungi kontak berikut.

Narahubung:

■ Justin (LINE: iamjustin10)

■ Carles (LINE: Carles_octavianus)

■ Tulus (LINE: tlsnew)