<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tim Asisten Lab Matematika UI">
<meta name="dcterms.date" content="2026-09-21">

<title>Modul 3: R - Statistik Deskriptif dan Visualisasi Frekuensi – Lab Matematika UI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-07ba0ad10f5680c660e360ac31d2f3b6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8b864f0777c60eecff11d75b6b2e1175.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-b23fd6acf0dedb4246d7efc181bbfeaf.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../site_libs/bootstrap/bootstrap-dark-db4a9ea8999158859878766d6bd11a7f.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="icon" type="image/png" href="../../../../ico/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/svg+xml" href="../../../../ico/favicon.svg">
<link rel="shortcut icon" href="../../../../ico/favicon.ico">
<link rel="apple-touch-icon" sizes="180x180" href="../../../../ico/apple-touch-icon.png">
<meta name="apple-mobile-web-app-title" content="MyWebSite">
<link rel="manifest" href="../../../../ico/site.webmanifest">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer">


<link rel="stylesheet" href="../../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">Lab Matematika UI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../index.html"> <i class="bi bi-house" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../semuahalaman/about.html"> 
<span class="menu-text">Tentang Kami</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../blog.html"> 
<span class="menu-text">Berita</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-informasi-praktikum" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-info-circle" role="img">
</i> 
 <span class="menu-text">Informasi Praktikum</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-informasi-praktikum">    
        <li>
    <a class="dropdown-item" href="../../../../semuahalaman/praktikum.html">
 <span class="dropdown-text">Arsip Modul Praktikum</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../semuahalaman/Jadwal.html">
 <span class="dropdown-text">Jadwal Asistensi</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/aslab-math-ui/modul-prak"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tujuan-pembelajaran" id="toc-tujuan-pembelajaran" class="nav-link active" data-scroll-target="#tujuan-pembelajaran">Tujuan Pembelajaran</a></li>
  <li><a href="#skenario-misteri-bunga-iris" id="toc-skenario-misteri-bunga-iris" class="nav-link" data-scroll-target="#skenario-misteri-bunga-iris">1. Skenario: Misteri Bunga Iris 🕵️</a></li>
  <li><a href="#pemanasan-operasi-dasar-vector" id="toc-pemanasan-operasi-dasar-vector" class="nav-link" data-scroll-target="#pemanasan-operasi-dasar-vector">2. Pemanasan: Operasi Dasar &amp; <em>Vector</em></a>
  <ul class="collapse">
  <li><a href="#aritmatika-dan-variabel" id="toc-aritmatika-dan-variabel" class="nav-link" data-scroll-target="#aritmatika-dan-variabel">2.1. Aritmatika dan Variabel</a></li>
  <li><a href="#vector-menyimpan-kumpulan-data" id="toc-vector-menyimpan-kumpulan-data" class="nav-link" data-scroll-target="#vector-menyimpan-kumpulan-data">2.2. Vector: Menyimpan Kumpulan Data</a></li>
  </ul></li>
  <li><a href="#investigasi-data-iris" id="toc-investigasi-data-iris" class="nav-link" data-scroll-target="#investigasi-data-iris">3. Investigasi Data Iris</a>
  <ul class="collapse">
  <li><a href="#memuat-dan-melihat-data" id="toc-memuat-dan-melihat-data" class="nav-link" data-scroll-target="#memuat-dan-melihat-data">3.1. Memuat dan Melihat Data</a></li>
  <li><a href="#menjawab-pertanyaan-1-statistik-deskriptif" id="toc-menjawab-pertanyaan-1-statistik-deskriptif" class="nav-link" data-scroll-target="#menjawab-pertanyaan-1-statistik-deskriptif">3.2. Menjawab Pertanyaan 1: Statistik Deskriptif</a></li>
  <li><a href="#menjawab-pertanyaan-2-perbandingan-spesies" id="toc-menjawab-pertanyaan-2-perbandingan-spesies" class="nav-link" data-scroll-target="#menjawab-pertanyaan-2-perbandingan-spesies">3.3. Menjawab Pertanyaan 2: Perbandingan Spesies</a></li>
  <li><a href="#kesimpulan-investigasi" id="toc-kesimpulan-investigasi" class="nav-link" data-scroll-target="#kesimpulan-investigasi">Kesimpulan Investigasi</a></li>
  <li><a href="#lampiran-impor-data-dari-file-lokal" id="toc-lampiran-impor-data-dari-file-lokal" class="nav-link" data-scroll-target="#lampiran-impor-data-dari-file-lokal">Lampiran: Impor Data dari File Lokal</a></li>
  </ul></li>
  <li><a href="#investigasi-lebih-lanjut-dataset-iris" id="toc-investigasi-lebih-lanjut-dataset-iris" class="nav-link" data-scroll-target="#investigasi-lebih-lanjut-dataset-iris">Investigasi Lebih Lanjut Dataset Iris</a>
  <ul class="collapse">
  <li><a href="#boxplot" id="toc-boxplot" class="nav-link" data-scroll-target="#boxplot">Boxplot</a></li>
  <li><a href="#scatter" id="toc-scatter" class="nav-link" data-scroll-target="#scatter">Scatter</a></li>
  <li><a href="#lampiran-visualisasi-lain-yang-tersedia" id="toc-lampiran-visualisasi-lain-yang-tersedia" class="nav-link" data-scroll-target="#lampiran-visualisasi-lain-yang-tersedia">Lampiran: Visualisasi Lain yang Tersedia</a></li>
  </ul></li>
  <li><a href="#time-series-dan-line-chart" id="toc-time-series-dan-line-chart" class="nav-link" data-scroll-target="#time-series-dan-line-chart"><em>Time Series</em> dan <em>Line Chart</em></a></li>
  <li><a href="#mencari-data-time-series" id="toc-mencari-data-time-series" class="nav-link" data-scroll-target="#mencari-data-time-series">Mencari data <em>time series</em></a></li>
  <li><a href="#line-chart-instan-dari-objek-time-series" id="toc-line-chart-instan-dari-objek-time-series" class="nav-link" data-scroll-target="#line-chart-instan-dari-objek-time-series"><em>Line chart</em> instan dari objek <em>time series</em></a></li>
  <li><a href="#mengubah-time-series-object-menjadi-data-frame" id="toc-mengubah-time-series-object-menjadi-data-frame" class="nav-link" data-scroll-target="#mengubah-time-series-object-menjadi-data-frame">Mengubah <em>time series object</em> menjadi <em>data frame</em></a></li>
  <li><a href="#line-chart-dari-data-frame" id="toc-line-chart-dari-data-frame" class="nav-link" data-scroll-target="#line-chart-dari-data-frame"><em>Line chart</em> dari <em>data frame</em></a></li>
  <li><a href="#ggplot2" id="toc-ggplot2" class="nav-link" data-scroll-target="#ggplot2">ggplot2</a>
  <ul class="collapse">
  <li><a href="#dataset-yang-tersedia-di-ggplot2" id="toc-dataset-yang-tersedia-di-ggplot2" class="nav-link" data-scroll-target="#dataset-yang-tersedia-di-ggplot2"><em>Dataset</em> yang tersedia di <code>ggplot2</code></a></li>
  <li><a href="#dasar-dasar-ggplot2-dengan-line-chart" id="toc-dasar-dasar-ggplot2-dengan-line-chart" class="nav-link" data-scroll-target="#dasar-dasar-ggplot2-dengan-line-chart">Dasar-dasar <code>ggplot2</code> dengan <em>line chart</em></a></li>
  <li><a href="#scatter-1" id="toc-scatter-1" class="nav-link" data-scroll-target="#scatter-1"><em>Scatter</em></a></li>
  <li><a href="#bar-chart" id="toc-bar-chart" class="nav-link" data-scroll-target="#bar-chart"><em>Bar Chart</em></a></li>
  <li><a href="#pie-chart" id="toc-pie-chart" class="nav-link" data-scroll-target="#pie-chart"><em>Pie Chart</em></a></li>
  <li><a href="#histogram" id="toc-histogram" class="nav-link" data-scroll-target="#histogram"><em>Histogram</em></a></li>
  <li><a href="#boxplot-1" id="toc-boxplot-1" class="nav-link" data-scroll-target="#boxplot-1"><em>Boxplot</em></a></li>
  <li><a href="#lampiran-untuk-belajar-lebih-lanjut" id="toc-lampiran-untuk-belajar-lebih-lanjut" class="nav-link" data-scroll-target="#lampiran-untuk-belajar-lebih-lanjut">Lampiran untuk belajar lebih lanjut</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modul 3: R - Statistik Deskriptif dan Visualisasi Frekuensi</h1>
<p class="subtitle lead">Analisis Dataset Bunga Iris dan <em>Timeseries</em></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tim Asisten Lab Matematika UI </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="../psd2026ganjil.qmd" class="btn btn-outline-primary mb-4"> <i class="fa-solid fa-arrow-left"></i> Kembali ke Arsip Praktikum PSD </a></p>
<section id="tujuan-pembelajaran" class="level2">
<h2 class="anchored" data-anchor-id="tujuan-pembelajaran">Tujuan Pembelajaran</h2>
<p>Setelah menyelesaikan modul ini, mahasiswa diharapkan mampu:</p>
<ul>
<li><strong>1. Melakukan Operasi Dasar R</strong>
<ul>
<li>Menggunakan R untuk operasi aritmatika dan logika.</li>
<li>Memahami dan membuat objek dasar di R, yaitu <em>vector</em>.</li>
</ul></li>
<li><strong>2. Mengelola Data di RStudio</strong>
<ul>
<li>Mengimpor <em>dataset</em> dari file <code>.csv</code> ke dalam R sebagai sebuah <em>data frame</em>.</li>
<li>Melakukan inspeksi dasar pada <em>data frame</em> untuk memahami struktur dan isinya.</li>
<li>Memfilter (<em>subsetting</em>) data berdasarkan kriteria tertentu.</li>
</ul></li>
<li><strong>3. Menganalisis dan Memvisualisasikan Data</strong>
<ul>
<li>Menghitung statistik deskriptif dasar (mean, median, min, max, standar deviasi).</li>
<li>Membuat tabel frekuensi untuk data kategorik.</li>
<li>Membuat visualisasi frekuensi yang sesuai dengan tipe datanya (<em>bar chart</em>, <em>pie chart</em>, <em>histogram</em>).</li>
</ul></li>
</ul>
<hr>
</section>
<section id="skenario-misteri-bunga-iris" class="level2">
<h2 class="anchored" data-anchor-id="skenario-misteri-bunga-iris">1. Skenario: Misteri Bunga Iris 🕵️</h2>
<p>Selamat datang kembali! Di modul sebelumnya, kita sudah berhasil menyiapkan “bengkel” kerja kita. Sekarang, saatnya menggunakan alat-alat tersebut untuk memecahkan kasus pertama kita.</p>
<p>Seorang botanis (ahli tumbuhan) datang kepada kita dengan <em>dataset</em> berisi pengukuran 150 bunga Iris. Data ini terdiri dari tiga spesies berbeda. Sang botanis punya beberapa pertanyaan:</p>
<ol type="1">
<li><p>“Apa karakteristik umum dari data yang saya kumpulkan ini?”</p></li>
<li><p>“Apakah ada spesies yang cenderung memiliki kelopak (<em>sepal</em>) yang lebih panjang dibandingkan yang lain?”</p></li>
</ol>
<p>Tugas kita adalah menggunakan R untuk <strong>mengeksplorasi data, menghitung statistik dasar, dan membuat visualisasi</strong> untuk menjawab pertanyaan-pertanyaan tersebut.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tentang Dataset <code>iris</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Dataset</em> <code>iris</code> adalah data klasik dalam dunia statistika, berisi pengukuran empat fitur (panjang &amp; lebar kelopak dan mahkota bunga) dari tiga spesies Iris. <em>Dataset</em> ini sudah tersedia secara <em>built-in</em> di R, jadi kita bisa langsung menggunakannya.</p>
</div>
</div>
<hr>
</section>
<section id="pemanasan-operasi-dasar-vector" class="level2">
<h2 class="anchored" data-anchor-id="pemanasan-operasi-dasar-vector">2. Pemanasan: Operasi Dasar &amp; <em>Vector</em></h2>
<p>Sebelum membedah <em>dataset</em> <code>iris</code>, mari kita hangatkan jari kita dengan beberapa operasi dasar yang akan sering kita gunakan.</p>
<section id="aritmatika-dan-variabel" class="level3">
<h3 class="anchored" data-anchor-id="aritmatika-dan-variabel">2.1. Aritmatika dan Variabel</h3>
<p>Seperti yang kita pelajari di modul pertama, R bisa berfungsi sebagai kalkulator. Kita juga bisa menyimpan hasil perhitungan dalam variabel menggunakan <code>&lt;-</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Operasi dasar</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">5</span> <span class="sc">+</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Menyimpan hasil ke variabel</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lebar_kelopak <span class="ot">&lt;-</span> <span class="fl">2.5</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>panjang_kelopak <span class="ot">&lt;-</span> <span class="fl">4.5</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>luas_kelopak <span class="ot">&lt;-</span> lebar_kelopak <span class="sc">*</span> panjang_kelopak</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>luas_kelopak</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.25</code></pre>
</div>
</div>
</section>
<section id="vector-menyimpan-kumpulan-data" class="level3">
<h3 class="anchored" data-anchor-id="vector-menyimpan-kumpulan-data">2.2. Vector: Menyimpan Kumpulan Data</h3>
<p>Saat menganalisis data, kita jarang bekerja dengan satu angka saja. Kita akan bekerja dengan sekumpulan data. Di R, cara paling dasar untuk menyimpan sekumpulan data adalah dengan <strong>vector</strong>, menggunakan fungsi <code>c()</code> (<em>combine</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector berisi data numerik (lebar kelopak dari 3 bunga)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>kumpulan_lebar <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.5</span>, <span class="fl">3.1</span>, <span class="fl">2.8</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>kumpulan_lebar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.5 3.1 2.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector berisi data teks/karakter (nama spesies)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>kumpulan_spesies <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"setosa"</span>, <span class="st">"versicolor"</span>, <span class="st">"virginica"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>kumpulan_spesies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "setosa"     "versicolor" "virginica" </code></pre>
</div>
</div>
<p>Setiap kolom dalam sebuah tabel data di R pada dasarnya adalah sebuah <em>vector</em>.</p>
<hr>
</section>
</section>
<section id="investigasi-data-iris" class="level2">
<h2 class="anchored" data-anchor-id="investigasi-data-iris">3. Investigasi Data Iris</h2>
<p>Sekarang kita siap untuk memulai investigasi. Mari kita muat dan periksa data <code>iris</code>.</p>
<section id="memuat-dan-melihat-data" class="level3">
<h3 class="anchored" data-anchor-id="memuat-dan-melihat-data">3.1. Memuat dan Melihat Data</h3>
<p><em>Dataset</em> <code>iris</code> sudah tersedia di R. Kita cukup memanggilnya untuk melihatnya.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Memuat dataset (sebenarnya sudah aktif, tapi ini cara memastikannya)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"iris"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Melihat 6 baris pertama dari data</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
<p>Untuk mendapatkan gambaran umum tentang struktur data, gunakan <code>str()</code> (<em>structure</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Melihat struktur data: jumlah baris, kolom, nama kolom, dan tipe datanya</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Dari sini kita tahu ada 150 observasi, 5 kolom, dan tipe datanya adalah numerik (<code>num</code>) dan kategorik (<code>Factor</code> untuk Spesies).</p>
</section>
<section id="menjawab-pertanyaan-1-statistik-deskriptif" class="level3">
<h3 class="anchored" data-anchor-id="menjawab-pertanyaan-1-statistik-deskriptif">3.2. Menjawab Pertanyaan 1: Statistik Deskriptif</h3>
<p>Untuk menjawab pertanyaan pertama botanis (“Apa karakteristik umum dari data ini?”), kita bisa menggunakan statistik deskriptif.</p>
<ul>
<li><strong>Ringkasan Cepat</strong>: Gunakan fungsi <code>summary()</code> untuk mendapatkan ringkasan statistik (Min, Median, Mean, Max, Kuartil) untuk setiap kolom numerik.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                </code></pre>
</div>
</div>
<ul>
<li><strong>Perhitungan Spesifik</strong>: Anda juga bisa menghitung statistik satu per satu. Untuk mengakses satu kolom, gunakan simbol <code>$</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rata-rata panjang kelopak (Sepal.Length)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.843333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standar deviasi panjang kelopak</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(iris<span class="sc">$</span>Sepal.Length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8280661</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Nilai minimum dan maksimum</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(iris<span class="sc">$</span>Sepal.Length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(iris<span class="sc">$</span>Sepal.Length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.9</code></pre>
</div>
</div>
<p>Ini memberikan kita gambaran umum yang bagus tentang rentang dan pusat data kita.</p>
</section>
<section id="menjawab-pertanyaan-2-perbandingan-spesies" class="level3">
<h3 class="anchored" data-anchor-id="menjawab-pertanyaan-2-perbandingan-spesies">3.3. Menjawab Pertanyaan 2: Perbandingan Spesies</h3>
<p>Sekarang pertanyaan kedua: “Apakah ada spesies yang cenderung memiliki kelopak (<em>sepal</em>) yang lebih panjang?” Untuk menjawab ini, kita perlu <strong>memfilter</strong> data dan <strong>memvisualisasikannya</strong>.</p>
<section id="memfilter-data" class="level4">
<h4 class="anchored" data-anchor-id="memfilter-data">Memfilter Data</h4>
<p>Kita ingin melihat data hanya untuk spesies tertentu atau untuk bunga dengan kriteria tertentu. Gunakan fungsi <code>subset()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Membuat data frame baru yang hanya berisi spesies 'virginica'</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>iris_virginica <span class="ot">&lt;-</span> <span class="fu">subset</span>(iris, Species <span class="sc">==</span> <span class="st">"virginica"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Melihat 6 baris pertama dari data baru kita</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris_virginica)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
101          6.3         3.3          6.0         2.5 virginica
102          5.8         2.7          5.1         1.9 virginica
103          7.1         3.0          5.9         2.1 virginica
104          6.3         2.9          5.6         1.8 virginica
105          6.5         3.0          5.8         2.2 virginica
106          7.6         3.0          6.6         2.1 virginica</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Membuat data frame baru yang hanya berisi bunga dengan Sepal.Length &gt; 7.0</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>iris_panjang <span class="ot">&lt;-</span> <span class="fu">subset</span>(iris, Sepal.Length <span class="sc">&gt;</span> <span class="fl">7.0</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Melihat hasilnya</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>iris_panjang</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
103          7.1         3.0          5.9         2.1 virginica
106          7.6         3.0          6.6         2.1 virginica
108          7.3         2.9          6.3         1.8 virginica
110          7.2         3.6          6.1         2.5 virginica
118          7.7         3.8          6.7         2.2 virginica
119          7.7         2.6          6.9         2.3 virginica
123          7.7         2.8          6.7         2.0 virginica
126          7.2         3.2          6.0         1.8 virginica
130          7.2         3.0          5.8         1.6 virginica
131          7.4         2.8          6.1         1.9 virginica
132          7.9         3.8          6.4         2.0 virginica
136          7.7         3.0          6.1         2.3 virginica</code></pre>
</div>
</div>
<p>Dengan memfilter, kita bisa melihat bahwa bunga dengan kelopak sangat panjang mayoritas adalah spesies <code>virginica</code>.</p>
</section>
<section id="visualisasi-frekuensi" class="level4">
<h4 class="anchored" data-anchor-id="visualisasi-frekuensi">Visualisasi Frekuensi</h4>
<p>Cara terbaik untuk membandingkan adalah dengan visualisasi. Mari kita lihat distribusi frekuensi dari data kita.</p>
<ul>
<li><strong>Tabel Frekuensi</strong>: Pertama, kita hitung ada berapa bunga untuk setiap spesies.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>tabel_spesies <span class="ot">&lt;-</span> <span class="fu">table</span>(iris<span class="sc">$</span>Species)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>tabel_spesies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    setosa versicolor  virginica 
        50         50         50 </code></pre>
</div>
</div>
<ul>
<li><strong>Bar Chart</strong>: Visualisasi ini paling cocok untuk membandingkan jumlah antar kategori.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(tabel_spesies, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Distribusi Spesies Bunga Iris"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Spesies"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Jumlah Bunga"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"skyblue"</span>, <span class="st">"salmon"</span>, <span class="st">"lightgreen"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<pre><code>Dari sini terlihat bahwa jumlah data untuk setiap spesies sama (50).</code></pre>
<ul>
<li><strong>Histogram</strong>: Untuk melihat distribusi data numerik seperti <code>Sepal.Length</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(iris<span class="sc">$</span>Sepal.Length,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribusi Panjang Kelopak (Sepal)"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Panjang Kelopak (cm)"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Frekuensi"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"lavender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<pre><code>Histogram ini menunjukkan bahwa mayoritas bunga memiliki panjang kelopak antara 5.5 dan 6.5 cm.</code></pre>
</section>
</section>
<section id="kesimpulan-investigasi" class="level3">
<h3 class="anchored" data-anchor-id="kesimpulan-investigasi">Kesimpulan Investigasi</h3>
<p>Dengan analisis singkat ini, kita bisa kembali ke sang botanis dengan jawaban: 1. Karakteristik umum data menunjukkan panjang kelopak (Sepal) berkisar antara 4.3 hingga 7.9 cm, dengan rata-rata 5.84 cm. 2. Ya, ada spesies yang cenderung memiliki kelopak lebih panjang. Data menunjukkan bahwa bunga dengan panjang kelopak di atas 7 cm hampir seluruhnya adalah spesies <code>virginica</code>.</p>
</section>
<section id="lampiran-impor-data-dari-file-lokal" class="level3">
<h3 class="anchored" data-anchor-id="lampiran-impor-data-dari-file-lokal">Lampiran: Impor Data dari File Lokal</h3>
<p>Di dunia nyata, data tidak selalu ada di dalam R. Seringkali Anda akan mendapatkannya dalam bentuk file <code>.csv</code> atau <code>.xlsx</code>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Impor dari <code>.csv</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Impor dari <code>.xlsx</code></a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Untuk mengimpor file <code>.csv</code>, Anda perlu <em>library</em> <code>readr</code>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("readr") # Jalankan sekali jika belum terinstal</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Misalkan file Iris.csv ada di folder data</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>data_csv <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Iris.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Untuk mengimpor file Excel, Anda perlu <em>library</em> <code>readxl</code>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("readxl") # Jalankan sekali jika belum terinstal</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Misalkan file Iris.xlsx ada di folder data</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>data_excel <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/Iris.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
</section>
<section id="investigasi-lebih-lanjut-dataset-iris" class="level2">
<h2 class="anchored" data-anchor-id="investigasi-lebih-lanjut-dataset-iris">Investigasi Lebih Lanjut Dataset Iris</h2>
<p>Sebelumnya, kita sudah membuat visualisasi frekuensi dengan fungsi seperti <code>barplot</code>, <code>pie</code>, dan <code>hist</code>, yang “sudah ada dari sananya” atau disebut <em>built-in</em>. Untuk keperluan visualisasi dua variabel, juga tersedia beberapa fungsi <em>built-in</em>.</p>
<section id="boxplot" class="level3">
<h3 class="anchored" data-anchor-id="boxplot">Boxplot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> iris</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length) <span class="co">#1 variabel</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width) <span class="co">#2 variabel atau lebih</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot Perbandingan Sepal Length dan Sepal Width"</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sepal Length"</span>, <span class="st">"Sepal Width"</span>)) <span class="co">#tambahkan judul dan xlabel</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot Perbandingan Sepal Length dan Sepal Width"</span>,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sepal Length"</span>, <span class="st">"Sepal Width"</span>),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>)) <span class="co">#ganti warna</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot Perbandingan Sepal Length dan Sepal Width"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sepal Length"</span>, <span class="st">"Sepal Width"</span>),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">horizontal =</span> <span class="cn">TRUE</span>) <span class="co">#rotate jadi horizontal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Boxplot Perbandingan Sepal Length dan Sepal Width"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Sepal Length"</span>, <span class="st">"Sepal Width"</span>),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">notch =</span> <span class="cn">TRUE</span>) <span class="co"># jadi "mengerucut" di sekitar median</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length <span class="sc">~</span> df1<span class="sc">$</span>Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Sepal.Length <span class="sc">~</span> Species, <span class="at">data =</span> df1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df1<span class="sc">$</span>Sepal.Length <span class="sc">~</span> df1<span class="sc">$</span>Species, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Perbandingan Sepal Length berdasarkan Species"</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Species"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Sepal Length"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"yellow"</span>,<span class="st">"red"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="scatter" class="level3">
<h3 class="anchored" data-anchor-id="scatter">Scatter</h3>
<p>Untuk menggambar <em>scatter plot</em>, gunakan fungsi <code>plot</code></p>
<p>Plot paling dasar: semua variabel numerik menjadi scatter</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Scatter plot</em> antar dua variabel pilihan:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Tambahkan judul pakai <code>main</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Ini Judul grafiknya"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Tambahkan label sumbu</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width, </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Ini Judul grafiknya"</span>,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Sumbu X"</span>,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Sumbu Y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Beri warna</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df1<span class="sc">$</span>Sepal.Length, df1<span class="sc">$</span>Sepal.Width,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Scatter Plot Sepal Length dengan Sepal Width"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Sepal Length"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Sepal Width"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lampiran-visualisasi-lain-yang-tersedia" class="level3">
<h3 class="anchored" data-anchor-id="lampiran-visualisasi-lain-yang-tersedia">Lampiran: Visualisasi Lain yang Tersedia</h3>
<p>Selain <em>boxplot</em> dan <em>scatterplot</em>, tentunya R menyediakan fungsi <em>built-in</em> lain untuk visualisasi 2 variabel seperti <em>Stem and Leaf Plot</em> ataupun <em>Dot Diagram/Plot</em>.</p>
<section id="stem-and-leaf-plot" class="level4">
<h4 class="anchored" data-anchor-id="stem-and-leaf-plot"><em>Stem and Leaf Plot</em></h4>
<p>Untuk melihat persebaran data (min, max, distribusi), mirip histogram</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>?stem</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>starting httpd help server ... done</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(ChickWeight) <span class="co">#data dari r</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stem</span>(ChickWeight<span class="sc">$</span>weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

   2 | 599999999
   4 | 00000111111111111111111112222222222222223333456678888888899999999999+38
   6 | 00111111122222222333334444455555666677777888888900111111222222333334+8
   8 | 00112223344444455555566777788999990001223333566666788888889
  10 | 0000111122233333334566667778889901122223445555667789
  12 | 00002223333344445555667788890113444555566788889
  14 | 11123444455556666677788890011234444555666777777789
  16 | 00002233334444466788990000134445555789
  18 | 12244444555677782225677778889999
  20 | 0123444555557900245578
  22 | 0012357701123344556788
  24 | 08001699
  26 | 12344569259
  28 | 01780145
  30 | 355798
  32 | 12712
  34 | 1
  36 | 13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ChickWeight<span class="sc">$</span>weight) <span class="co">#buat perbandingan</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(ChickWeight<span class="sc">$</span>weight) <span class="co">#cek nilai minimumnya</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(ChickWeight<span class="sc">$</span>weight) <span class="co">#cek maxnya</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 373</code></pre>
</div>
</div>
<p>Kalau ternyata min sama maxnya kurang tepat, ganti scalenya</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stem</span>(ChickWeight<span class="sc">$</span>weight, <span class="at">scale =</span> <span class="dv">5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

   3 | 599999999
   4 | 000001111111111111111111122222222222222233334
   4 | 5667888888889999999999999
   5 | 00000011111111222233333444
   5 | 5555566667778888899999
   6 | 001111111222222223333344444
   6 | 555556666777778888889
   7 | 001111112222223333344444444
   7 | 6667778889999
   8 | 001122233444444
   8 | 5555556677778899999
   9 | 0001223333
   9 | 566666788888889
  10 | 0000111122233333334
  10 | 5666677788899
  11 | 0112222344
  11 | 5555667789
  12 | 0000222333334444
  12 | 555566778889
  13 | 0113444
  13 | 555566788889
  14 | 111234444
  14 | 5555666667778889
  15 | 0011234444
  15 | 555666777777789
  16 | 000022333344444
  16 | 6678899
  17 | 000013444
  17 | 5555789
  18 | 12244444
  18 | 55567778
  19 | 222
  19 | 5677778889999
  20 | 0123444
  20 | 5555579
  21 | 0024
  21 | 5578
  22 | 00123
  22 | 577
  23 | 01123344
  23 | 556788
  24 | 0
  24 | 8
  25 | 001
  25 | 699
  26 | 12344
  26 | 569
  27 | 2
  27 | 59
  28 | 01
  28 | 78
  29 | 014
  29 | 5
  30 | 3
  30 | 5579
  31 | 
  31 | 8
  32 | 12
  32 | 7
  33 | 12
  33 | 
  34 | 1
  34 | 
  35 | 
  35 | 
  36 | 1
  36 | 
  37 | 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stem</span>(ChickWeight<span class="sc">$</span>weight, <span class="at">width =</span> <span class="dv">100</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 1 digit(s) to the right of the |

   2 | 599999999
   4 | 0000011111111111111111111222222222222222333345667888888889999999999999000000111111112222+18
   6 | 0011111112222222233333444445555566667777788888890011111122222233333444444446667778889999
   8 | 00112223344444455555566777788999990001223333566666788888889
  10 | 0000111122233333334566667778889901122223445555667789
  12 | 00002223333344445555667788890113444555566788889
  14 | 11123444455556666677788890011234444555666777777789
  16 | 00002233334444466788990000134445555789
  18 | 12244444555677782225677778889999
  20 | 0123444555557900245578
  22 | 0012357701123344556788
  24 | 08001699
  26 | 12344569259
  28 | 01780145
  30 | 355798
  32 | 12712
  34 | 1
  36 | 13</code></pre>
</div>
</div>
</section>
<section id="dot-diagram" class="level4">
<h4 class="anchored" data-anchor-id="dot-diagram"><em>Dot Diagram</em></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>?dotchart</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Paling Sederhana</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>(mtcars<span class="sc">$</span>mpg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Tambah Judul dan Label</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>(mtcars<span class="sc">$</span>mpg, <span class="at">labels =</span> <span class="fu">row.names</span>(mtcars),</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">cex =</span> <span class="fl">0.9</span>, <span class="at">xlab =</span> <span class="st">"mpg"</span>,</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">"Persebaran Jarak Yang Dapat Ditempuh Per Galon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Berdasarkan Grup</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>grps <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mtcars<span class="sc">$</span>cyl)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>my_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"darkgreen"</span>, <span class="st">"orange"</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dotchart</span>(mtcars<span class="sc">$</span>mpg, <span class="at">labels =</span> <span class="fu">row.names</span>(mtcars),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">groups =</span> grps, <span class="at">gcolor =</span> my_cols,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">color =</span> my_cols[grps],</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">cex =</span> <span class="fl">0.9</span>,  <span class="at">pch =</span> <span class="dv">22</span>, <span class="at">xlab =</span> <span class="st">"mpg"</span>,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">"Persebaran Jarak Yang Dapat Ditempuh Per Galon Berdasarkan Jumlah Silinder"</span>)</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"4"</span>,<span class="st">"6"</span>, <span class="st">"6"</span>),</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> my_cols, <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="time-series-dan-line-chart" class="level2">
<h2 class="anchored" data-anchor-id="time-series-dan-line-chart"><em>Time Series</em> dan <em>Line Chart</em></h2>
<p>Data periodik terhadap waktu (misalnya data tahunan atau data bulanan) disebut <em>time series data</em> (data runtun waktu), biasa disebut <em>time series</em> saja atau disingkat “TS”. Visualisasi <em>line chart</em> biasa digunakan untuk data <em>time series</em>, dan begitu juga sebaliknya, data <em>time series</em> biasa divisualisasikan dengan <em>line chart</em>.</p>
</section>
<section id="mencari-data-time-series" class="level2">
<h2 class="anchored" data-anchor-id="mencari-data-time-series">Mencari data <em>time series</em></h2>
<p>Sayangnya, <em>dataset</em> <code>iris</code> tidak memiliki data <em>time series</em>. Bahkan, dari semua <em>dataset</em> yang <em>built-in</em>, data <em>time series</em> cenderung berupa <em>dataset</em> tersendiri, yang memang khusus menyimpan data variabel tertentu saja terhadap waktu.</p>
<p>Oleh karena itu, mari kita coba <em>dataset</em> lain. Kalian bisa melihat-lihat <em>dataset</em> yang sudah tersedia di R dengan perintah <code>data()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sebenarnya, tiap <em>dataset</em> berasal dari sebuah <em>package</em>. Perhatikan bahwa <em>dataset</em> <code>iris</code> berasal dari <em>package</em> bernama <code>datasets</code> (yang memang sudah <em>built-in</em>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>?iris</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Kita bisa spesifik melihat daftar <em>dataset</em> yang berasal dari <em>package</em> tertentu dengan tambahan opsi <code>package</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="at">package =</span> <span class="st">"datasets"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Untuk data <em>time series</em>, kita bisa mencoba misalnya <code>nhtemp</code>, rata-rata tahunan untuk suhu di kota New Haven di Amerika Serikat</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"nhtemp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mari kita lihat:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(nhtemp)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>nhtemp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time Series:
Start = 1912 
End = 1971 
Frequency = 1 
 [1] 49.9 52.3 49.4 51.1 49.4 47.9 49.8 50.9 49.3 51.9 50.8 49.6 49.3 50.6 48.4
[16] 50.7 50.9 50.6 51.5 52.8 51.8 51.1 49.8 50.2 50.4 51.6 51.8 50.9 48.8 51.7
[31] 51.0 50.6 51.7 51.5 52.1 51.3 51.0 54.0 51.4 52.7 53.1 54.6 52.0 52.0 50.9
[46] 52.6 50.2 52.6 51.6 51.9 50.5 50.9 51.7 51.4 51.7 50.8 51.9 51.8 51.9 53.0</code></pre>
</div>
</div>
<p>Terlihat bahwa data ini berupa <em>time series</em> yang tidak langsung berbentuk tabel. Di R, data berjenis <em>time series</em> memang diberi perhatian khusus, sehingga menjadi yang namanya <em>“time series object”</em>. Data runtun waktu dipelajari lebih lanjut di mata kuliah Metode Peramalan <em>(Forecasting Methods / Time Series Analysis)</em>.</p>
</section>
<section id="line-chart-instan-dari-objek-time-series" class="level2">
<h2 class="anchored" data-anchor-id="line-chart-instan-dari-objek-time-series"><em>Line chart</em> instan dari objek <em>time series</em></h2>
<p>Di pertemuan kali ini, kita hanya akan membuat visualisasinya dengan <em>line chart</em>.</p>
<p>Perhatian khusus tersebut ternyata sangat mempermudah cara memvisualisasikannya:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nhtemp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Langsung jadi!</p>
<p>Namun, apabila sewaktu-waktu kalian berurusan dengan tabel data yang sebenarnya berupa <em>time series</em>, mungkin R tidak akan langsung mengakuinya sebagai <em>time series</em>. Tidak masalah, karena kita masih bisa membuat <em>line chart</em> dari <em>data frame</em>.</p>
</section>
<section id="mengubah-time-series-object-menjadi-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="mengubah-time-series-object-menjadi-data-frame">Mengubah <em>time series object</em> menjadi <em>data frame</em></h2>
<p>Sebelum bisa membuat <em>line chart</em> dari <em>data frame</em>, datanya harus ada. Kalian bisa sewaktu-waktu <em>import</em> data kalian sendiri, kalau ada. Di sini, kita hanya akan mengubah <em>time series object</em> <code>nhtemp</code> menjadi <em>data frame</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>df_nhtemp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Time=</span><span class="fu">time</span>(nhtemp),</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Temp=</span><span class="fu">as.matrix</span>(nhtemp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mari kita lihat:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df_nhtemp)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>df_nhtemp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Time Temp
1  1912 49.9
2  1913 52.3
3  1914 49.4
4  1915 51.1
5  1916 49.4
6  1917 47.9
7  1918 49.8
8  1919 50.9
9  1920 49.3
10 1921 51.9
11 1922 50.8
12 1923 49.6
13 1924 49.3
14 1925 50.6
15 1926 48.4
16 1927 50.7
17 1928 50.9
18 1929 50.6
19 1930 51.5
20 1931 52.8
21 1932 51.8
22 1933 51.1
23 1934 49.8
24 1935 50.2
25 1936 50.4
26 1937 51.6
27 1938 51.8
28 1939 50.9
29 1940 48.8
30 1941 51.7
31 1942 51.0
32 1943 50.6
33 1944 51.7
34 1945 51.5
35 1946 52.1
36 1947 51.3
37 1948 51.0
38 1949 54.0
39 1950 51.4
40 1951 52.7
41 1952 53.1
42 1953 54.6
43 1954 52.0
44 1955 52.0
45 1956 50.9
46 1957 52.6
47 1958 50.2
48 1959 52.6
49 1960 51.6
50 1961 51.9
51 1962 50.5
52 1963 50.9
53 1964 51.7
54 1965 51.4
55 1966 51.7
56 1967 50.8
57 1968 51.9
58 1969 51.8
59 1970 51.9
60 1971 53.0</code></pre>
</div>
</div>
</section>
<section id="line-chart-dari-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="line-chart-dari-data-frame"><em>Line chart</em> dari <em>data frame</em></h2>
<p>Sekarang tinggal kita gambar, dengan cara menggambar <em>scatter plot</em> yang kemudian diberi opsi <code>type = "l"</code> agar menjadi <em>line chart</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_nhtemp<span class="sc">$</span>Time, df_nhtemp<span class="sc">$</span>Temp, <span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df_nhtemp<span class="sc">$</span>Time, df_nhtemp<span class="sc">$</span>Temp, <span class="at">type=</span><span class="st">"l"</span>,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Time"</span>, <span class="at">ylab=</span><span class="st">"Temp"</span>,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Average Yearly Temperature in New Haven"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Hmm, kurang bagus ya. Untuk <em>line chart</em> yang lebih bagus (dan juga berbagai <em>plot</em> lainnya) serta lebih fleksibel, selanjutnya kita akan mencoba <code>ggplot2</code>, sebuah <em>package</em> untuk <em>plotting</em> di R yang sangat terkenal dan sering digunakan di kalangan pengguna R.</p>
</section>
<section id="ggplot2" class="level2">
<h2 class="anchored" data-anchor-id="ggplot2">ggplot2</h2>
<p>Fungsi-fungsi <em>plot</em> yang tersedia di R secara <em>built-in</em> (terkadang disebut “base R”), yang sudah kita eksplorasi sejauh ini, cenderung terbatas dan tidak begitu fleksibel. Kalangan pengguna R cenderung menggunakan sebuah <em>package</em> terkenal di R untuk keperluan <em>plotting</em>, yaitu <code>ggplot2</code>.</p>
<p>Instal terlebih dahulu, kalau belum:</p>
<pre><code>install.packages("ggplot2")</code></pre>
<p>Lalu aktifkan:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dataset-yang-tersedia-di-ggplot2" class="level3">
<h3 class="anchored" data-anchor-id="dataset-yang-tersedia-di-ggplot2"><em>Dataset</em> yang tersedia di <code>ggplot2</code></h3>
<p>Kebetulan, <code>ggplot2</code> menyediakan beberapa <em>dataset</em> (yang tidak tersedia di <em>base R</em>) yang bisa kita gunakan untuk mempelajari dan mengeksplorasi <code>ggplot2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="at">package =</span> <span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Kita lihat, data <em>time series</em> tersedia di <code>ggplot2</code>, bernama <code>economics</code>. Mari kita lihat-lihat:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"economics"</span>, <span class="at">package =</span> <span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> economics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df2)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          date     pce      pop psavert uempmed unemploy
1   1967-07-01   506.7 198712.0    12.6     4.5     2944
2   1967-08-01   509.8 198911.0    12.6     4.7     2945
3   1967-09-01   515.6 199113.0    11.9     4.6     2958
4   1967-10-01   512.2 199311.0    12.9     4.9     3143
5   1967-11-01   517.4 199498.0    12.8     4.7     3066
6   1967-12-01   525.1 199657.0    11.8     4.8     3018
7   1968-01-01   530.9 199808.0    11.7     5.1     2878
8   1968-02-01   533.6 199920.0    12.3     4.5     3001
9   1968-03-01   544.3 200056.0    11.7     4.1     2877
10  1968-04-01   544.0 200208.0    12.3     4.6     2709
11  1968-05-01   549.8 200361.0    12.0     4.4     2740
12  1968-06-01   556.3 200536.0    11.7     4.4     2938
13  1968-07-01   563.2 200706.0    10.7     4.5     2883
14  1968-08-01   567.0 200898.0    10.5     4.2     2768
15  1968-09-01   568.2 201095.0    10.6     4.6     2686
16  1968-10-01   571.6 201290.0    10.8     4.8     2689
17  1968-11-01   576.7 201466.0    10.6     4.4     2715
18  1968-12-01   576.5 201621.0    11.1     4.4     2685
19  1969-01-01   583.5 201760.0    10.3     4.4     2718
20  1969-02-01   588.7 201881.0     9.7     4.9     2692
21  1969-03-01   588.9 202023.0    10.2     4.0     2712
22  1969-04-01   593.9 202161.0     9.7     4.0     2758
23  1969-05-01   600.3 202331.0    10.1     4.2     2713
24  1969-06-01   600.9 202507.0    11.1     4.4     2816
25  1969-07-01   602.7 202677.0    11.8     4.4     2868
26  1969-08-01   609.9 202877.0    11.5     4.4     2856
27  1969-09-01   613.2 203090.0    11.6     4.7     3040
28  1969-10-01   618.5 203302.0    11.4     4.5     3049
29  1969-11-01   620.5 203500.0    11.6     4.8     2856
30  1969-12-01   622.8 203675.0    11.8     4.6     2884
31  1970-01-01   628.7 203849.0    11.8     4.6     3201
32  1970-02-01   634.0 204008.0    11.7     4.5     3453
33  1970-03-01   632.3 204156.0    12.4     4.6     3635
34  1970-04-01   636.0 204401.0    13.3     4.1     3797
35  1970-05-01   642.4 204607.0    12.4     4.7     3919
36  1970-06-01   646.3 204830.0    12.3     4.9     4071
37  1970-07-01   648.5 205052.0    13.5     5.1     4175
38  1970-08-01   652.9 205295.0    13.4     5.4     4256
39  1970-09-01   659.1 205540.0    12.9     5.2     4456
40  1970-10-01   658.3 205788.0    13.1     5.2     4591
41  1970-11-01   656.6 206024.0    13.6     5.6     4898
42  1970-12-01   665.6 206238.0    13.2     5.9     5076
43  1971-01-01   676.1 206466.0    13.3     6.2     4986
44  1971-02-01   679.4 206668.0    13.3     6.3     4903
45  1971-03-01   682.0 206855.0    13.5     6.4     4987
46  1971-04-01   688.8 207065.0    13.2     6.5     4959
47  1971-05-01   691.1 207260.0    13.6     6.7     4996
48  1971-06-01   699.8 207462.0    14.7     5.7     4949
49  1971-07-01   698.9 207661.0    13.8     6.2     5035
50  1971-08-01   704.9 207881.0    13.6     6.4     5134
51  1971-09-01   713.0 208114.0    13.3     5.8     5042
52  1971-10-01   715.8 208345.0    13.3     6.5     4954
53  1971-11-01   720.9 208555.0    13.1     6.4     5161
54  1971-12-01   728.4 208740.0    13.0     6.2     5154
55  1972-01-01   731.5 208917.0    12.5     6.2     5019
56  1972-02-01   736.2 209061.0    12.8     6.6     4928
57  1972-03-01   749.2 209212.0    11.8     6.6     5038
58  1972-04-01   752.5 209386.0    11.5     6.7     4959
59  1972-05-01   758.0 209545.0    11.7     6.6     4922
60  1972-06-01   761.6 209725.0    11.7     5.4     4923
61  1972-07-01   769.9 209896.0    11.7     6.1     4913
62  1972-08-01   776.3 210075.0    12.0     6.0     4939
63  1972-09-01   781.1 210278.0    12.2     5.6     4849
64  1972-10-01   794.9 210479.0    13.0     5.7     4875
65  1972-11-01   800.5 210656.0    13.6     5.7     4602
66  1972-12-01   806.1 210821.0    13.7     6.1     4543
67  1973-01-01   816.5 210985.0    12.4     5.7     4326
68  1973-02-01   825.8 211120.0    12.5     5.2     4452
69  1973-03-01   832.8 211254.0    12.7     5.5     4394
70  1973-04-01   835.7 211420.0    13.2     5.0     4459
71  1973-05-01   841.6 211577.0    13.2     4.9     4329
72  1973-06-01   844.3 211746.0    13.6     5.0     4363
73  1973-07-01   854.1 211909.0    13.2     5.2     4305
74  1973-08-01   853.3 212092.0    13.9     4.9     4305
75  1973-09-01   869.2 212289.0    13.1     5.4     4350
76  1973-10-01   868.2 212475.0    14.4     5.5     4144
77  1973-11-01   876.9 212634.0    14.4     5.1     4396
78  1973-12-01   876.6 212785.0    14.8     4.7     4489
79  1974-01-01   884.5 212932.0    14.3     5.0     4644
80  1974-02-01   889.7 213074.0    14.2     5.1     4731
81  1974-03-01   901.4 213211.0    13.4     4.8     4634
82  1974-04-01   910.8 213361.0    13.1     5.0     4618
83  1974-05-01   922.4 213513.0    12.8     4.6     4705
84  1974-06-01   928.0 213686.0    12.8     5.3     4927
85  1974-07-01   937.9 213854.0    12.8     5.7     5063
86  1974-08-01   954.8 214042.0    12.1     5.0     5022
87  1974-09-01   955.1 214246.0    12.9     5.3     5437
88  1974-10-01   959.2 214451.0    13.4     5.5     5523
89  1974-11-01   956.2 214625.0    13.8     5.2     6140
90  1974-12-01   961.8 214782.0    14.0     5.7     6636
91  1975-01-01   975.6 214931.0    13.2     6.3     7501
92  1975-02-01   989.4 215065.0    12.5     7.1     7520
93  1975-03-01   990.6 215198.0    12.7     7.2     7978
94  1975-04-01   995.0 215353.0    14.2     8.7     8210
95  1975-05-01  1018.9 215523.0    17.3     9.4     8433
96  1975-06-01  1026.8 215768.0    14.3     8.8     8220
97  1975-07-01  1039.8 215973.0    12.6     8.6     8127
98  1975-08-01  1047.0 216195.0    13.0     9.2     7928
99  1975-09-01  1054.8 216393.0    13.0     9.2     7923
100 1975-10-01  1060.9 216587.0    13.4     8.6     7897
101 1975-11-01  1075.8 216771.0    12.7     9.5     7794
102 1975-12-01  1092.1 216931.0    12.0     9.0     7744
103 1976-01-01  1107.1 217095.0    11.7     9.0     7534
104 1976-02-01  1107.7 217249.0    12.3     8.2     7326
105 1976-03-01  1114.9 217381.0    12.2     8.7     7230
106 1976-04-01  1125.4 217528.0    11.7     8.2     7330
107 1976-05-01  1122.7 217685.0    12.3     8.3     7053
108 1976-06-01  1140.5 217861.0    11.4     7.8     7322
109 1976-07-01  1149.6 218035.0    11.7     7.7     7490
110 1976-08-01  1158.0 218233.0    11.7     7.9     7518
111 1976-09-01  1168.8 218440.0    11.4     7.8     7380
112 1976-10-01  1176.8 218644.0    11.1     7.7     7430
113 1976-11-01  1189.0 218834.0    11.4     8.4     7620
114 1976-12-01  1211.5 219006.0    10.6     8.0     7545
115 1977-01-01  1215.0 219179.0    10.6     7.5     7280
116 1977-02-01  1231.3 219344.0     9.3     7.2     7443
117 1977-03-01  1238.3 219504.0    10.5     7.2     7307
118 1977-04-01  1247.3 219684.0    10.5     7.3     7059
119 1977-05-01  1257.1 219859.0    10.3     7.9     6911
120 1977-06-01  1263.6 220046.0    10.6     6.2     7134
121 1977-07-01  1280.5 220239.0    10.5     7.1     6829
122 1977-08-01  1285.7 220458.0    10.9     7.0     6925
123 1977-09-01  1294.5 220688.0    11.1     6.7     6751
124 1977-10-01  1311.4 220904.0    11.0     6.9     6763
125 1977-11-01  1327.0 221109.0    11.2     7.0     6815
126 1977-12-01  1336.0 221303.0    11.4     6.8     6386
127 1978-01-01  1329.5 221477.0    11.9     6.5     6489
128 1978-02-01  1355.1 221629.0    11.1     6.7     6318
129 1978-03-01  1377.5 221792.0    11.0     6.2     6337
130 1978-04-01  1396.4 221991.0    10.8     6.1     6180
131 1978-05-01  1412.0 222176.0    10.3     5.7     6127
132 1978-06-01  1425.8 222379.0    10.0     6.0     6028
133 1978-07-01  1426.8 222585.0    10.9     5.8     6309
134 1978-08-01  1447.0 222805.0    10.5     5.8     6080
135 1978-09-01  1452.9 223053.0    10.6     5.6     6125
136 1978-10-01  1466.9 223271.0    10.7     5.9     5947
137 1978-11-01  1480.6 223477.0    10.5     5.5     6077
138 1978-12-01  1496.5 223670.0    10.4     5.6     6228
139 1979-01-01  1502.4 223865.0    11.1     5.9     6109
140 1979-02-01  1517.8 224053.0    11.1     5.9     6173
141 1979-03-01  1531.2 224235.0    11.2     5.9     6109
142 1979-04-01  1538.4 224438.0    11.0     5.4     6069
143 1979-05-01  1558.8 224632.0    10.3     5.6     5840
144 1979-06-01  1575.7 224843.0     9.9     5.6     5959
145 1979-07-01  1586.1 225055.0    10.6     5.9     5996
146 1979-08-01  1615.6 225295.0     9.7     4.8     6320
147 1979-09-01  1633.9 225547.0     9.4     5.5     6190
148 1979-10-01  1641.6 225801.0     9.7     5.5     6296
149 1979-11-01  1657.3 226027.0     9.7     5.3     6238
150 1979-12-01  1666.3 226243.0    10.1     5.7     6325
151 1980-01-01  1697.3 226451.0     9.9     5.3     6683
152 1980-02-01  1701.4 226656.0    10.1     5.8     6702
153 1980-03-01  1708.2 226849.0    10.2     6.0     6729
154 1980-04-01  1695.2 227061.0    11.3     5.8     7358
155 1980-05-01  1700.1 227251.0    11.4     5.7     7984
156 1980-06-01  1718.8 227522.0    11.2     6.4     8098
157 1980-07-01  1747.1 227726.0    11.3     7.0     8363
158 1980-08-01  1763.8 227953.0    11.3     7.5     8281
159 1980-09-01  1780.5 228186.0    11.7     7.7     8021
160 1980-10-01  1817.1 228417.0    11.3     7.5     8088
161 1980-11-01  1826.8 228612.0    11.6     7.7     8023
162 1980-12-01  1851.7 228779.0    11.4     7.5     7718
163 1981-01-01  1870.0 228937.0    10.9     7.4     8071
164 1981-02-01  1884.2 229071.0    10.8     7.1     8051
165 1981-03-01  1902.9 229224.0    10.8     7.1     7982
166 1981-04-01  1904.4 229403.0    10.9     7.4     7869
167 1981-05-01  1913.8 229575.0    11.0     6.9     8174
168 1981-06-01  1934.5 229761.0    10.8     6.6     8098
169 1981-07-01  1942.1 229966.0    12.3     7.1     7863
170 1981-08-01  1966.6 230187.0    12.0     7.2     8036
171 1981-09-01  1965.5 230412.0    12.4     6.8     8230
172 1981-10-01  1963.9 230641.0    13.0     6.8     8646
173 1981-11-01  1970.6 230822.0    13.2     6.9     9029
174 1981-12-01  1988.8 230989.0    12.5     6.9     9267
175 1982-01-01  1997.1 231157.0    12.7     7.1     9397
176 1982-02-01  2021.2 231313.0    12.1     7.5     9705
177 1982-03-01  2024.1 231470.0    12.2     7.7     9895
178 1982-04-01  2026.3 231645.0    12.9     8.1    10244
179 1982-05-01  2044.5 231809.0    12.3     8.5    10335
180 1982-06-01  2048.1 231992.0    12.3     9.5    10538
181 1982-07-01  2072.2 232188.0    12.5     8.5    10849
182 1982-08-01  2080.1 232392.0    12.6     8.7    10881
183 1982-09-01  2104.6 232599.0    11.8     9.5    11217
184 1982-10-01  2125.8 232816.0    11.3     9.7    11529
185 1982-11-01  2149.3 232993.0    10.9    10.0    11938
186 1982-12-01  2161.6 233160.0    10.9    10.2    12051
187 1983-01-01  2174.0 233322.0    11.1    11.1    11534
188 1983-02-01  2177.0 233473.0    11.1     9.8    11545
189 1983-03-01  2202.8 233613.0    10.6    10.4    11408
190 1983-04-01  2226.4 233781.0    10.3    10.9    11268
191 1983-05-01  2245.9 233922.0     9.9    12.3    11154
192 1983-06-01  2276.0 234118.0     9.1    11.3    11246
193 1983-07-01  2304.4 234307.0     9.6    10.1    10548
194 1983-08-01  2320.4 234501.0     9.2     9.3    10623
195 1983-09-01  2334.9 234701.0     9.6     9.3    10282
196 1983-10-01  2357.6 234907.0     9.7     9.4     9887
197 1983-11-01  2366.3 235078.0    10.3     9.3     9499
198 1983-12-01  2393.6 235235.0    10.1     8.7     9331
199 1984-01-01  2419.4 235385.0    10.0     9.1     9008
200 1984-02-01  2403.5 235527.0    11.7     8.3     8791
201 1984-03-01  2431.6 235675.0    11.5     8.3     8746
202 1984-04-01  2457.5 235839.0    11.5     8.2     8762
203 1984-05-01  2474.5 235993.0    11.1     9.1     8456
204 1984-06-01  2495.6 236160.0    11.1     7.5     8226
205 1984-07-01  2494.6 236348.0    11.6     7.5     8537
206 1984-08-01  2512.2 236549.0    11.8     7.3     8519
207 1984-09-01  2533.8 236760.0    11.8     7.6     8367
208 1984-10-01  2531.3 236976.0    11.7     7.2     8381
209 1984-11-01  2571.4 237159.0    10.9     7.2     8198
210 1984-12-01  2582.6 237316.0    11.2     7.3     8358
211 1985-01-01  2618.8 237468.0    10.3     6.8     8423
212 1985-02-01  2640.8 237602.0     9.1     7.1     8321
213 1985-03-01  2648.5 237732.0     8.7     7.1     8339
214 1985-04-01  2659.5 237900.0     9.9     6.9     8395
215 1985-05-01  2696.4 238074.0    11.1     6.9     8302
216 1985-06-01  2689.4 238270.0     9.6     6.6     8460
217 1985-07-01  2715.7 238466.0     9.1     6.9     8513
218 1985-08-01  2752.1 238679.0     8.2     7.1     8196
219 1985-09-01  2794.7 238898.0     7.3     6.9     8248
220 1985-10-01  2755.8 239113.0     9.1     7.1     8298
221 1985-11-01  2771.1 239307.0     9.0     7.0     8128
222 1985-12-01  2811.3 239477.0     8.6     6.8     8138
223 1986-01-01  2827.1 239638.0     8.6     6.7     7795
224 1986-02-01  2820.2 239788.0     9.3     6.9     8402
225 1986-03-01  2823.6 239928.0     9.9     6.8     8383
226 1986-04-01  2835.2 240094.0     9.7     6.7     8364
227 1986-05-01  2857.5 240271.0     9.3     6.8     8439
228 1986-06-01  2861.7 240459.0     9.4     7.0     8508
229 1986-07-01  2881.2 240651.0     9.3     6.9     8319
230 1986-08-01  2898.6 240854.0     9.0     7.1     8135
231 1986-09-01  2971.8 241068.0     7.2     7.4     8310
232 1986-10-01  2932.9 241274.0     8.4     7.0     8243
233 1986-11-01  2928.4 241467.0     8.8     7.1     8159
234 1986-12-01  2997.1 241620.0     7.0     7.1     7883
235 1987-01-01  2935.5 241784.0     9.7     6.9     7892
236 1987-02-01  3001.7 241930.0     8.5     6.6     7865
237 1987-03-01  3013.3 242079.0     8.5     6.6     7862
238 1987-04-01  3038.8 242252.0     4.5     7.1     7542
239 1987-05-01  3048.4 242423.0     8.2     6.6     7574
240 1987-06-01  3072.8 242608.0     7.7     6.5     7398
241 1987-07-01  3094.7 242804.0     7.5     6.5     7268
242 1987-08-01  3130.8 243012.0     7.2     6.4     7261
243 1987-09-01  3126.5 243223.0     7.6     6.0     7102
244 1987-10-01  3134.5 243446.0     8.3     6.3     7227
245 1987-11-01  3144.2 243639.0     8.5     6.2     7035
246 1987-12-01  3174.1 243809.0     8.7     6.0     6936
247 1988-01-01  3213.7 243981.0     8.1     6.2     6953
248 1988-02-01  3221.4 244131.0     8.6     6.3     6929
249 1988-03-01  3260.5 244279.0     8.2     6.4     6876
250 1988-04-01  3263.0 244445.0     8.8     5.9     6601
251 1988-05-01  3293.6 244610.0     8.4     5.9     6779
252 1988-06-01  3318.5 244806.0     8.4     5.8     6546
253 1988-07-01  3342.7 245021.0     8.6     6.1     6605
254 1988-08-01  3368.0 245240.0     8.4     5.9     6843
255 1988-09-01  3375.0 245464.0     8.9     5.7     6604
256 1988-10-01  3413.7 245693.0     8.6     5.6     6568
257 1988-11-01  3430.2 245884.0     8.4     5.7     6537
258 1988-12-01  3459.7 246056.0     8.3     5.9     6518
259 1989-01-01  3483.7 246224.0     8.5     5.6     6682
260 1989-02-01  3488.0 246378.0     9.0     5.4     6359
261 1989-03-01  3498.8 246530.0     9.5     5.4     6205
262 1989-04-01  3543.0 246721.0     8.4     5.4     6468
263 1989-05-01  3551.8 246906.0     8.1     5.3     6375
264 1989-06-01  3566.6 247114.0     8.2     5.4     6577
265 1989-07-01  3585.7 247342.0     8.2     5.6     6495
266 1989-08-01  3620.6 247573.0     7.6     5.0     6511
267 1989-09-01  3621.9 247816.0     8.1     4.9     6590
268 1989-10-01  3633.6 248067.0     8.5     4.9     6630
269 1989-11-01  3643.3 248281.0     8.6     4.8     6725
270 1989-12-01  3684.2 248479.0     7.8     4.9     6667
271 1990-01-01  3730.7 248659.0     8.0     5.1     6752
272 1990-02-01  3728.2 248827.0     8.6     5.3     6651
273 1990-03-01  3754.9 249012.0     8.3     5.1     6598
274 1990-04-01  3770.0 249306.0     8.8     4.8     6797
275 1990-05-01  3775.8 249565.0     8.7     5.2     6742
276 1990-06-01  3804.5 249849.0     8.6     5.2     6590
277 1990-07-01  3821.7 250132.0     8.7     5.4     6922
278 1990-08-01  3848.3 250439.0     8.1     5.4     7188
279 1990-09-01  3870.1 250751.0     8.1     5.6     7368
280 1990-10-01  3870.6 251057.0     7.8     5.8     7459
281 1990-11-01  3871.9 251346.0     7.9     5.7     7764
282 1990-12-01  3861.3 251626.0     8.8     5.9     7901
283 1991-01-01  3841.0 251889.0     9.3     6.0     8015
284 1991-02-01  3866.7 252135.0     8.8     6.2     8265
285 1991-03-01  3913.0 252372.0     8.0     6.7     8586
286 1991-04-01  3907.1 252643.0     8.6     6.6     8439
287 1991-05-01  3933.2 252913.0     8.4     6.4     8736
288 1991-06-01  3940.5 253207.0     8.9     6.9     8692
289 1991-07-01  3966.0 253493.0     8.2     7.0     8586
290 1991-08-01  3969.1 253807.0     8.6     7.3     8666
291 1991-09-01  3984.7 254126.0     8.8     6.8     8722
292 1991-10-01  3976.0 254435.0     9.3     7.2     8842
293 1991-11-01  4003.6 254718.0     9.0     7.5     8931
294 1991-12-01  4020.5 254964.0     9.7     7.8     9198
295 1992-01-01  4084.7 255214.0     9.4     8.1     9283
296 1992-02-01  4099.5 255448.0     9.8     8.2     9454
297 1992-03-01  4117.0 255703.0     9.7     8.3     9460
298 1992-04-01  4131.5 255992.0     9.9     8.5     9415
299 1992-05-01  4158.4 256285.0     9.9     8.8     9744
300 1992-06-01  4177.1 256589.0    10.1     8.7    10040
301 1992-07-01  4204.8 256894.0     9.6     8.6     9850
302 1992-08-01  4220.9 257232.0     9.7     8.8     9787
303 1992-09-01  4255.3 257548.0     8.7     8.6     9781
304 1992-10-01  4284.7 257861.0     8.0     9.0     9398
305 1992-11-01  4300.5 258147.0     8.0     9.0     9565
306 1992-12-01  4336.4 258413.0    10.6     9.3     9557
307 1993-01-01  4340.7 258679.0     8.6     8.6     9325
308 1993-02-01  4355.3 258919.0     8.9     8.5     9183
309 1993-03-01  4352.5 259152.0     8.9     8.5     9056
310 1993-04-01  4393.4 259414.0     8.7     8.4     9110
311 1993-05-01  4422.4 259680.0     8.3     8.1     9149
312 1993-06-01  4440.0 259963.0     7.8     8.3     9121
313 1993-07-01  4468.9 260255.0     7.6     8.2     8930
314 1993-08-01  4481.1 260566.0     7.7     8.2     8763
315 1993-09-01  4511.5 260867.0     6.9     8.3     8714
316 1993-10-01  4532.8 261163.0     6.3     8.0     8750
317 1993-11-01  4554.1 261425.0     6.3     8.3     8542
318 1993-12-01  4571.1 261674.0     9.1     8.3     8477
319 1994-01-01  4585.1 261919.0     7.1     8.6     8630
320 1994-02-01  4632.6 262123.0     6.5     9.2     8583
321 1994-03-01  4646.0 262352.0     6.8     9.3     8470
322 1994-04-01  4671.1 262631.0     6.4     9.1     8331
323 1994-05-01  4669.5 262877.0     7.6     9.2     7915
324 1994-06-01  4708.9 263152.0     6.9     9.3     7927
325 1994-07-01  4720.6 263436.0     7.0     9.0     7946
326 1994-08-01  4762.6 263724.0     6.5     8.9     7933
327 1994-09-01  4775.0 264017.0     6.8     9.2     7734
328 1994-10-01  4812.9 264301.0     7.1    10.0     7632
329 1994-11-01  4825.6 264559.0     7.0     9.0     7375
330 1994-12-01  4841.6 264804.0     7.2     8.7     7230
331 1995-01-01  4851.2 265044.0     7.5     8.0     7375
332 1995-02-01  4850.8 265270.0     7.8     8.1     7187
333 1995-03-01  4885.4 265495.0     7.5     8.3     7153
334 1995-04-01  4890.2 265755.0     6.9     8.3     7645
335 1995-05-01  4933.1 265998.0     7.1     9.1     7430
336 1995-06-01  4977.5 266270.0     6.7     7.9     7427
337 1995-07-01  4970.2 266557.0     7.1     8.5     7527
338 1995-08-01  5005.3 266843.0     6.7     8.3     7484
339 1995-09-01  5020.5 267152.0     6.8     7.9     7478
340 1995-10-01  5013.9 267456.0     7.1     8.2     7328
341 1995-11-01  5055.6 267715.0     6.6     8.0     7426
342 1995-12-01  5097.5 267943.0     6.1     8.3     7423
343 1996-01-01  5085.7 268151.0     6.7     8.3     7491
344 1996-02-01  5132.8 268364.0     6.7     7.8     7313
345 1996-03-01  5173.3 268595.0     6.6     8.3     7318
346 1996-04-01  5208.0 268853.0     5.7     8.6     7415
347 1996-05-01  5223.8 269108.0     6.7     8.6     7423
348 1996-06-01  5229.8 269386.0     7.1     8.3     7095
349 1996-07-01  5251.9 269667.0     6.7     8.3     7337
350 1996-08-01  5275.0 269976.0     6.6     8.4     6882
351 1996-09-01  5296.6 270284.0     6.7     8.5     6979
352 1996-10-01  5328.5 270581.0     6.4     8.3     7031
353 1996-11-01  5351.2 270878.0     6.4     7.7     7236
354 1996-12-01  5378.6 271125.0     6.4     7.8     7253
355 1997-01-01  5411.1 271360.0     6.2     7.8     7158
356 1997-02-01  5434.0 271585.0     6.2     8.1     7102
357 1997-03-01  5454.2 271821.0     6.4     7.9     7000
358 1997-04-01  5459.3 272083.0     6.5     8.3     6873
359 1997-05-01  5460.2 272342.0     6.8     8.0     6655
360 1997-06-01  5494.2 272622.0     6.6     8.0     6799
361 1997-07-01  5548.8 272912.0     6.1     8.3     6655
362 1997-08-01  5587.0 273237.0     6.0     7.8     6608
363 1997-09-01  5601.7 273553.0     6.2     8.2     6656
364 1997-10-01  5637.7 273852.0     6.2     7.7     6454
365 1997-11-01  5661.1 274126.0     6.4     7.6     6308
366 1997-12-01  5692.1 274372.0     6.4     7.5     6476
367 1998-01-01  5689.9 274626.0     7.4     7.4     6368
368 1998-02-01  5723.8 274838.0     7.4     7.0     6306
369 1998-03-01  5750.3 275047.0     7.5     6.8     6422
370 1998-04-01  5788.1 275304.0     7.2     6.7     5941
371 1998-05-01  5837.9 275564.0     6.9     6.0     6047
372 1998-06-01  5871.7 275836.0     6.8     6.9     6212
373 1998-07-01  5890.0 276115.0     6.9     6.7     6259
374 1998-08-01  5925.0 276418.0     6.8     6.8     6179
375 1998-09-01  5965.6 276714.0     6.4     6.7     6300
376 1998-10-01  5998.8 277003.0     6.2     5.8     6280
377 1998-11-01  6015.4 277277.0     6.3     6.6     6100
378 1998-12-01  6070.5 277526.0     5.8     6.8     6032
379 1999-01-01  6072.9 277790.0     6.4     6.9     5976
380 1999-02-01  6101.8 277992.0     6.2     6.8     6111
381 1999-03-01  6132.9 278198.0     5.9     6.8     5783
382 1999-04-01  6196.2 278451.0     5.2     6.2     6004
383 1999-05-01  6225.7 278717.0     4.9     6.5     5796
384 1999-06-01  6254.0 279001.0     4.8     6.3     5951
385 1999-07-01  6281.5 279295.0     4.8     5.8     6025
386 1999-08-01  6326.5 279602.0     4.7     6.5     5838
387 1999-09-01  6378.8 279903.0     4.2     6.0     5915
388 1999-10-01  6402.1 280203.0     4.6     6.1     5778
389 1999-11-01  6437.9 280471.0     4.8     6.2     5716
390 1999-12-01  6538.7 280716.0     4.4     5.8     5653
391 2000-01-01  6535.3 280976.0     5.4     5.8     5708
392 2000-02-01  6619.7 281190.0     4.8     6.1     5858
393 2000-03-01  6685.8 281409.0     4.5     6.0     5733
394 2000-04-01  6671.1 281653.0     5.0     6.1     5481
395 2000-05-01  6707.6 281877.0     4.9     5.8     5758
396 2000-06-01  6743.9 282126.0     4.9     5.7     5651
397 2000-07-01  6764.1 282385.0     5.2     6.0     5747
398 2000-08-01  6799.1 282653.0     5.2     6.3     5853
399 2000-09-01  6882.9 282932.0     4.5     5.2     5625
400 2000-10-01  6888.2 283201.0     4.6     6.1     5534
401 2000-11-01  6902.4 283453.0     4.5     6.1     5639
402 2000-12-01  6945.7 283696.0     4.2     6.0     5634
403 2001-01-01  6977.0 283920.0     4.8     5.8     6023
404 2001-02-01  6995.8 284137.0     4.9     6.1     6089
405 2001-03-01  6987.9 284350.0     5.3     6.6     6141
406 2001-04-01  7001.2 284581.0     5.0     5.9     6271
407 2001-05-01  7047.1 284810.0     4.5     6.3     6226
408 2001-06-01  7060.7 285062.0     4.5     6.0     6484
409 2001-07-01  7072.2 285309.0     5.6     6.8     6583
410 2001-08-01  7108.9 285570.0     6.8     6.9     7042
411 2001-09-01  7012.8 285843.0     7.0     7.2     7142
412 2001-10-01  7208.4 286098.0     3.4     7.3     7694
413 2001-11-01  7167.9 286341.0     4.1     7.7     8003
414 2001-12-01  7147.7 286570.0     4.5     8.2     8258
415 2002-01-01  7174.3 286788.0     6.1     8.4     8182
416 2002-02-01  7218.3 286994.0     5.8     8.3     8215
417 2002-03-01  7237.2 287190.0     5.9     8.4     8304
418 2002-04-01  7305.4 287397.0     5.8     8.9     8599
419 2002-05-01  7282.7 287623.0     6.5     9.5     8399
420 2002-06-01  7318.2 287864.0     6.4    11.0     8393
421 2002-07-01  7380.4 288105.0     5.5     8.9     8390
422 2002-08-01  7401.5 288360.0     5.4     9.0     8304
423 2002-09-01  7391.0 288618.0     5.7     9.5     8251
424 2002-10-01  7430.7 288870.0     5.7     9.6     8307
425 2002-11-01  7459.7 289106.0     5.7     9.3     8520
426 2002-12-01  7512.8 289313.0     5.5     9.6     8640
427 2003-01-01  7533.1 289518.0     5.5     9.6     8520
428 2003-02-01  7535.9 289714.0     5.6     9.5     8618
429 2003-03-01  7598.4 289911.0     5.3     9.7     8588
430 2003-04-01  7621.0 290125.0     5.3    10.2     8842
431 2003-05-01  7628.1 290346.0     5.8     9.9     8957
432 2003-06-01  7678.6 290584.0     5.6    11.5     9266
433 2003-07-01  7738.2 290820.0     6.3    10.3     9011
434 2003-08-01  7834.5 291072.0     6.0    10.1     8896
435 2003-09-01  7835.0 291321.0     5.2    10.2     8921
436 2003-10-01  7845.7 291574.0     5.3    10.4     8732
437 2003-11-01  7899.6 291807.0     5.4    10.3     8576
438 2003-12-01  7929.2 292008.0     5.4    10.4     8317
439 2004-01-01  7987.4 292192.0     5.0    10.6     8370
440 2004-02-01  8019.8 292368.0     5.0    10.2     8167
441 2004-03-01  8076.0 292561.0     4.9    10.2     8491
442 2004-04-01  8088.6 292779.0     5.3     9.5     8170
443 2004-05-01  8163.2 292997.0     5.3     9.9     8212
444 2004-06-01  8147.2 293223.0     5.8    11.0     8286
445 2004-07-01  8218.9 293463.0     5.3     8.9     8136
446 2004-08-01  8253.1 293719.0     5.2     9.2     7990
447 2004-09-01  8321.1 293971.0     4.6     9.6     7927
448 2004-10-01  8374.6 294230.0     4.5     9.5     8061
449 2004-11-01  8420.6 294466.0     4.1     9.7     7932
450 2004-12-01  8481.5 294694.0     6.9     9.5     7934
451 2005-01-01  8470.2 294914.0     3.7     9.4     7784
452 2005-02-01  8529.2 295105.0     3.4     9.2     7980
453 2005-03-01  8569.5 295287.0     3.6     9.3     7737
454 2005-04-01  8645.6 295490.0     3.1     9.0     7672
455 2005-05-01  8643.9 295704.0     3.5     9.1     7651
456 2005-06-01  8724.8 295936.0     2.9     9.0     7524
457 2005-07-01  8829.5 296186.0     2.2     8.8     7406
458 2005-08-01  8832.4 296440.0     2.7     9.2     7345
459 2005-09-01  8885.8 296707.0     2.7     8.4     7553
460 2005-10-01  8926.6 296972.0     3.1     8.6     7453
461 2005-11-01  8938.5 297207.0     3.5     8.5     7566
462 2005-12-01  8969.6 297431.0     3.7     8.7     7279
463 2006-01-01  9059.8 297647.0     4.2     8.6     7064
464 2006-02-01  9090.1 297854.0     4.2     9.1     7184
465 2006-03-01  9122.1 298060.0     4.2     8.7     7072
466 2006-04-01  9174.8 298281.0     4.0     8.4     7120
467 2006-05-01  9215.1 298496.0     3.8     8.5     6980
468 2006-06-01  9240.8 298739.0     4.0     7.3     7001
469 2006-07-01  9322.6 298996.0     3.4     8.0     7175
470 2006-08-01  9321.8 299263.0     3.6     8.4     7091
471 2006-09-01  9354.7 299554.0     3.6     8.0     6847
472 2006-10-01  9373.2 299835.0     3.6     7.9     6727
473 2006-11-01  9380.2 300094.0     3.9     8.3     6872
474 2006-12-01  9469.0 300340.0     3.7     7.5     6762
475 2007-01-01  9516.3 300574.0     3.7     8.3     7116
476 2007-02-01  9546.8 300802.0     4.1     8.5     6927
477 2007-03-01  9585.1 301021.0     4.4     9.1     6731
478 2007-04-01  9615.7 301254.0     4.2     8.6     6850
479 2007-05-01  9651.3 301483.0     4.0     8.2     6766
480 2007-06-01  9667.3 301739.0     3.8     7.7     6979
481 2007-07-01  9709.6 302004.0     3.7     8.7     7149
482 2007-08-01  9753.9 302267.0     3.4     8.8     7067
483 2007-09-01  9797.9 302546.0     3.5     8.7     7170
484 2007-10-01  9827.0 302807.0     3.4     8.4     7237
485 2007-11-01  9897.8 303054.0     3.1     8.6     7240
486 2007-12-01  9908.4 303287.0     3.6     8.4     7645
487 2008-01-01  9930.0 303506.0     3.7     9.0     7685
488 2008-02-01  9913.4 303711.0     4.1     8.7     7497
489 2008-03-01  9959.4 303907.0     4.0     8.7     7822
490 2008-04-01  9996.8 304117.0     3.4     9.4     7637
491 2008-05-01 10053.8 304323.0     7.8     7.9     8395
492 2008-06-01 10107.9 304556.0     5.5     9.0     8575
493 2008-07-01 10104.7 304798.0     4.4     9.7     8937
494 2008-08-01 10094.7 305045.0     3.8     9.7     9438
495 2008-09-01 10043.5 305309.0     4.7    10.2     9494
496 2008-10-01  9960.3 305554.0     5.5    10.4    10074
497 2008-11-01  9820.8 305786.0     6.4     9.8    10538
498 2008-12-01  9730.7 306004.0     6.4    10.5    11286
499 2009-01-01  9783.8 306208.0     6.2    10.7    12058
500 2009-02-01  9766.0 306402.0     5.5    11.7    12898
501 2009-03-01  9718.5 306588.0     5.9    12.3    13426
502 2009-04-01  9724.8 306787.0     6.8    13.1    13853
503 2009-05-01  9748.9 306984.0     8.2    14.2    14499
504 2009-06-01  9806.9 307206.0     6.7    17.2    14707
505 2009-07-01  9841.7 307439.0     6.0    16.0    14601
506 2009-08-01  9961.0 307685.0     4.9    16.3    14814
507 2009-09-01  9883.4 307946.0     5.9    17.8    15009
508 2009-10-01  9931.9 308189.0     5.4    18.9    15352
509 2009-11-01  9940.5 308418.0     5.9    19.8    15219
510 2009-12-01  9998.9 308633.0     5.9    20.1    15098
511 2010-01-01 10001.8 308833.0     6.1    20.0    15046
512 2010-02-01 10030.6 309027.0     5.8    19.9    15113
513 2010-03-01 10089.1 309212.0     5.7    20.4    15202
514 2010-04-01 10112.9 309191.2     6.4    22.1    15325
515 2010-05-01 10131.0 309369.1     7.0    22.3    14849
516 2010-06-01 10151.4 309548.5     6.9    25.2    14474
517 2010-07-01 10184.7 309745.7     6.8    22.3    14512
518 2010-08-01 10228.2 309957.8     6.9    21.0    14648
519 2010-09-01 10249.0 310176.5     6.7    20.3    14579
520 2010-10-01 10304.7 310400.0     6.6    21.2    14516
521 2010-11-01 10354.7 310595.8     6.6    21.0    15081
522 2010-12-01 10392.1 310781.7     7.1    21.9    14348
523 2011-01-01 10435.5 310960.7     7.4    21.5    14013
524 2011-02-01 10470.1 311113.4     7.6    21.1    13820
525 2011-03-01 10550.5 311265.4     7.0    21.5    13737
526 2011-04-01 10587.6 311436.2     6.9    20.9    13957
527 2011-05-01 10612.0 311607.1     6.9    21.6    13855
528 2011-06-01 10636.8 311791.2     7.2    22.4    13962
529 2011-07-01 10677.5 311997.0     7.3    22.0    13763
530 2011-08-01 10700.6 312205.4     7.2    22.4    13818
531 2011-09-01 10738.1 312429.1     6.8    22.0    13948
532 2011-10-01 10753.1 312644.2     6.8    20.6    13594
533 2011-11-01 10759.5 312829.5     7.0    20.8    13302
534 2011-12-01 10772.2 313009.7     7.8    20.5    13093
535 2012-01-01 10862.1 313183.2     8.0    20.8    12797
536 2012-02-01 10953.5 313339.0     8.0    19.7    12813
537 2012-03-01 10951.8 313499.4     8.5    19.2    12713
538 2012-04-01 10979.7 313667.1     8.7    19.1    12646
539 2012-05-01 10968.6 313830.5     8.8    19.9    12660
540 2012-06-01 10946.3 314017.6     9.1    20.4    12692
541 2012-07-01 10977.2 314210.8     8.2    17.5    12656
542 2012-08-01 11004.1 314422.3     8.0    18.4    12471
543 2012-09-01 11061.5 314646.7     8.2    18.8    12115
544 2012-10-01 11099.8 314854.0     8.8    19.9    12124
545 2012-11-01 11136.8 315053.9     9.7    18.6    12005
546 2012-12-01 11140.5 315232.8    12.0    17.7    12298
547 2013-01-01 11202.8 315389.6     6.3    15.8    12471
548 2013-02-01 11239.6 315520.1     5.8    17.2    11950
549 2013-03-01 11227.1 315662.2     5.9    17.6    11689
550 2013-04-01 11205.4 315817.9     6.4    17.1    11760
551 2013-05-01 11244.6 315983.7     6.7    17.1    11654
552 2013-06-01 11268.8 316171.0     6.8    17.0    11751
553 2013-07-01 11296.7 316358.8     6.6    16.2    11335
554 2013-08-01 11329.2 316580.3     6.7    16.5    11279
555 2013-09-01 11366.9 316806.1     6.8    16.5    11270
556 2013-10-01 11419.8 317022.3     6.3    16.3    11136
557 2013-11-01 11487.6 317228.0     6.2    17.1    10787
558 2013-12-01 11517.9 317411.6     6.4    17.3    10404
559 2014-01-01 11512.5 317593.9     7.1    15.4    10202
560 2014-02-01 11566.2 317753.9     7.3    15.9    10349
561 2014-03-01 11643.0 317917.2     7.4    15.8    10380
562 2014-04-01 11702.6 318089.2     7.4    15.7     9702
563 2014-05-01 11748.4 318269.5     7.4    14.6     9859
564 2014-06-01 11817.0 318464.2     7.4    13.8     9460
565 2014-07-01 11860.5 318662.4     7.5    13.1     9608
566 2014-08-01 11944.3 318893.8     7.2    12.9     9599
567 2014-09-01 11957.4 319125.3     7.4    13.4     9262
568 2014-10-01 12023.0 319353.7     7.2    13.6     8990
569 2014-11-01 12051.4 319564.2     7.3    13.0     9090
570 2014-12-01 12062.0 319746.2     7.6    12.9     8717
571 2015-01-01 12046.0 319928.6     7.7    13.2     8903
572 2015-02-01 12082.4 320074.5     7.9    12.9     8610
573 2015-03-01 12158.3 320230.8     7.4    12.0     8504
574 2015-04-01 12193.8 320402.3     7.6    11.5     8526</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>(df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "date"     "pce"      "pop"      "psavert"  "uempmed"  "unemploy"</code></pre>
</div>
</div>
<p>Data <em>time series</em> ini terdiri dari sejumlah kolom terhadap waktu.</p>
</section>
<section id="dasar-dasar-ggplot2-dengan-line-chart" class="level3">
<h3 class="anchored" data-anchor-id="dasar-dasar-ggplot2-dengan-line-chart">Dasar-dasar <code>ggplot2</code> dengan <em>line chart</em></h3>
<p>Menggunakan <em>line chart</em>, kita bisa memvisualisasikan bagaimana perubahan suatu variabel terhadap variabel waktu (<code>date</code>). Misalnya, kita bisa melihat bagaimana perubahan banyaknya pengangguran (<code>unemploy</code>) dari tahun ke tahun.</p>
<p>Apabila kita gunakan fungsi <em>built-in</em> untuk <em>line chart</em>, jadinya seperti berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(df2<span class="sc">$</span>date, df2<span class="sc">$</span>unemploy,</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mari kita coba buat dengan <code>ggplot2</code>.</p>
<p>Langkah pertama adalah menentukan <em>data frame</em> yang ingin kita gunakan, serta variabel yang akan di sumbu x dan variabel yang akan di sumbu y. <em>Syntax</em>-nya seperti berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> unemploy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>aes</code> artinya <em>aesthetic</em> (estetika), sebenarnya dalam artian “sesuatu yang bisa dilihat”. Kita memang ingin melihat data <code>date</code> untuk sumbu x dan <code>unemploy</code> untuk sumbu y, sehingga kita tuliskan seperti itu.</p>
<p>Namun, sejauh ini, isi <em>plot</em> masih kosong. Kita baru membuat <em>canvas</em> nya saja, belum garis-garisnya.</p>
<p>Agar ada garis, kita “tambahkan” dengan fungsi <code>geom_line()</code> seperti berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> unemploy)) <span class="sc">+</span> </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mungkin tampak aneh, seolah-olah fungsi dijumlahkan dengan fungsi. Cara kerjanya kurang lebih seperti berikut.</p>
<ul>
<li><p>Sebenarnya, fungsi <code>ggplot</code> menghasilkan “objek” atau “benda” yang berupa <em>plot</em> kosong.</p></li>
<li><p>Serupa, fungsi <code>geom_line</code> menghasilkan “objek” berupa perintah untuk menggambarkan garis-garis.</p></li>
<li><p>Begitu kita jumlahkan, objek hasil <code>geom_line</code> diterapkan ke objek hasil <code>ggplot</code>.</p></li>
<li><p>Hasil jumlahnya berupa objek <em>plot</em> baru, yaitu <em>line chart</em> yang kita inginkan.</p></li>
<li><p>Objek baru itulah yang kemudian ditampilkan.</p></li>
</ul>
<p>Cara ini sangat berbeda dengan cara kerja fungsi-fungsi <em>plotting</em> di <em>base R</em> yang memang berupa perintah.</p>
<p>Penjumlahan seperti itu di <code>ggplot2</code> bisa kita bayangkan sebagai “komposisi”, yang pada akhirnya menghasilkan suatu objek <em>plot</em> akhir. Ibaratnya seperti penulisan penjumlahan bilangan di R,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>yang memang menggabungkan 2 dengan 3 untuk menghasilkan hasil akhir yaitu 5, yang kemudian ditampilkan.</p>
<p>Tentu, kita bisa menyimpan atau meng-<em>assign</em> hasil jumlah tersebut ke dalam variabel, yang kemudian bisa kita tampilkan, sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>hasil_jumlah <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>hasil_jumlah</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<p>Sebagaimana hasil penjumlahan bilangan itu bisa kita simpan ke dalam variabel, “hasil jumlahan <em>plot</em>” dalam penggunaan <code>ggplot2</code> sebenarnya juga bisa kita simpan ke dalam variabel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>tren_pengangguran <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> unemploy)) <span class="sc">+</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Karena sudah tersimpan ke dalam variabel, kita bisa menampilkan <em>plot</em> akhir tersebut kapan saja, cukup dengan memanggil variabelnya:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>tren_pengangguran</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fleksibilitas seperti ini tidak ada ketika kita menggunakan fungsi-fungsi <em>plotting</em> dari <em>base R</em>.</p>
<p>Tentunya, kita juga bisa menambahkan label, dengan menambahkan <code>labs</code> seperti berikut</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df2, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> unemploy)) <span class="sc">+</span> </span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Line Chart Tahun dengan Jumlah Pengangguran"</span>,</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Tahun"</span>,</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Jumlah Pengangguran"</span></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="scatter-1" class="level3">
<h3 class="anchored" data-anchor-id="scatter-1"><em>Scatter</em></h3>
<p>Penulisannya mirip, tetapi menggunakan <code>geom_point</code> daripada <code>geom_line</code></p>
<p>Secara tampilan pun, bedanya <em>line chart</em> dan <em>scatter plot</em> hanyalah pilihan antara menggambar garis atau menggambar titik-titik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length, <span class="at">y =</span> Sepal.Width)) <span class="sc">+</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita juga bisa menambahkan warna-warna sesuai kolom lain, misal berdasarkan spesies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length, <span class="at">y =</span> Sepal.Width, <span class="at">color =</span> Species)) <span class="sc">+</span> </span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Betapa fleksibelnya, ya! Fitur <em>scatter plot</em> <code>plot</code> di <em>base R</em> tidak se-fleksibel ini. Lebih nyaman juga, karena keterangan warna-warnanya juga langsung ada.</p>
<p>Jangan lupa tambahkan label dengan <code>labs</code> seperti berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length, <span class="at">y =</span> Sepal.Width, <span class="at">color =</span> Species)) <span class="sc">+</span> </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatter Plot Sepal Length vs Sepal Width"</span>,</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sepal Length"</span>,</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sepal Width"</span>,</span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Species Names"</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Contoh lain: <code>Petal.Length</code> vs.&nbsp;<code>Petal.Width</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width, <span class="at">color =</span> Species)) <span class="sc">+</span> </span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatter Plot Petal Length vs Petal Width"</span>,</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Petal Length"</span>,</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Petal Width"</span>,</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Species Names"</span></span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bar-chart" class="level3">
<h3 class="anchored" data-anchor-id="bar-chart"><em>Bar Chart</em></h3>
<p>Di pertemuan sebelumnya, kita sudah menggunakan <em>bar chart</em> untuk memvisualisasi frekuensi nilai-nilai di satu variabel, menggunakan <em>dataset</em> <code>iris</code>. Persebaran <code>Species</code> ternyata kurang menarik, kecuali apabila dilakukan <em>filter</em> data terlebih dahulu.</p>
<p>Agar lebih mudah, mari kita coba <em>dataset</em> lain yang sudah memiliki persebaran lebih menarik. Tidak harus dari <code>ggplot2</code>, bisa juga dari package* <code>datasets</code> yang <em>built-in</em>. Kita bisa cari-cari dulu:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="at">package =</span> <span class="st">"datasets"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Misalnya kita pilih <code>mtcars</code> dari <code>datasets</code> (daripada dari <code>ggplot2</code>), yang berisi data mobil-mobil dari majalah <em>Motor Trend</em> tahun 1974.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"mtcars"</span>, <span class="at">package =</span> <span class="st">"datasets"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> mtcars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Kita bisa lihat isinya:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df3)</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>df3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>(df3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "am"   "carb" "cyl"  "disp" "drat" "gear" "hp"   "mpg"  "qsec" "vs"  
[11] "wt"  </code></pre>
</div>
</div>
<p>Perhatikan bahwa tiap baris adalah mobil tersendiri, dan datanya memang tidak terlalu banyak. Salah satu kolomnya adalah <code>cyl</code>, banyaknya “silinder” untuk tiap mobil, yaitu mesin di dalam mobil yang biasa memompa bensin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>df3<span class="sc">$</span>cyl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 6 8 4</code></pre>
</div>
</div>
<p>Sepertinya persebarannya menarik. Tidak seperti fungsi <code>barplot</code> dari <em>base R</em>, di <code>ggplot2</code> kita tidak perlu membuat tabel frekuensi untuk membuat <em>bar chart</em>. Langsung saja tambahkan <code>geom_bar</code> seperti berikut. Karena hanya ada satu variabel, kita cukup pasang variabel sumbu x saja.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> cyl)) <span class="sc">+</span> </span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-70-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Untuk memberi warna, gunakan opsi <code>fill</code> di <code>aes</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> cyl, <span class="at">fill =</span> <span class="st">"red"</span>)) <span class="sc">+</span> </span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita juga bisa menentukan ketebalan dengan opsi <code>width</code> di <code>geom_bar</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> cyl, <span class="at">fill =</span> <span class="st">"red"</span>)) <span class="sc">+</span> </span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-72-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Seandainya kalian justru memiliki data yang berupa semacam tabel frekuensi saja, misalnya data <em>voting</em> anonim, <em>bar chart</em> masih bisa dibuat dengan fungsi terpisah yaitu <code>geom_col</code> daripada <code>geom_bar</code></p>
<p>Sebagai contoh, misalkan kita punya tabel frekuensi untuk variabel <code>cyl</code>, yang bisa kita peroleh sebagai berikut (seperti di pertemuan sebelumnya):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>cyl_freq <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(df3<span class="sc">$</span>cyl, <span class="at">dnn=</span><span class="st">"cyl"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(cyl_freq)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>cyl_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cyl Freq
1   4   11
2   6    7
3   8   14</code></pre>
</div>
</div>
<p>Kita bisa menggambar <em>bar chart</em> untuk tabel frekuensi tersebut dengan tambahan fungsi <code>geom_col</code> seperti berikut.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cyl_freq, <span class="fu">aes</span>(<span class="at">x =</span> cyl, <span class="at">y =</span> Freq)) <span class="sc">+</span> </span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-75-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita juga bisa memberi warna (dengan <code>fill</code> di <code>aes</code> di <code>ggplot</code>) dan menentukan lebar batang (dengan <code>width</code> di <code>geom_col</code>), sebagaimana ketika menggunakan <code>geom_bar</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cyl_freq, <span class="fu">aes</span>(<span class="at">x =</span> cyl, <span class="at">y =</span> Freq, <span class="at">fill =</span> <span class="st">"red"</span>)) <span class="sc">+</span> </span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-76-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pie-chart" class="level3">
<h3 class="anchored" data-anchor-id="pie-chart"><em>Pie Chart</em></h3>
<p>Selain <em>bar chart</em>, ada <em>pie chart</em> sebagai visualisasi yang berbeda untuk kegunaan yang sama. Sayangnya, di <code>ggplot2</code> tidak ada fungsi khusus untuk <em>pie chart</em>. Namun, kita bisa akali dengan membuat <em>bar chart</em> dengan <code>geom_bar</code> seperti berikut, yang kemudian diterapkan koordinat polar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>), <span class="at">fill =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span> </span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-77-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Di sini, fungsi <code>factor</code> diperlukan untuk memberitahu R bahwa data <code>cyl</code> berupa data kategorik. Kita juga pasang <code>x = factor(1)</code> karena di sini seolah-olah hanya ada satu batang di <em>bar chart</em> (yang kemudian diterapkan koordinat polar), dan kita biasa hanya memasang sumbu x ketika membuat <em>bar chart</em>.</p>
<p>Seperti biasa, kita bisa tambahkan <code>labs</code> untuk menentukan label, seperti menentukan judul, mengosongkan label sumbu x maupun sumbu y, dan menentukan label untuk opsi <code>fill</code> (yang saat ini terpasang menjadi <code>factor(cyl)</code>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df3, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>), <span class="at">fill =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">width =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Banyaknya Silinder di Mobil (dari Motor Trend, 1974)"</span>,</span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb122-8"><a href="#cb122-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"cyl (banyaknya silinder)"</span></span>
<span id="cb122-9"><a href="#cb122-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-78-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Apabila data kita berupa semacam tabel frekuensi saja, kita juga bisa melakukan hal serupa dengan <code>geom_col</code> agar tetap bisa membuat <em>pie chart</em>. Caranya seperti berikut, juga menggantikan <code>x = cyl</code> dengan <code>x = factor(1)</code>, sedangkan opsi <code>fill</code> tetap diberi <code>factor(cyl)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cyl_freq, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>), <span class="at">y =</span> Freq, <span class="at">fill =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span> </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Label bisa kita tentukan dengan menambahkan <code>labs</code> seperti biasa</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cyl_freq, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(<span class="dv">1</span>), <span class="at">y =</span> Freq, <span class="at">fill =</span> <span class="fu">factor</span>(cyl))) <span class="sc">+</span> </span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Pie Chart Banyaknya Silinder dari Tabel Frekuensi"</span>,</span>
<span id="cb124-6"><a href="#cb124-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb124-7"><a href="#cb124-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb124-8"><a href="#cb124-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"cyl (banyaknya silinder)"</span></span>
<span id="cb124-9"><a href="#cb124-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-80-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="histogram" class="level3">
<h3 class="anchored" data-anchor-id="histogram"><em>Histogram</em></h3>
<p>Di <code>ggplot2</code>, <em>histogram</em> juga seolah-olah seperti sejenis <em>bar chart</em>. Mari kita coba gambar <em>histogram</em> untuk <code>Sepal.Length</code> seperti di pertemuan sebelumnya. Kali ini, tambahkan <code>geom_histogram</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-81-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita bisa menentukan lebar batang di <em>histogram</em> dengan opsi <code>binwidth</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita juga bisa memberi opsi warna, yaitu <code>fill</code> untuk warna isi batangnya dan <code>color</code> untuk warna pinggiran batangnya.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-83-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="boxplot-1" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-1"><em>Boxplot</em></h3>
<p>Untuk <em>boxplot</em>, tambahkan <code>geom_boxplot</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kita juga bisa menenukan warna isi yaitu <code>fill</code> dan warna pinggiran yaitu <code>color</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df1, <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="modul3_files/figure-html/unnamed-chunk-85-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lampiran-untuk-belajar-lebih-lanjut" class="level3">
<h3 class="anchored" data-anchor-id="lampiran-untuk-belajar-lebih-lanjut">Lampiran untuk belajar lebih lanjut</h3>
<p>ggplot2:</p>
<p><a href="https://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html" class="uri">https://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html</a></p>
<hr>
<p><a href="../psd2026ganjil.qmd" class="btn btn-outline-primary mb-4"> <i class="fa-solid fa-arrow-left"></i> Kembali ke Arsip Praktikum PSD </a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Departemen Matematika FMIPA UI</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:aslab.math@sci.ui.ac.id">
      <i class="bi bi-envelope" role="img" aria-label="Email kami">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>